package local.pocketchat;

import android.app.*;
import android.content.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;

/** Functional module host. Existing chat controls, dialogs and drivers remain intact. */
final class AppHub {
  final MainActivity a;final LinearLayout root,bar;final View chat;final FrameLayout panel;int page;long navigation,lastHistorySync;final Button[] tabs=new Button[4];
  AppHub(MainActivity activity,LinearLayout root,View chat){a=activity;this.root=root;this.chat=chat;panel=new FrameLayout(a);panel.setVisibility(View.GONE);root.addView(panel,new LinearLayout.LayoutParams(-1,0,1));bar=new LinearLayout(a);bar.setBackgroundColor(Ui.SOFT);for(int i=0;i<4;i++){final int index=i;Button button=new Button(a);button.setAllCaps(false);button.setText(new String[]{"聊天","下载","窗口","设置"}[i]);button.setTextSize(12);button.setMinWidth(0);button.setMinimumWidth(0);bar.addView(button,new LinearLayout.LayoutParams(0,a.dp(48),1));tabs[i]=button;button.setOnClickListener(v->select(index));}root.addView(bar,new LinearLayout.LayoutParams(-1,a.dp(48)));mark();}
  void select(int target){if(target<0||target>3)return;if(target==2){a.startActivity(new Intent(a,WindowHomeActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_REORDER_TO_FRONT));return;}long token=++navigation;if(page==0&&target!=0){a.session.pageMemory.capture(()->{if(token==navigation)show(target);});}else show(target);}
  void show(int target){page=target;chat.setVisibility(page==0?View.VISIBLE:View.GONE);a.toolbar.setVisibility(page==0?View.VISIBLE:View.GONE);a.composer.setVisibility(page==0&&!a.pageMode?View.VISIBLE:View.GONE);panel.setVisibility(page==0?View.GONE:View.VISIBLE);a.session.foreground(a.active);mark();if(page!=0){((android.view.inputmethod.InputMethodManager)a.getSystemService(Context.INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(a.input.getWindowToken(),0);refresh();}else{a.session.pageMemory.restorePending=true;if(a.session.networkReady&&MainActivity.chatUrl(a.remote.getUrl()))a.session.pageMemory.restore(a.remote.getUrl(),a.session.navigationEpoch);a.session.wakePolling();}}
  void mark(){for(int i=0;i<tabs.length;i++){tabs[i].setTextColor(i==page?0xff164cf2:Ui.MUTED);tabs[i].setSelected(i==page);}}
  LinearLayout layout(String title){LinearLayout box=new LinearLayout(a);box.setOrientation(1);box.setPadding(a.dp(18),a.dp(14),a.dp(18),a.dp(18));TextView heading=a.label(title,22,Ui.INK);heading.setTypeface(android.graphics.Typeface.create("sans-serif-medium",0));box.addView(heading);ScrollView scroll=new ScrollView(a);scroll.addView(box);panel.removeAllViews();panel.addView(scroll,new FrameLayout.LayoutParams(-1,-1));return box;}
  void action(LinearLayout box,String text,Runnable run){Button b=new Button(a);b.setText(text);b.setAllCaps(false);box.addView(b,new LinearLayout.LayoutParams(-1,-2));b.setOnClickListener(v->run.run());}
  void note(LinearLayout box,String text){TextView t=a.label(text,14,Ui.MUTED);t.setPadding(0,a.dp(10),0,a.dp(10));box.addView(t);}
  void refresh(){if(page==1)downloads();if(page==2)environments();if(page==3)settings();}
  void downloads(){LinearLayout box=layout("下载与文件");note(box,"默认保存位置："+DefaultDownloads.description(a)+"\n下载完成自动保存。点文件可打开、分享或另存为。");action(box,"查看所有窗口的已下载文件",()->a.startActivity(new Intent(a,DownloadCenterActivity.class)));action(box,"打开下载管理",()->a.downloads.history());action(box,"仅 Wi-Fi 下载："+(AppPrefs.enabled(a,"wifiDownloads")?"开启":"关闭"),()->EnvironmentEditorUi.show(a));for(int i=0;i<a.downloads.tasks.rows.length();i++){JSONObject row=a.downloads.tasks.rows.optJSONObject(i);action(box,row.optString("name")+" · "+DownloadTasks.label(row.optString("state")),()->a.downloads.taskActions(row));}if(a.downloads.tasks.rows.length()==0)note(box,"还没有下载任务。");}
  Set<Integer> live(){Set<Integer> ids=new HashSet<>();try{List<ActivityManager.RunningAppProcessInfo> rows=a.getSystemService(ActivityManager.class).getRunningAppProcesses();if(rows!=null)for(ActivityManager.RunningAppProcessInfo r:rows)ids.add(r.pid);}catch(Exception ignored){}return ids;}
  void environments(){ProfileCatalog catalog=ProfileCatalog.get(a);catalog.heartbeat(a.session,true);LinearLayout box=layout("独立环境");JSONArray rows=catalog.list();int count=0;for(int i=0;i<rows.length();i++)if(rows.optJSONObject(i).optBoolean("created"))count++;note(box,"已创建 "+count+" / "+Profiles.MAX+" 个环境。Android 9 及以上使用独立进程和 WebView 数据目录，登录和聊天数据分别保存。不会自动生成不同出口或伪造设备身份。");action(box,"＋ 创建新环境",()->createEnvironment());Set<Integer> live=live();for(int i=0;i<rows.length();i++){JSONObject row=rows.optJSONObject(i);if(!row.optBoolean("created"))continue;int id=row.optInt("slot");boolean current=id==Profiles.slot(a),alive=live.contains(row.optInt("pid")),fresh=System.currentTimeMillis()-row.optLong("seen")<60000;String status=current?"当前环境":alive?fresh?row.optBoolean("waiting")?"正在等待回复":row.optBoolean("connected")?"进程运行，连接已记录":"已启动":"进程运行，状态待更新":"未启动";LinearLayout card=new LinearLayout(a);card.setOrientation(1);card.setPadding(a.dp(12),a.dp(10),a.dp(12),a.dp(10));card.setBackground(Ui.shape(a,Ui.SOFT,14));TextView title=a.label(row.optString("name")+" · "+status,17,Ui.INK);card.addView(title);card.addView(a.label("chatgpt.com · 独立 Cookie / 本机记录\n网络："+(current?a.session.internalNetwork()?"内置网络":a.prefs.getString("proxy","").isEmpty()?"手机网络":"应用代理":row.optString("mode","未记录")),13,Ui.MUTED));LinearLayout actions=new LinearLayout(a);a.button("打开",actions,v->open(id,false));a.button("编辑",actions,v->open(id,true));card.addView(actions);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=a.dp(10);box.addView(card,p);}action(box,"刷新环境状态",()->environments());action(box,"当前环境隐私与自检",()->ProfileUi.show(a));}
  void createEnvironment(){if(Build.VERSION.SDK_INT<28){a.status("独立环境需要 Android 9 或更新版本");return;}JSONArray rows=ProfileCatalog.get(a).list();int target=-1;for(int i=1;i<rows.length();i++)if(!rows.optJSONObject(i).optBoolean("created")){target=i;break;}if(target<0){a.status("已达到 "+Profiles.MAX+" 个环境，已有环境均已保留");return;}int id=target;EditText name=new EditText(a);name.setSingleLine(true);name.setText("环境 "+(id+1));CheckBox copy=new CheckBox(a);copy.setText("复制当前网络配置，不复制登录、Cookie、聊天或基线");copy.setChecked(true);LinearLayout box=new LinearLayout(a);box.setOrientation(1);box.setPadding(a.dp(20),0,a.dp(20),0);box.addView(name);box.addView(copy);new AlertDialog.Builder(a).setTitle("创建独立环境").setView(box).setPositiveButton("创建并打开",(d,w)->{String title=name.getText().toString().trim();if(title.isEmpty()||title.length()>24){a.status("环境名称需要 1–24 字");return;}boolean clone=copy.isChecked();a.loading.task("正在准备独立环境…");java.util.concurrent.ExecutorService worker=java.util.concurrent.Executors.newSingleThreadExecutor();worker.execute(()->{String error="";try{Profiles.prepare(a,id,clone);Profiles.rename(a,id,title);ProfileCatalog.get(a).created(id);}catch(Exception e){error="环境准备失败，已有环境未改动";}String failure=error;a.handler.post(()->{a.loading.dismissTask();if(failure.isEmpty())open(id,false);else a.status(failure);});worker.shutdown();});}).setNegativeButton("取消",null).show();}
  void open(int id,boolean edit){if(id==Profiles.slot(a)){if(edit)EnvironmentEditorUi.show(a);else select(0);return;}if(Build.VERSION.SDK_INT<28){a.status("独立环境需要 Android 9 或更新版本");return;}a.startActivity(new Intent(a,Profiles.activity(id)).putExtra("openEnvironmentEditor",edit).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_REORDER_TO_FRONT));}
  void settings(){LinearLayout box=layout("设置与保护");action(box,"编辑当前环境：基础 / 高级指纹 / 偏好",()->EnvironmentEditorUi.show(a));action(box,"网络管理",()->network());action(box,"隐私保护等级",()->ProfileUi.privacy(a));action(box,"环境自检与变更",()->EnvironmentAuditUi.show(a));action(box,"后台通知与电池设置",()->FeatureDialogs.backgroundSettings(a));action(box,"临时缓存与保留策略",()->cache());action(box,"关于、使用帮助与开源说明",()->about());}
  void network(){LinearLayout box=layout("网络管理");note(box,NetworkMetricsUi.detail(a.session,NativeNetwork.get(a),System.currentTimeMillis(),SystemClock.elapsedRealtime()));action(box,"网络方式：手机 VPN / 应用代理 / 内置网络",()->new AlertDialog.Builder(a).setTitle("选择网络方式").setItems(new String[]{"使用手机 VPN（断开保护默认开启）","配置应用专用代理地址","内置网络：订阅入口＋固定出口"},(d,n)->{if(ProfileUi.working(a.session)){a.status("当前任务结束后再切换网络");return;}if(n==0){a.prefs.edit().putBoolean("networkConfigured",true).putString("networkMode","external").putString("proxy","").putBoolean("requireExternalVpn",true).commit();a.session.reconnect();}else if(n==1)a.externalNetworkSettings();else FeatureDialogs.networkAdvanced(a);}).show());action(box,"节点管理：测速 / 切换入口",()->FeatureDialogs.nodes(a));action(box,"订阅管理与固定出口设置",()->FeatureDialogs.networkAdvanced(a));action(box,"查看 / 核实出口信息",()->ExitIpUi.show(a));action(box,"测试当前线路延迟",()->NativeNetwork.get(a).measureLatency((ok,msg)->a.status(msg)));action(box,"网络事件记录",()->text("网络事件",NetworkJournal.text(a)));action(box,"刷新网络信息",()->network());}
  void cache(){LinearLayout box=layout("临时缓存策略");JSONObject data=AppPrefs.temporaryCache(a,System.currentTimeMillis(),false);note(box,"自动策略："+(AppPrefs.enabled(a,"cleanTemporaryCache")?"已开启":"默认关闭")+"\n符合条件的无引用旧中间文件："+data.optInt("count")+" 个，"+NetworkMetricsUi.amount(data.optLong("bytes"))+"\n保留的下载任务中间文件："+data.optInt("protected")+" 个\n\n只检查本环境缓存目录中超过 30 天的无引用 .part 文件。不删除聊天、草稿、Cookie、用户已保存文件或其他未知缓存目录。");action(box,"设置自动策略",()->EnvironmentEditorUi.show(a));action(box,"清理上述无引用旧文件",()->{AppPrefs.temporaryCache(a,System.currentTimeMillis(),true);cache();});}
  void text(String title,String value){TextView body=a.label(value,14,Ui.INK);body.setPadding(a.dp(20),a.dp(10),a.dp(20),a.dp(15));ScrollView sc=new ScrollView(a);sc.addView(body);new AlertDialog.Builder(a).setTitle(title).setView(sc).setPositiveButton("关闭",null).show();}
  void about(){LinearLayout box=layout("关于元婴期院士");note(box,"Android ChatGPT 网页客户端\nv1.4.1 窗口首页版\n\n这版先完成参考界面的功能结构。完整视觉、品牌背景与动效待设计定稿。");action(box,"功能介绍",()->text("功能介绍","保留网页 / 简洁聊天、模型强度选择、历史管理、草稿恢复、附件、下载、后台通知、网络统计、固定出口、独立环境和环境自检。新增窗口首页、默认下载目录、最多八个环境、环境编辑草稿和真实偏好控制。"));action(box,"使用帮助",()->text("使用帮助","覆盖安装保留登录。聊天页的更多选项继续提供全部旧功能。独立环境需要分别登录。网络与保护等级只在当前环境生效。联网自检由你明确开启，结果不是防封号认证。"));action(box,"常见问题",()->text("常见问题","未提供模拟 Windows、任意切换内核和随机设备身份。系统及 WebView 显示真实值。后台等待受安卓省电影响。仅 Wi-Fi 下载无法确认当前 Wi-Fi 时会暂停；已有下载进度继续保留。"));action(box,"开源与隐私说明",()->text("开源与隐私","应用源码及第三方许可随源码包提供，包含 Mihomo、AndroidX 与 KaTeX 等组件的相关说明。没有加入广告、遥测或客服账号。网络配置与自检基线按环境加密保存；网络日志不记录订阅、密码、Cookie 或 IP。不能保证 VPN 不被识别或账号不被封。"));action(box,"复制问题诊断（不含账号配置）",()->{((ClipboardManager)a.getSystemService(Context.CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("问题诊断",a.session.trace.copyText()));a.status("已复制本机耗时诊断");});}
}
