package local.pocketchat;
import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.net.Uri;
import android.provider.OpenableColumns;
import android.view.*;
import android.webkit.*;
import android.widget.*;
import java.util.*;
import java.util.concurrent.*;
import org.json.*;

final class Attachments {
  final MainActivity a;final LinearLayout rows;final HorizontalScrollView view;final ExecutorService worker=Executors.newSingleThreadExecutor();ValueCallback<Uri[]> callback;
  String pickerUrl="",kind="file",lastRendered="";long pickerEpoch,requestSerial=0,selectedAt=0;boolean requesting=false,reading=false,checking=false,destroyed=false,navigationAccepted=false;int stableReady=0;Uri retryUri;String retryName="";String boundOwner="";
  Attachments(MainActivity activity){a=activity;rows=new LinearLayout(a);rows.setOrientation(0);rows.setPadding(a.dp(12),a.dp(5),a.dp(12),a.dp(2));view=new HorizontalScrollView(a);view.setHorizontalScrollBarEnabled(false);view.addView(rows);view.setVisibility(View.GONE);restore();}
  void persist(){if(!boundOwner.isEmpty())a.prefs.edit().putString("files:"+boundOwner,a.session.attachments.toString()).apply();}
  void restore(){String owner=a.session.conversation;if(owner.isEmpty())owner=MainActivity.ORIGIN;if(owner.equals(boundOwner))return;boundOwner=owner;a.session.attachmentOwner=owner;try{a.session.attachments=new JSONArray(a.prefs.getString("files:"+owner,"[]"));for(int i=0;i<a.session.attachments.length();i++)a.session.attachments.getJSONObject(i).put("state","unknown");}catch(Exception e){a.session.attachments=new JSONArray();}lastRendered="";}
  void preview(String message,String name){JSONObject file=null;if(message.isEmpty()){for(int i=0;i<a.session.attachments.length();i++){JSONObject f=a.session.attachments.optJSONObject(i);if(name.equals(f.optString("name")))file=f;}}else file=J.parse(a.prefs.getString("preview:"+a.conversation+"|"+message+"|"+name,"{}"));if(file!=null&&!file.optString("uri").isEmpty()){a.startActivity(new Intent(a,Profiles.preview(a)).putExtra("uri",file.optString("uri")).putExtra("name",name).putExtra("mime",file.optString("mime")));}else{a.status("此历史附件尚无本地副本，请在原网页点按附件查看");a.showPage(true);}}
  void actions(JSONObject f){String name=f.optString("name");new AlertDialog.Builder(a).setTitle(name+"\n"+sizeLabel(f.optLong("size",-1))+" · "+stateLabel(f)).setItems(new String[]{"预览","重新上传","查看原网页"},(d,n)->{if(n==0)preview("",name);else if(n==1)retry(f);else a.showPage(true);}).show();}
  void retry(JSONObject f){if(a.session.offline||a.session.navigating||a.session.pending!=null||a.session.submitting){a.status("请联网并等待当前操作完成");return;}String name=f.optString("name"),uri=f.optString("uri");if(uri.isEmpty()){a.status("此附件需要重新选择");return;}long epoch=a.session.navigationEpoch;a.session.asyncDriver("attachment-state",J.obj("names",new JSONArray().put(name),"url",boundOwner),2500,r->{if(epoch!=a.session.navigationEpoch)return;JSONObject state=r.optJSONArray("files")==null?null:r.optJSONArray("files").optJSONObject(0);if(state==null||state.optInt("matches",-1)>1){a.status("无法确认原附件，请查看原网页");return;}Runnable upload=()->{retryName=name;retryUri=Uri.parse(uri);open(f.optString("mime").startsWith("image/")?"image":"file");};if(state.optInt("matches",-1)==0)upload.run();else if(state.optInt("matches",-1)==1)a.session.asyncDriver("attachment-remove",J.obj("name",name,"url",boundOwner),3500,removed->{if(epoch!=a.session.navigationEpoch)return;if(removed.optBoolean("ok"))upload.run();else a.status("原附件移除未确认，未重复上传");});});}
  void drop(String name){JSONArray kept=new JSONArray();for(int i=0;i<a.session.attachments.length();i++){JSONObject f=a.session.attachments.optJSONObject(i);if(!name.equals(f.optString("name")))kept.put(f);}a.session.attachments=kept;persist();render();}
  boolean hasFiles(){return a.session.attachments.length()>0;}
  boolean blocked(){if(requesting||callback!=null||reading)return true;for(int i=0;i<a.session.attachments.length();i++)if(!"ready".equals(a.session.attachments.optJSONObject(i).optString("state")))return true;return false;}
  void open(String requestedKind){if(a.session.offline||a.session.navigating||a.session.navigationFailed||a.session.pending!=null||a.session.operation||a.session.submitting||(retryUri==null&&blocked())){a.status("请先等待当前操作完成");return;}kind=requestedKind;requesting=true;render();pickerUrl=a.remote.getUrl();pickerEpoch=a.session.navigationEpoch;long serial=++requestSerial;a.loading.task("正在打开文件选择器…");a.session.asyncDriver("attachment-open",J.obj("kind",kind,"url",pickerUrl,"reset",!retryName.isEmpty()),2500,result->{if(result.has("touch")){a.loading.dismissTask();a.remote.requestFocus();JSONObject point=result.optJSONObject("touch");float x=(float)(point.optDouble("x")*a.remote.getWidth()/point.optDouble("width",1)),y=(float)(point.optDouble("y")*a.remote.getHeight()/point.optDouble("height",1));a.handler.postDelayed(()->tap(x,y),100);}if(!result.optBoolean("ok")){requesting=false;a.loading.dismissTask();a.status(result.optString("reason"));}});a.handler.postDelayed(()->{if(requesting&&requestSerial==serial&&callback==null){requesting=false;a.loading.dismissTask();a.status("文件选择器未打开，请在原网页重试");}},3500);}
  void tap(float x,float y){if(!requesting||!samePage())return;long time=android.os.SystemClock.uptimeMillis();android.view.MotionEvent down=android.view.MotionEvent.obtain(time,time,android.view.MotionEvent.ACTION_DOWN,x,y,0);down.setSource(android.view.InputDevice.SOURCE_TOUCHSCREEN);a.remote.dispatchTouchEvent(down);down.recycle();a.handler.postDelayed(()->{android.view.MotionEvent up=android.view.MotionEvent.obtain(time,android.os.SystemClock.uptimeMillis(),android.view.MotionEvent.ACTION_UP,x,y,0);up.setSource(android.view.InputDevice.SOURCE_TOUCHSCREEN);a.remote.dispatchTouchEvent(up);up.recycle();},60);}
  WebChromeClient chrome(){return new WebChromeClient(){@Override public void onPermissionRequest(PermissionRequest request){request.deny();}@Override public void onGeolocationPermissionsShowPrompt(String origin,GeolocationPermissions.Callback callback){callback.invoke(origin,false,false);}@Override public boolean onShowFileChooser(WebView web,ValueCallback<Uri[]> result,FileChooserParams params){if(!MainActivity.chatUrl(web.getUrl())||a.session.pending!=null||a.session.navigating){result.onReceiveValue(null);return true;}cancelChooser();callback=result;requesting=false;pickerUrl=web.getUrl();pickerEpoch=a.session.navigationEpoch;a.loading.dismissTask();if(retryUri!=null){Uri selected=retryUri;retryUri=null;Attachments.this.result(Activity.RESULT_OK,new Intent().setData(selected));return true;}Intent intent=new Intent(Intent.ACTION_OPEN_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType("image".equals(kind)?"image/*":"*/*").addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);intent.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,params.getMode()==FileChooserParams.MODE_OPEN_MULTIPLE);try{a.startActivityForResult(intent,74);}catch(ActivityNotFoundException e){cancelChooser();a.status("设备没有可用的文件选择器");}kind="file";return true;}};}
  boolean samePage(){return pickerEpoch==a.session.navigationEpoch&&MainActivity.chatUrl(a.remote.getUrl())&&Uri.parse(pickerUrl).getPath().equals(Uri.parse(a.remote.getUrl()).getPath());}
  void result(int code,Intent data){ValueCallback<Uri[]> recipient=callback;if(recipient==null)return;if(code!=Activity.RESULT_OK||data==null){cancelChooser();return;}if(!samePage()){cancelChooser();a.status("对话已改变，未添加附件");return;}LinkedHashSet<Uri> selected=new LinkedHashSet<>();if(data.getClipData()!=null)for(int i=0;i<data.getClipData().getItemCount();i++)selected.add(data.getClipData().getItemAt(i).getUri());else if(data.getData()!=null)selected.add(data.getData());if(selected.isEmpty()){cancelChooser();return;}reading=true;a.loading.task("正在读取所选附件…");worker.execute(()->{JSONArray files=new JSONArray();String problem="";try{Set<String> names=new HashSet<>();for(int i=0;i<a.session.attachments.length();i++)if(!retryName.equals(a.session.attachments.optJSONObject(i).optString("name")))names.add(a.session.attachments.optJSONObject(i).optString("name"));for(Uri uri:selected){if(uri==null||!"content".equals(uri.getScheme())||uri.getAuthority()==null||uri.getAuthority().startsWith(a.getPackageName()+"."))throw new Exception("请选择系统文件选择器中的文件");String name="附件";long size=-1;try(Cursor c=a.getContentResolver().query(uri,new String[]{OpenableColumns.DISPLAY_NAME,OpenableColumns.SIZE},null,null,null)){if(c!=null&&c.moveToFirst()){int ni=c.getColumnIndex(OpenableColumns.DISPLAY_NAME),si=c.getColumnIndex(OpenableColumns.SIZE);if(ni>=0)name=c.getString(ni);if(si>=0&&!c.isNull(si))size=c.getLong(si);}}if(name==null||name.trim().isEmpty())throw new Exception("无法读取附件名称");if(!names.add(name))throw new Exception("已有同名附件，请先移除后再添加");try(android.content.res.AssetFileDescriptor fd=a.getContentResolver().openAssetFileDescriptor(uri,"r")){if(fd==null)throw new Exception("所选文件不可读取");}try{a.getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(SecurityException ignored){}files.put(J.obj("name",name,"size",size,"state","uploading","uri",uri.toString(),"mime",a.getContentResolver().getType(uri)));}}catch(Exception e){problem=e.getMessage()==null?"读取附件失败，请重新选择":e.getMessage();}final String error=problem;a.handler.post(()->{reading=false;if(destroyed||callback!=recipient)return;a.loading.dismissTask();if(!error.isEmpty()||!samePage()){cancelChooser();a.status(error.isEmpty()?"对话已改变，未添加附件":error);return;}callback=null;if(!retryName.isEmpty()){drop(retryName);retryName="";}for(int i=0;i<files.length();i++)a.session.attachments.put(files.optJSONObject(i));a.session.attachmentOwner=pickerUrl;boundOwner=a.session.conversation.isEmpty()?MainActivity.ORIGIN:a.session.conversation;persist();selectedAt=System.currentTimeMillis();stableReady=0;render();a.session.updateBrowserActivity();recipient.onReceiveValue(selected.toArray(new Uri[0]));a.status("正在上传附件…完成后再发送");a.handler.postDelayed(()->refresh(),400);});});}
  void cancelChooser(){requesting=false;ValueCallback<Uri[]> old=callback;callback=null;if(old!=null)old.onReceiveValue(null);}
  void refresh(){restore();if(destroyed||a.session.offline||checking||!hasFiles()||a.session.navigating)return;boolean wasUploading=a.session.uploading();JSONArray names=new JSONArray();for(int i=0;i<a.session.attachments.length();i++)names.put(a.session.attachments.optJSONObject(i).optString("name"));checking=true;long epoch=a.session.navigationEpoch;String owner=boundOwner;a.session.asyncDriver("attachment-state",J.obj("names",names,"url",a.session.attachmentOwner),2500,data->{checking=false;if(destroyed||epoch!=a.session.navigationEpoch||!owner.equals(boundOwner))return;JSONArray states=data.optJSONArray("files");if(states!=null){boolean ready=true;for(int i=0;i<states.length();i++)if(!"ready".equals(states.optJSONObject(i).optString("state")))ready=false;stableReady=ready?stableReady+1:0;for(int i=0;i<a.session.attachments.length();i++){JSONObject f=a.session.attachments.optJSONObject(i);for(int j=0;j<states.length();j++){JSONObject state=states.optJSONObject(j);if(f.optString("name").equals(state.optString("name")))try{String value=state.optString("state","unknown");if("ready".equals(value)&&stableReady<2)value="uploading";if("unknown".equals(value)&&System.currentTimeMillis()-selectedAt<20000)value="uploading";f.put("state",value);f.put("progress",state.optInt("progress",-1));f.put("detail",state.optString("reason"));}catch(Exception ignored){}}}}persist();render();if(wasUploading!=a.session.uploading())a.session.updateBrowserActivity();});}
  static String sizeLabel(long bytes){if(bytes<0)return "大小未知";if(bytes<1024)return bytes+" B";return String.format(Locale.ROOT,bytes<1048576?"%.1f KB":"%.1f MB",bytes/(bytes<1048576?1024.0:1048576.0));}
  static String stateLabel(JSONObject f){String state=f.optString("state");int progress=f.optInt("progress",-1);return "ready".equals(state)?"网页已接收":"error".equals(state)?"上传失败，点按处理":"unknown".equals(state)?"网页接收待核对":progress>=0?"上传 "+progress+"%":"上传或处理中…";}
  void render(){restore();boolean show=hasFiles();view.setVisibility(show?View.VISIBLE:View.GONE);String serial=a.session.attachments.toString();if(!serial.equals(lastRendered)){lastRendered=serial;rows.removeAllViews();for(int i=0;i<a.session.attachments.length();i++){JSONObject f=a.session.attachments.optJSONObject(i);String name=f.optString("name"),state=f.optString("state");LinearLayout row=new LinearLayout(a);row.setGravity(Gravity.CENTER_VERTICAL);TextView text=a.label(name+"\n"+sizeLabel(f.optLong("size",-1))+" · "+stateLabel(f),13,Ui.MUTED);text.setMaxLines(2);text.setEllipsize(android.text.TextUtils.TruncateAt.MIDDLE);text.setPadding(a.dp(6),a.dp(5),a.dp(6),a.dp(5));row.addView(text,new LinearLayout.LayoutParams(0,-2,1));text.setOnClickListener(v->actions(f));Ui.IconButton remove=new Ui.IconButton(a,"close","移除附件 "+name,false);row.addView(remove,new LinearLayout.LayoutParams(a.dp(36),a.dp(40)));remove.setOnClickListener(v->remove(name));android.graphics.drawable.GradientDrawable bg=Ui.shape(a,android.graphics.Color.WHITE,12);bg.setStroke(1,0xffdddddd);row.setBackground(bg);LinearLayout.LayoutParams chip=new LinearLayout.LayoutParams(a.dp(210),a.dp(72));chip.rightMargin=a.dp(8);rows.addView(row,chip);}}
    if(a.send!=null)a.send.setEnabled(a.session.networkReady&&!a.session.offline&&a.session.pending==null&&!a.session.submitting&&!a.session.operation&&!a.session.navigating&&!a.session.navigationFailed&&!blocked()&&(hasFiles()||a.input.getText().toString().trim().length()>0));}
  void remove(String name){if(a.session.pending!=null||a.session.submitting)return;a.loading.task("正在移除附件…");a.session.asyncDriver("attachment-remove",J.obj("name",name,"url",a.session.attachmentOwner),3500,r->{a.loading.dismissTask();if(r.optBoolean("ok")){JSONArray kept=new JSONArray();for(int i=0;i<a.session.attachments.length();i++){JSONObject f=a.session.attachments.optJSONObject(i);if(!name.equals(f.optString("name")))kept.put(f);}a.session.attachments=kept;persist();render();}else a.status(r.optString("reason","移除未确认，请查看原网页"));});}
  boolean beforeSend(){if(blocked()){a.status("请等待附件上传完成，或移除未完成的附件");return false;}return true;}
  void sent(){JSONObject job=a.session.pending;String key=job==null?"":job.optString("userKey");if(!key.isEmpty()){SharedPreferences.Editor prefs=a.prefs.edit();for(int i=0;i<a.session.attachments.length();i++){JSONObject f=a.session.attachments.optJSONObject(i);prefs.putString("preview:"+a.session.conversation+"|"+key+"|"+f.optString("name"),f.toString());}prefs.apply();}a.session.attachments=new JSONArray();persist();lastRendered="";render();}
  boolean allowNavigation(Runnable action){if(navigationAccepted){navigationAccepted=false;return true;}if(!hasFiles()&&callback==null&&!requesting)return true;new AlertDialog.Builder(a).setTitle("离开当前对话？").setMessage("附件记录将保存在当前对话。返回后会核对上传状态，必要时可点按重新上传。").setPositiveButton("继续",(d,w)->{cancelChooser();persist();navigationAccepted=true;action.run();}).setNegativeButton("取消",null).show();return false;}
  void destroy(){destroyed=true;cancelChooser();worker.shutdown();}
}

