package local.pocketchat;
import android.content.*;import android.database.*;import android.database.sqlite.*;import org.json.*;import java.util.*;

final class DeliveryStore extends SQLiteOpenHelper {
 long revision=0;
 DeliveryStore(Context c){super(c.getApplicationContext(),"deliveries.db",null,1);}
 public void onCreate(SQLiteDatabase db){db.execSQL("CREATE TABLE deliveries(id TEXT PRIMARY KEY,url TEXT NOT NULL,body TEXT NOT NULL,state TEXT NOT NULL,detail TEXT NOT NULL DEFAULT '',user_key TEXT NOT NULL DEFAULT '',files TEXT NOT NULL DEFAULT '[]',kind TEXT NOT NULL DEFAULT 'send',attempted INTEGER NOT NULL DEFAULT 0,created INTEGER NOT NULL,updated INTEGER NOT NULL)");db.execSQL("CREATE INDEX by_conversation ON deliveries(url,created)");}
 public void onUpgrade(SQLiteDatabase db,int a,int b){}
 JSONObject row(Cursor c){JSONObject o=new JSONObject();for(int i=0;i<c.getColumnCount();i++)try{String key=c.getColumnName(i);if(key.equals("created")||key.equals("updated")||key.equals("attempted"))o.put(key,c.getLong(i));else o.put(key,c.getString(i));}catch(Exception ignored){}return o;}
 synchronized JSONObject get(String id){try(Cursor c=getReadableDatabase().query("deliveries",null,"id=?",new String[]{id},null,null,null)){return c.moveToFirst()?row(c):null;}}
 synchronized String begin(String url,String body,JSONArray files,String kind,String requestedId){String encoded=files==null?"[]":files.toString();if(requestedId==null&&kind.equals("send")){try(Cursor c=getReadableDatabase().query("deliveries",null,"url=? AND body=? AND files=? AND kind='send' AND attempted=0 AND state IN ('queued','failed','draft')",new String[]{url,body,encoded},null,null,"created DESC","1")){if(c.moveToFirst()){String id=c.getString(c.getColumnIndexOrThrow("id"));update(id,"queued","等待发送",false,"",url);return id;}}}String id=requestedId==null?UUID.randomUUID().toString():requestedId;long now=System.currentTimeMillis();ContentValues v=new ContentValues();v.put("id",id);v.put("url",url);v.put("body",body);v.put("files",encoded);v.put("kind",kind);v.put("state","queued");v.put("created",now);v.put("updated",now);getWritableDatabase().insertOrThrow("deliveries",null,v);revision++;return id;}
 synchronized void update(String id,String state,String detail,boolean attempted,String key,String url){if(id==null||id.isEmpty())return;detail=detail==null?"":detail;JSONObject old=get(id);if(old==null)return;if(state.equals(old.optString("state"))&&detail.equals(old.optString("detail"))&&attempted==(old.optInt("attempted")!=0)&&(key.isEmpty()||key.equals(old.optString("user_key")))&&(url.isEmpty()||url.equals(old.optString("url"))))return;ContentValues v=new ContentValues();v.put("state",state);v.put("detail",detail);v.put("attempted",attempted?1:0);v.put("updated",System.currentTimeMillis());if(!key.isEmpty())v.put("user_key",key);if(!url.isEmpty())v.put("url",url);getWritableDatabase().update("deliveries",v,"id=?",new String[]{id});revision++;}
 synchronized JSONArray list(String url){JSONArray result=new JSONArray();try(Cursor c=getReadableDatabase().query("deliveries",null,"url=?",new String[]{url},null,null,"rowid ASC")){while(c.moveToNext())result.put(row(c));}return result;}
 static String label(String state){switch(state){case "queued":return "待发送";case "sending":return "正在发送";case "confirmed":return "网页已确认";case "awaiting":return "等待回复";case "completed":return "回复完成";case "stopped":return "已停止等待";case "failed":return "失败待处理";case "uncertain":return "发送结果待确认";case "draft":return "已放回输入框";default:return "网页记录";}}
 JSONObject decoration(JSONObject record){return J.obj("id",record.optString("id"),"state",record.optString("state"),"label",label(record.optString("state")),"detail",record.optString("detail"),"attempted",record.optInt("attempted")!=0);}
 synchronized JSONArray decorate(String url,JSONArray messages,String active){JSONArray records=list(url),out=new JSONArray();Map<String,JSONObject> byKey=new HashMap<>();for(int i=0;i<records.length();i++){JSONObject r=records.optJSONObject(i);if(!r.optString("user_key").isEmpty())byKey.put(r.optString("user_key"),r);}for(int i=0;i<messages.length();i++){JSONObject e=J.parse(messages.optJSONObject(i).toString());if("user".equals(e.optString("role")))try{JSONObject r=byKey.get(e.optString("id"));e.put("delivery",r==null?J.obj("state","web_record","label","网页记录"):decoration(r));}catch(Exception ignored){}out.put(e);}for(int i=0;i<records.length();i++){JSONObject r=records.optJSONObject(i);String state=r.optString("state");if((android.net.Uri.parse(url).getPath().contains("/c/")||r.optString("id").equals(active))&&r.optString("user_key").isEmpty()&&Arrays.asList("queued","sending","failed","uncertain","awaiting").contains(state)){JSONArray files;try{files=new JSONArray(r.optString("files","[]"));}catch(Exception e){files=new JSONArray();}out.put(J.obj("id","local:"+r.optString("id"),"role","user","text",r.optString("body"),"attachments",files,"local",true,"delivery",decoration(r)));}}return out;}
 synchronized void recover(JSONObject pending){String active=pending==null?"":pending.optString("id");if(pending!=null&&!active.isEmpty()&&get(active)==null){begin(pending.optString("confirmedUrl",pending.optString("expectedUrl")),pending.optString("prompt"),pending.optJSONArray("attachmentNames"),pending.optString("kind","send"),active);update(active,pending.optBoolean("confirmed")?"awaiting":"uncertain","恢复上次发送记录，未自动重发",true,pending.optString("userKey"),"");}try(Cursor c=getReadableDatabase().query("deliveries",null,"state IN ('queued','sending','confirmed','awaiting')",null,null,null,null)){while(c.moveToNext()){JSONObject r=row(c);if(!r.optString("id").equals(active))update(r.optString("id"),r.optInt("attempted")!=0?"uncertain":"queued",r.optInt("attempted")!=0?"应用重启后需要核对网页":"尚未点击发送，可放回输入框",r.optInt("attempted")!=0,"","");}}}
}
