package local.pocketchat;
import android.app.*;import android.os.SystemClock;import android.widget.*;import org.json.*;

/** Network design panels consume existing evidence; missing diagnostics are explicit extension slots. */
final class DesignNetworkUi {
  static void render(MainActivity a,LinearLayout box,int tab){box.addView(DesignUi.tabs(a,new String[]{"方案","订阅","节点","出口","诊断"},tab,n->{a.hub.networkTab=n;a.hub.network();}));NativeNetwork network=NativeNetwork.get(a);DesignUi.note(box,"当前窗口："+Profiles.display(a,Profiles.slot(a)));if(tab==0)scheme(a,box,network);if(tab==1)subscription(a,box);if(tab==2)nodes(a,box,network);if(tab==3)exit(a,box,network);if(tab==4)diagnostics(a,box,network);}
  static void scheme(MainActivity a,LinearLayout box,NativeNetwork n){LinearLayout card=DesignUi.card(a),head=DesignUi.row(a);head.addView(DesignUi.icon(a,"window",DesignUi.CYAN,38));TextView title=DesignUi.text(a,Profiles.display(a,Profiles.slot(a))+" 网络方案",16,DesignUi.TEXT);title.setPadding(a.dp(9),0,0,0);head.addView(title,new LinearLayout.LayoutParams(0,-2,1));head.addView(DesignUi.badge(a,a.session.networkReady?"● 使用中":"待连接",a.session.networkReady?DesignUi.GREEN:DesignUi.MUTED));card.addView(head);String mode=a.session.internalNetwork()?"内置订阅入口＋固定出口":a.prefs.getString("proxy","").isEmpty()?"使用手机现有网络":"应用专用代理";DesignUi.note(card,mode);if(a.session.internalNetwork())DesignUi.field(card,"当前入口",n.currentEntry.isEmpty()?"尚未选择":NativeNetwork.display(n.currentEntry));DesignUi.field(card,"连接状态",NetworkMetricsUi.line(a.session,n,System.currentTimeMillis(),SystemClock.elapsedRealtime()));DesignUi.action(card,"设置网络方式",true,()->modes(a));DesignUi.addCard(box,card);DesignUi.addCard(box,DesignUi.setting(a,"globe","多个网络方案","为本窗口预留方案管理入口","开发中",()->FutureFeatures.open(a,FutureFeatures.Feature.NETWORK_PLANS,Profiles.slot(a))));DesignUi.action(box,"连接状态与重连",false,()->NetworkStatusUi.show(a));DesignUi.action(box,"完整线路统计",false,()->NetworkMetricsUi.show(a));}
  static void modes(MainActivity a){new AlertDialog.Builder(a).setTitle("网络方式").setItems(new String[]{"使用手机 VPN","应用专用 HTTP / SOCKS 代理","内置网络：订阅＋固定 SOCKS5 出口"},(d,n)->{if(ProfileUi.working(a.session)){a.status("当前任务结束后再切换网络");return;}if(n==0){a.prefs.edit().putBoolean("networkConfigured",true).putString("networkMode","external").putString("proxy","").putBoolean("requireExternalVpn",true).commit();a.session.reconnect();}if(n==1)a.externalNetworkSettings();if(n==2)FeatureDialogs.networkAdvanced(a);}).setNegativeButton("取消",null).show();}
  static void subscription(MainActivity a,LinearLayout box){JSONObject saved=new SecretStore(a).settings();LinearLayout card=DesignUi.card(a);LinearLayout head=DesignUi.row(a);head.addView(DesignUi.icon(a,"globe",DesignUi.CYAN,36));TextView name=DesignUi.text(a,"当前窗口订阅",16,DesignUi.TEXT);name.setPadding(a.dp(10),0,0,0);head.addView(name,new LinearLayout.LayoutParams(0,-2,1));head.addView(DesignUi.badge(a,saved.optString("subscriptionUrl").isEmpty()?"未配置":"已配置",saved.optString("subscriptionUrl").isEmpty()?DesignUi.MUTED:DesignUi.GREEN));card.addView(head);DesignUi.note(card,"订阅地址与固定出口凭据按窗口加密保存。当前支持一份订阅配置。");DesignUi.action(card,"编辑订阅与固定出口",true,()->FeatureDialogs.networkAdvanced(a));DesignUi.action(card,"更新当前订阅",false,()->{if(ProfileUi.working(a.session)){a.status("请等待当前任务结束");return;}a.loading.task("正在更新订阅…");NativeNetwork.get(a).refresh((ok,msg)->{a.loading.dismissTask();a.status(msg);if(ok)a.session.applyProxy(NativeNetwork.get(a).proxy());});});DesignUi.addCard(box,card);DesignUi.addCard(box,DesignUi.setting(a,"plus","添加更多订阅","多个订阅列表接口","开发中",()->FutureFeatures.open(a,FutureFeatures.Feature.MULTI_SUBSCRIPTIONS,Profiles.slot(a))));}
  static void nodes(MainActivity a,LinearLayout box,NativeNetwork n){DesignUi.action(box,"重新测速 / 选择入口",true,()->FeatureDialogs.nodes(a));if(n.results.length()==0)DesignUi.note(box,"还没有线路测量结果，配置内置网络后可进行测速。");for(int i=0;i<n.results.length();i++){JSONObject r=n.results.optJSONObject(i);String internal=r.optString("internalName");String delay=r.optInt("delay")>0?r.optInt("delay")+" ms":"本次不可用";String details=delay+(r.optInt("samples")>0?" · 成功 "+Math.round(r.optDouble("successRate")*100)+"% · 波动 "+r.optLong("jitter")+" ms":"");DesignUi.addCard(box,DesignUi.setting(a,"globe",r.optString("name"),details,internal.equals(n.currentEntry)?"使用中":"",()->{if(ProfileUi.working(a.session)){a.status("当前任务结束后再切换入口");return;}a.loading.task("正在切换并核实线路…");n.select(internal,(ok,msg)->{a.loading.dismissTask();a.status(msg);a.hub.network();});}));}}
  static void exit(MainActivity a,LinearLayout box,NativeNetwork n){LinearLayout card=DesignUi.card(a);DesignUi.field(card,"出口信息",ExitIpUi.value(a.session,n));DesignUi.note(card,"只展示实际核实的地址。城市和地区尚无独立核验数据。");DesignUi.addCard(box,card);DesignUi.action(box,"查看 / 核实固定出口",true,()->ExitIpUi.show(a));DesignUi.action(box,"授权检查实际网络出口",false,()->EnvironmentAuditUi.show(a));DesignUi.action(box,"查看网络事件",false,()->a.hub.text("本机网络事件",NetworkJournal.text(a)));}
  static void diagnostics(MainActivity a,LinearLayout box,NativeNetwork n){LinearLayout chain=DesignUi.card(a);DesignUi.field(chain,"当前连接链路",a.session.internalNetwork()?"本机 → 入口节点 → 固定出口 → ChatGPT":a.prefs.getString("proxy","").isEmpty()?"本机网络 / 手机 VPN → ChatGPT":"本机 → 应用代理 → ChatGPT");DesignUi.addCard(box,chain);long now=System.currentTimeMillis();JSONObject q=n.quality.stats(n.currentEntry,now);status(a,box,"当前连接",a.session.offline?"已断开":a.session.networkReady?"已连接":"待确认",a.session.networkReady?DesignUi.GREEN:DesignUi.MUTED);status(a,box,"线路延迟",a.session.internalNetwork()?NetworkMetricsUi.latency(q,now):"当前模式未统计",DesignUi.CYAN);status(a,box,"探测稳定性",a.session.internalNetwork()?NetworkMetricsUi.stability(q,now):"当前模式未统计",DesignUi.MUTED);status(a,box,"出口核实",ExitIpUi.value(a.session,n),DesignUi.MUTED);status(a,box,"DNS / TCP / TLS 分项","开发中 · 尚未分项测量",DesignUi.MUTED);status(a,box,"WebRTC / DNS 完整泄漏测试","未覆盖 · 可查看现有自检证据",DesignUi.MUTED);DesignUi.action(box,"测一下真实线路延迟",true,()->n.measureLatency((ok,msg)->{a.status(msg);a.hub.network();}));DesignUi.action(box,"环境自检与检查详情",false,()->EnvironmentAuditUi.show(a));DesignUi.action(box,"连接阶段耗时",false,()->NetworkStatusUi.show(a));DesignUi.addCard(box,DesignUi.setting(a,"globe","完整分项诊断","测量接口预留","开发中",()->FutureFeatures.open(a,FutureFeatures.Feature.FULL_DIAGNOSTIC,Profiles.slot(a))));}
  static void status(MainActivity a,LinearLayout box,String name,String value,int color){LinearLayout row=DesignUi.row(a);row.setPadding(a.dp(10),a.dp(11),a.dp(10),a.dp(11));row.addView(DesignUi.text(a,name,12,DesignUi.TEXT),new LinearLayout.LayoutParams(0,-2,1));TextView info=DesignUi.text(a,value,11,color);info.setMaxWidth(a.dp(200));row.addView(info);DesignUi.addCard(box,row);}
}
