package local.pocketchat;
import android.app.*;import android.content.*;import android.os.*;import android.widget.*;import org.json.*;import java.util.*;

/** Unified file/task presentation uses real progress and routes controls to the owner process. */
final class DesignDownloads {
  static JSONArray rows(Context c){DownloadLibrary library=DownloadLibrary.get(c);JSONArray out=new JSONArray(),tasks=library.tasks(),files=library.list();Set<String> seen=new HashSet<>();for(int i=0;i<files.length();i++){JSONObject r=files.optJSONObject(i);out.put(r);seen.add(r.optString("uri"));}for(int i=0;i<tasks.length();i++){JSONObject r=tasks.optJSONObject(i);if(r.optString("state").equals("saved")&&!r.optString("uri").isEmpty()&&seen.contains(r.optString("uri")))continue;out.put(r);}return out;}
  static boolean busy(String state){return Arrays.asList("preparing","downloading","saving","choosing").contains(state);}
  static void open(Activity a,JSONObject r,SavedFileActions actions){if("saved".equals(r.optString("state"))){actions.show(r);return;}int slot=r.optInt("slot");if(a instanceof MainActivity&&slot==Profiles.slot(a)){MainActivity main=(MainActivity)a;for(int i=0;i<main.downloads.tasks.rows.length();i++){JSONObject actual=main.downloads.tasks.rows.optJSONObject(i);if(actual.optString("id").equals(r.optString("id"))){main.downloads.taskActions(actual);return;}}}a.startActivity(new Intent(a,Profiles.activity(slot)).putExtra("openDownload",r.optString("id")).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_REORDER_TO_FRONT));}
  static void render(Activity a,LinearLayout box,int filter,java.util.function.IntConsumer choose,SavedFileActions actions){JSONArray rows=rows(a);box.addView(DesignUi.tabs(a,new String[]{"全部","进行中","已完成","失败"},filter,choose));LinearLayout link=DesignUi.row(a);TextView scope=DesignUi.text(a,"全部环境 · 文件与任务汇总",12,DesignUi.MUTED);link.addView(scope,new LinearLayout.LayoutParams(0,-2,1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=DesignUi.dp(a,10);box.addView(link,lp);int count=0;
    for(int i=0;i<rows.length();i++){JSONObject r=rows.optJSONObject(i);String state=r.optString("state");if(filter==1&&!busy(state)||filter==2&&!state.equals("saved")||filter==3&&!state.equals("failed"))continue;count++;LinearLayout card=DesignUi.card(a),top=DesignUi.row(a);boolean saved=state.equals("saved");int color=state.equals("failed")?DesignUi.RED:saved?DesignUi.CYAN:DesignUi.GREEN;top.addView(DesignUi.icon(a,saved?"file":"download",color,36));LinearLayout labels=DesignUi.column(a);labels.setPadding(DesignUi.dp(a,9),0,DesignUi.dp(a,5),0);TextView name=DesignUi.text(a,r.optString("name","文件"),14,DesignUi.TEXT);name.setMaxLines(2);labels.addView(name);labels.addView(DesignUi.text(a,Profiles.display(a,r.optInt("slot"))+" · "+DownloadTasks.label(state),11,DesignUi.MUTED));top.addView(labels,new LinearLayout.LayoutParams(0,-2,1));top.addView(DesignUi.text(a,"›",22,color));card.addView(top);
      if(!saved){long total=r.optLong("total",-1),received=r.optLong("received");ProgressBar progress=new ProgressBar(a,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);progress.setProgress(total>0?(int)Math.min(100,received*100/total):0);progress.setIndeterminate(total<=0&&busy(state));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,DesignUi.dp(a,6));pp.topMargin=DesignUi.dp(a,10);card.addView(progress,pp);DesignUi.note(card,DownloadTasks.progress(r));if(!r.optString("reason").isEmpty())card.addView(DesignUi.text(a,r.optString("reason"),11,DesignUi.MUTED));if(busy(state)&&System.currentTimeMillis()-r.optLong("updated")>15000)card.addView(DesignUi.text(a,"记录待刷新，点按核对任务",11,DesignUi.MUTED));}
      else{TextView location=DesignUi.text(a,r.optString("location","原先选择的保存位置"),10,DesignUi.MUTED);location.setMaxLines(2);location.setPadding(0,DesignUi.dp(a,7),0,0);card.addView(location);}card.setClickable(true);card.setFocusable(true);card.setOnClickListener(v->open(a,r,actions));DesignUi.addCard(box,card);
    }if(count==0)DesignUi.note(box,"没有符合条件的下载。文件保存完成后会自动出现在这里。");DesignUi.note(box,"默认位置："+(Build.VERSION.SDK_INT>=29?"Download/元婴期院士/窗口_编号/":"各窗口的应用内文件目录")+"\n点已保存文件可打开、分享、另存为或查看位置。");}
}
