package local.pocketchat;
import android.content.*;import android.net.Uri;import android.view.*;import android.widget.*;

/** App chrome around the real website; it never rewrites site content or submits input. */
final class DesignChrome {
  final MainActivity a;final TextView title,badge,host;final LinearLayout address;
  DesignChrome(MainActivity a,LinearLayout root){this.a=a;a.toolbar=DesignUi.column(a);a.toolbar.setPadding(a.dp(10),a.dp(4),a.dp(10),a.dp(6));LinearLayout top=DesignUi.row(a);a.navigation=new Ui.IconButton(a,"menu","打开会话列表",false);top.addView(a.navigation,new LinearLayout.LayoutParams(a.dp(34),a.dp(38)));a.navigation.setOnClickListener(v->a.showDrawer());title=DesignUi.text(a,Profiles.display(a,Profiles.slot(a)),15,DesignUi.TEXT);title.setSingleLine(true);title.setEllipsize(android.text.TextUtils.TruncateAt.END);top.addView(title,new LinearLayout.LayoutParams(0,-2,1));badge=DesignUi.badge(a,"默认",DesignUi.CYAN);top.addView(badge);Ui.IconButton fresh=new Ui.IconButton(a,"plus","新对话",true);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(a.dp(32),a.dp(32));p.leftMargin=a.dp(12);top.addView(fresh,p);fresh.setOnClickListener(v->a.newChat());Ui.IconButton more=new Ui.IconButton(a,"more","更多选项",false);top.addView(more,new LinearLayout.LayoutParams(a.dp(32),a.dp(36)));more.setOnClickListener(v->a.moreSheet());a.toolbar.addView(top);
    a.networkLine=DesignUi.text(a,"正在连接…",11,DesignUi.CYAN);a.networkLine.setSingleLine(true);a.networkLine.setEllipsize(android.text.TextUtils.TruncateAt.END);a.networkLine.setPadding(a.dp(10),a.dp(7),a.dp(10),a.dp(7));a.networkLine.setBackground(DesignUi.surface(a,0xff082533,8,0xff15536a));a.networkLine.setOnClickListener(v->NetworkMetricsUi.show(a));a.toolbar.addView(a.networkLine,new LinearLayout.LayoutParams(-1,-2));
    LinearLayout modes=DesignUi.row(a);modes.setPadding(0,a.dp(6),0,a.dp(6));a.nativeTab=a.modeTab("简洁模式","简洁聊天模式",()->a.showPage(false));a.webTab=a.modeTab("原网页模式","原网页模式",()->a.showPage(true));LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(0,a.dp(32),1);modes.addView(a.nativeTab,mp);LinearLayout.LayoutParams wp=new LinearLayout.LayoutParams(0,a.dp(32),1);wp.leftMargin=a.dp(6);modes.addView(a.webTab,wp);a.toolbar.addView(modes);
    address=DesignUi.row(a);address.setPadding(a.dp(7),0,a.dp(4),0);address.setBackground(DesignUi.surface(a,DesignUi.CARD,8,DesignUi.LINE));address.addView(DesignUi.icon(a,"lock",DesignUi.MUTED,26));host=DesignUi.text(a,"chatgpt.com",11,DesignUi.TEXT);host.setPadding(a.dp(6),0,0,0);address.addView(host,new LinearLayout.LayoutParams(0,-2,1));Ui.IconButton reload=new Ui.IconButton(a,"undo","重新加载当前网页",false);address.addView(reload,new LinearLayout.LayoutParams(a.dp(30),a.dp(30)));reload.setOnClickListener(v->a.session.retryCurrent());a.toolbar.addView(address,new LinearLayout.LayoutParams(-1,a.dp(32)));root.addView(a.toolbar,new LinearLayout.LayoutParams(-1,-2));}
  void update(){title.setText(Profiles.display(a,Profiles.slot(a)));boolean isDefault=Profiles.slot(a)==AppSettings.defaultSlot(a);badge.setText(isDefault?"默认":"窗口 "+(Profiles.slot(a)+1));address.setVisibility(a.pageMode?View.VISIBLE:View.GONE);try{String actual=Uri.parse(a.remote.getUrl()).getHost();host.setText(actual==null?"chatgpt.com":actual);}catch(Exception ignored){host.setText("chatgpt.com");}NativeNetwork n=NativeNetwork.get(a);String status=a.session.offline?"网络已断开":a.session.networkReady?"已连接":a.session.connecting?"连接中":"待连接";String route=a.session.internalNetwork()?"内置网络 · "+(n.currentEntry.isEmpty()?"入口待选择":NativeNetwork.display(n.currentEntry))+" → "+(n.lastVerified>0?"固定出口已核实":"出口待核实"):a.prefs.getString("proxy","").isEmpty()?"手机网络":"应用专用代理";a.networkLine.setText((a.session.audit.hasChanges()?"环境变化 · ":"")+route+" · "+status+" ›");a.networkLine.setTextColor(a.session.offline||n.recoveryBlocked?DesignUi.RED:DesignUi.CYAN);}
}
