package local.pocketchat;

import android.app.*;import android.content.*;import android.content.res.ColorStateList;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.view.*;import android.widget.*;import java.util.*;

/** Native design system. Website content and network/identity policies are not restyled here. */
final class DesignUi {
  static final int BG=0xfff4f6fa,CARD=0xffffffff,FIELD=0xfff8fafc,LINE=0xffdce3ed,TEXT=0xff1e293b,MUTED=0xff64748b,BLUE=0xff2563eb,CYAN=0xff2563eb,PURPLE=0xff3976ef,GREEN=0xff16845b,RED=0xffc93747;
  static final String[] NAV={"会话","环境","下载","网络","设置"},GLYPHS={"chat","window","download","globe","settings"};
  static int dp(Context c,int n){return Ui.dp(c,n);}
  static TextView text(Context c,String value,int size,int color){TextView v=new TextView(c);v.setText(value);v.setTextSize(size);v.setTextColor(color);v.setIncludeFontPadding(false);v.setLineSpacing(dp(c,3),1);return v;}
  static GradientDrawable surface(Context c,int color,int radius,int stroke){GradientDrawable d=Ui.shape(c,color,radius);d.setStroke(dp(c,1),stroke);return d;}
  static GradientDrawable gradient(Context c){GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{BLUE,PURPLE});d.setCornerRadius(dp(c,10));d.setStroke(dp(c,1),CYAN);return d;}
  static void chrome(Activity a){a.getWindow().setStatusBarColor(BG);a.getWindow().setNavigationBarColor(BG);a.getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR | (Build.VERSION.SDK_INT>=26?View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR:0));}
  static LinearLayout column(Context c){LinearLayout v=new LinearLayout(c);v.setOrientation(1);return v;}
  static LinearLayout row(Context c){LinearLayout v=new LinearLayout(c);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
  static LinearLayout card(Context c){LinearLayout box=column(c);box.setPadding(dp(c,12),dp(c,12),dp(c,12),dp(c,12));box.setBackground(surface(c,CARD,12,LINE));return box;}
  static void addCard(LinearLayout parent,View card){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(parent.getContext(),10);parent.addView(card,p);}
  static Button button(Context c,String title,boolean primary,Runnable action){Button b=new Button(c);b.setText(title);b.setAllCaps(false);b.setTextSize(14);b.setTextColor(primary?android.graphics.Color.WHITE:TEXT);b.setMinWidth(0);b.setMinimumWidth(0);b.setMinHeight(0);b.setMinimumHeight(0);b.setPadding(dp(c,12),dp(c,8),dp(c,12),dp(c,8));b.setStateListAnimator(null);b.setBackground(primary?gradient(c):surface(c,CARD,9,LINE));b.setOnClickListener(v->action.run());return b;}
  static void action(LinearLayout box,String label,boolean primary,Runnable run){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(box.getContext(),44));p.topMargin=dp(box.getContext(),10);box.addView(button(box.getContext(),label,primary,run),p);}
  static TextView badge(Context c,String label,int color){TextView t=text(c,label,11,color);t.setGravity(Gravity.CENTER);t.setPadding(dp(c,8),dp(c,4),dp(c,8),dp(c,4));t.setBackground(surface(c,(color&0x00ffffff)|0x22000000,6,(color&0x00ffffff)|0x66000000));return t;}
  static void note(LinearLayout box,String s){TextView t=text(box.getContext(),s,13,MUTED);t.setPadding(0,dp(box.getContext(),10),0,dp(box.getContext(),6));box.addView(t);}
  static ImageView icon(Context c,String glyph,int color,int size){ImageView v=new ImageView(c);v.setImageDrawable(new Ui.Icon(glyph,color));v.setPadding(dp(c,7),dp(c,7),dp(c,7),dp(c,7));v.setBackground(surface(c,(color&0xffffff)|0x20000000,10,(color&0xffffff)|0x44000000));v.setLayoutParams(new LinearLayout.LayoutParams(dp(c,size),dp(c,size)));return v;}
  static LinearLayout setting(Context c,String glyph,String title,String detail,String tag,Runnable action){LinearLayout r=row(c);r.setPadding(dp(c,10),dp(c,12),dp(c,10),dp(c,12));ImageView icon=icon(c,glyph,CYAN,34);r.addView(icon);LinearLayout labels=column(c);labels.setPadding(dp(c,10),0,dp(c,8),0);labels.addView(text(c,title,15,TEXT));if(!detail.isEmpty()){TextView sub=text(c,detail,11,MUTED);sub.setPadding(0,dp(c,4),0,0);labels.addView(sub);}r.addView(labels,new LinearLayout.LayoutParams(0,-2,1));r.addView(tag.isEmpty()?text(c,"›",22,MUTED):badge(c,tag,MUTED));r.setBackground(new RippleDrawable(ColorStateList.valueOf(0x3022d7ff),surface(c,CARD,10,LINE),null));if(action!=null){r.setClickable(true);r.setFocusable(true);r.setOnClickListener(v->action.run());}return r;}
  static void field(LinearLayout box,String title,String value){Context c=box.getContext();TextView name=text(c,title,12,MUTED);name.setPadding(0,dp(c,10),0,dp(c,5));box.addView(name);TextView val=text(c,value,14,TEXT);val.setPadding(dp(c,11),dp(c,11),dp(c,11),dp(c,11));val.setBackground(surface(c,FIELD,8,LINE));val.setTextIsSelectable(true);box.addView(val,new LinearLayout.LayoutParams(-1,-2));}
  static EditText input(LinearLayout box,String title,String value,String hint){Context c=box.getContext();TextView label=text(c,title,13,MUTED);label.setPadding(0,dp(c,12),0,dp(c,6));box.addView(label);EditText e=new EditText(c);e.setTextSize(14);e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setSingleLine(true);e.setText(value);e.setHint(hint);e.setPadding(dp(c,10),0,dp(c,10),0);e.setBackground(surface(c,FIELD,8,LINE));box.addView(e,new LinearLayout.LayoutParams(-1,dp(c,44)));return e;}
  static LinearLayout tabs(Context c,String[] labels,int selected,java.util.function.IntConsumer onClick){LinearLayout bar=row(c);for(int i=0;i<labels.length;i++){final int n=i;Button b=button(c,labels[i],i==selected,()->onClick.accept(n));b.setTextSize(12);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(c,38),1);if(i>0)p.leftMargin=dp(c,4);b.setSingleLine(true);b.setPadding(dp(c,4),0,dp(c,4),0);bar.addView(b,p);}return bar;}
  static LinearLayout nav(Activity a,int selected,java.util.function.IntConsumer action,Button[] buttons){LinearLayout bar=row(a);bar.setPadding(dp(a,6),dp(a,5),dp(a,6),dp(a,5));bar.setBackground(surface(a,CARD,0,LINE));for(int i=0;i<5;i++){final int n=i;Button b=button(a,NAV[i],false,()->action.accept(n));b.setTextColor(i==selected?BLUE:MUTED);if(i==selected)b.setBackground(surface(a,0xffeaf1ff,10,0xffd9e6ff));b.setSelected(i==selected);b.setTextSize(10);b.setPadding(dp(a,2),dp(a,4),dp(a,2),dp(a,4));Ui.Icon icon=new Ui.Icon(GLYPHS[i],i==selected?BLUE:MUTED);icon.setBounds(0,0,dp(a,21),dp(a,21));b.setCompoundDrawables(null,icon,null,null);b.setCompoundDrawablePadding(dp(a,4));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(a,50),1);p.setMargins(dp(a,2),0,dp(a,2),0);bar.addView(b,p);if(buttons!=null)buttons[i]=b;}return bar;}
  static void markNav(Activity a,Button[] tabs,int selected){for(int i=0;i<tabs.length;i++){tabs[i].setBackground(i==selected?surface(a,0xffeaf1ff,10,0xffd9e6ff):Ui.shape(a,CARD,10));tabs[i].setTextColor(i==selected?BLUE:MUTED);tabs[i].setSelected(i==selected);android.graphics.drawable.Drawable[] icons=tabs[i].getCompoundDrawables();if(icons[1] instanceof Ui.Icon)((Ui.Icon)icons[1]).color=i==selected?BLUE:MUTED;tabs[i].invalidate();}}
  static LinearLayout screen(Activity a){chrome(a);LinearLayout root=column(a);root.setFitsSystemWindows(true);root.setBackground(new Stars(a));return root;}
  static LinearLayout body(Activity a,LinearLayout root,String title,Runnable back){LinearLayout head=row(a);head.setPadding(dp(a,12),dp(a,8),dp(a,12),dp(a,8));if(back!=null){Button b=button(a,"‹",false,back);b.setContentDescription("返回");head.addView(b,new LinearLayout.LayoutParams(dp(a,36),dp(a,36)));}TextView heading=text(a,title,20,TEXT);heading.setTypeface(Typeface.DEFAULT_BOLD);heading.setPadding(dp(a,8),0,0,0);head.addView(heading,new LinearLayout.LayoutParams(0,-2,1));root.addView(head);LinearLayout box=column(a);box.setPadding(dp(a,14),0,dp(a,14),dp(a,18));ScrollView scroll=new ScrollView(a);scroll.setFillViewport(true);scroll.addView(box);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));return box;}
  static void section(LinearLayout box,String title,String detail){TextView h=text(box.getContext(),title,15,TEXT);h.setTypeface(Typeface.DEFAULT_BOLD);h.setPadding(0,dp(box.getContext(),18),0,dp(box.getContext(),4));box.addView(h);if(!detail.isEmpty())note(box,detail);}
  static void scope(MainActivity a,LinearLayout box){LinearLayout card=card(a);card.addView(text(a,"环境 "+String.format(java.util.Locale.ROOT,"%02d",Profiles.slot(a)+1)+" · "+Profiles.display(a,Profiles.slot(a)),16,TEXT));note(card,"此页仅作用于该环境，登录与网络分别保存。");action(card,"切换环境",false,()->a.startActivity(new Intent(a,WindowHomeActivity.class).addFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT)));addCard(box,card);}
  static AlertDialog message(Activity a,String title,String text){return new AlertDialog.Builder(a).setTitle(title).setMessage(text).setPositiveButton("知道了",null).show();}
  static final class Stars extends Drawable {final Paint p=new Paint(3);final Context c;Stars(Context c){this.c=c;}public void draw(Canvas canvas){canvas.drawColor(BG);if(!AppSettings.bool(c,"starBackground",false))return;Rect b=getBounds();Random r=new Random(87);for(int i=0;i<100;i++){float x=r.nextFloat()*b.width(),y=r.nextFloat()*b.height();p.setColor(i%4==0?0x552a78c7:0x222598dc);canvas.drawCircle(x,y,i%9==0?1.6f:.7f,p);}p.setShader(new LinearGradient(0,0,b.width(),b.height()/2f,new int[]{0x180453a2,0x000453a2},null,Shader.TileMode.CLAMP));canvas.drawRect(b,p);p.setShader(null);}public void setAlpha(int a){}public void setColorFilter(ColorFilter f){}public int getOpacity(){return PixelFormat.OPAQUE;}}
}
