package local.pocketchat;
import android.app.*;import android.widget.*;import org.json.*;import java.util.*;

final class DesignSettingsUi {
  static void render(MainActivity a,LinearLayout box,int selected){box.addView(DesignUi.tabs(a,new String[]{"当前窗口设置","全局应用设置"},selected,n->{a.hub.settingsTab=n;a.hub.settings();}));DesignUi.note(box,selected==0?"当前窗口："+Profiles.display(a,Profiles.slot(a)):"全局设置控制应用入口与外观");
    if(selected==0){group(a,box,"基础设置","窗口名称、平台、真实语言与时区","window",()->EnvironmentEditorUi.editTab(a,0));group(a,box,"浏览器配置","实际内核、UA、WebRTC 与保护等级","globe",()->EnvironmentEditorUi.editTab(a,1));group(a,box,"网络设置","网络方式、节点、订阅、连接检查","globe",()->a.hub.select(4));group(a,box,"数据与存储","草稿、历史、缓存与下载记录","file",()->a.hub.cache());group(a,box,"偏好设置","历史、草稿、滚动位置、后台与通知","settings",()->EnvironmentEditorUi.editTab(a,2));group(a,box,"隐私保护 / 环境自检","保护等级、一致性与变化提醒","shield",()->DesignPrivacyUi.show(a));}
    else{group(a,box,"默认窗口与启动入口","默认："+Profiles.display(a,AppSettings.defaultSlot(a)),"window",()->defaultEntry(a));group(a,box,"应用外观","星空深蓝、背景纹理、品牌页","brand",()->appearance(a));group(a,box,"下载设置","默认目录与当前窗口的下载偏好","download",()->downloads(a));group(a,box,"后台等待与通知","应用偏好、系统通知和电池设置","chat",()->FeatureDialogs.backgroundSettings(a));group(a,box,"关于与使用帮助","版本、功能、第三方许可与诊断","settings",()->a.hub.about());}}
  static void group(MainActivity a,LinearLayout box,String title,String detail,String icon,Runnable click){DesignUi.addCard(box,DesignUi.setting(a,icon,title,detail,"",click));}
  static void defaultEntry(MainActivity a){JSONArray rows=ProfileCatalog.get(a).list();List<Integer> ids=new ArrayList<>();List<String> titles=new ArrayList<>();for(int i=0;i<rows.length();i++)if(rows.optJSONObject(i).optBoolean("created")){ids.add(i);titles.add(rows.optJSONObject(i).optString("name"));}LinearLayout box=DesignUi.column(a);box.setPadding(a.dp(18),0,a.dp(18),a.dp(14));Spinner spinner=new Spinner(a);spinner.setAdapter(new ArrayAdapter<>(a,android.R.layout.simple_spinner_dropdown_item,titles));spinner.setSelection(Math.max(0,ids.indexOf(AppSettings.defaultSlot(a))));box.addView(spinner);CheckBox direct=new CheckBox(a);direct.setText("启动时直达默认窗口的原网页");direct.setChecked(AppSettings.bool(a,"startupDirect",true));box.addView(direct);DesignUi.note(box,"关闭后先进入窗口列表。已有窗口分别保留登录与网络设置。");new AlertDialog.Builder(a).setTitle("默认窗口与启动方式").setView(box).setPositiveButton("保存",(d,w)->{AppSettings.defaultSlot(a,ids.get(spinner.getSelectedItemPosition()));AppSettings.put(a,"startupDirect",String.valueOf(direct.isChecked()));a.hub.settings();if(a.designChrome!=null)a.designChrome.update();}).setNegativeButton("取消",null).show();}
  static void appearance(MainActivity a){LinearLayout box=DesignUi.column(a);box.setPadding(a.dp(18),0,a.dp(18),a.dp(14));DesignUi.field(box,"当前主题","星空深蓝 · 蓝紫渐变");CheckBox stars=new CheckBox(a);stars.setText("显示星空背景纹理");stars.setChecked(AppSettings.bool(a,"starBackground",true));box.addView(stars);Button brand=DesignUi.button(a,"查看品牌启动页",false,()->a.startActivity(new android.content.Intent(a,BrandLaunchActivity.class).putExtra("previewBrand",true)));box.addView(brand);new AlertDialog.Builder(a).setTitle("应用外观").setView(box).setPositiveButton("保存",(d,w)->{AppSettings.put(a,"starBackground",String.valueOf(stars.isChecked()));a.hub.settings();a.hub.root.invalidate();}).setNegativeButton("取消",null).show();}
  static void downloads(MainActivity a){LinearLayout box=DesignUi.column(a);box.setPadding(a.dp(18),0,a.dp(18),a.dp(14));DesignUi.field(box,"当前窗口默认目录",DefaultDownloads.description(a));CheckBox wifi=new CheckBox(a);wifi.setText("当前窗口仅在 Wi-Fi 下载");wifi.setChecked(AppPrefs.enabled(a,"wifiDownloads"));box.addView(wifi);DesignUi.addCard(box,DesignUi.setting(a,"download","自定义默认目录","目录设置接口已预留","开发中",()->FutureFeatures.open(a,FutureFeatures.Feature.CUSTOM_DOWNLOAD_PATH,Profiles.slot(a))));new AlertDialog.Builder(a).setTitle("下载设置").setView(box).setPositiveButton("保存",(d,w)->AppPrefs.apply(a,J.obj("wifiDownloads",wifi.isChecked()))).setNegativeButton("取消",null).show();}
}
