package local.pocketchat;
import android.app.*;import android.widget.*;import org.json.*;import java.text.SimpleDateFormat;import java.util.*;

final class DraftUi {
 final MainActivity a;String shown="";AlertDialog dialog;
 DraftUi(MainActivity a){this.a=a;}
 static String preview(String text){String s=text.replaceAll("\\s+"," ").trim();return s.length()>160?s.substring(0,160)+"…":s;}
 void update(){JSONObject conflict=a.session.draftConflict;if(conflict==null){if(dialog!=null&&dialog.isShowing())dialog.dismiss();return;}if(conflict.optString("id").equals(shown)||a.isFinishing()||a.destroyed)return;shown=conflict.optString("id");if(!a.input.getText().toString().equals(conflict.optString("native"))){a.session.draftConflict=null;a.session.setStatus("输入内容已修改，请重新点发送");return;}if(dialog!=null)dialog.dismiss();LinearLayout box=new LinearLayout(a);box.setOrientation(1);box.setPadding(a.dp(24),a.dp(8),a.dp(24),a.dp(12));TextView text=a.label("当前输入\n"+preview(conflict.optString("native"))+"\n\n网页保留的草稿\n"+preview(conflict.optString("web"))+"\n\n发送当前输入前，会先暂存网页草稿，可从更多选项恢复。",15,Ui.INK);box.addView(text);ScrollView scroll=new ScrollView(a);scroll.addView(box);dialog=new AlertDialog.Builder(a).setTitle("选择本次发送内容").setView(scroll).setPositiveButton("发送当前输入",(d,w)->{if(!a.input.getText().toString().equals(conflict.optString("native"))){a.session.draftConflict=null;a.status("输入内容已改变，请重新点发送");return;}a.session.resolveDraftConflict(conflict);}).setNeutralButton("使用网页草稿",(d,w)->{if(a.session.navigationEpoch!=conflict.optLong("epoch")){a.session.draftConflict=null;a.status("对话已改变，请重新打开草稿");return;}if(!DraftArchive.get(a).save(a.conversation,a.input.getText().toString(),"元婴期院士草稿")){a.status("暂存失败，当前输入未修改");return;}a.session.draftConflict=null;a.input.setText(conflict.optString("web"));a.input.setSelection(a.input.length());a.status("已放入网页草稿，原输入已暂存；点发送后才会发送");}).setNegativeButton("取消",(d,w)->a.session.draftConflict=null).create();dialog.setOnCancelListener(d->a.session.draftConflict=null);dialog.show();}
 void destroy(){if(dialog!=null)dialog.dismiss();}
 static void restore(MainActivity a){JSONArray entries=DraftArchive.get(a).list(a.conversation);String old=a.prefs.getString("draftBackup:"+a.conversation,"");if(!old.isEmpty())entries.put(J.obj("body",old,"origin","此前暂存","created",0));if(entries.length()==0){a.status("没有暂存的草稿");return;}String[] rows=new String[entries.length()];for(int i=0;i<rows.length;i++){JSONObject e=entries.optJSONObject(i);long time=e.optLong("created");rows[i]=e.optString("origin")+(time>0?" · "+new SimpleDateFormat("MM-dd HH:mm",Locale.getDefault()).format(new Date(time)):"")+"\n"+preview(e.optString("body"));}new AlertDialog.Builder(a).setTitle("恢复暂存草稿").setItems(rows,(d,n)->{String selected=entries.optJSONObject(n).optString("body"),current=a.input.getText().toString();if(!current.equals(selected)&&!DraftArchive.get(a).save(a.conversation,current,"元婴期院士草稿")){a.status("暂存当前输入失败，未替换");return;}a.input.setText(selected);a.input.setSelection(a.input.length());a.status("已恢复草稿，点发送后才会发送");}).setNegativeButton("关闭",null).show();}
}
