package local.pocketchat;

import android.app.*;
import android.widget.*;
import android.os.Build;
import org.json.*;
import java.util.*;

/** Edit current owning process only; a saved editor draft never applies settings. */
final class EnvironmentEditorUi {
  static JSONObject current(MainActivity a){JSONObject values=AppPrefs.values(a);try{values.put("name",Profiles.display(a,Profiles.slot(a)));values.put("privacyLevel",a.session.privacy.level());}catch(Exception ignored){}return values;}
  static void show(MainActivity a){JSONObject draft=J.parse(ProfileCatalog.get(a).item(Profiles.slot(a)).optString("draft"));if(draft.length()>0)new AlertDialog.Builder(a).setTitle("发现环境编辑草稿").setMessage("草稿尚未应用，不会改变当前登录或网络。").setPositiveButton("继续编辑草稿",(d,w)->edit(a,draft)).setNeutralButton("编辑当前设置",(d,w)->edit(a,current(a))).setNegativeButton("取消",null).show();else edit(a,current(a));}
  static void edit(MainActivity a,JSONObject initial){LinearLayout outer=new LinearLayout(a);outer.setOrientation(1);outer.setPadding(a.dp(18),a.dp(8),a.dp(18),a.dp(12));LinearLayout tabs=new LinearLayout(a);outer.addView(tabs);LinearLayout basic=new LinearLayout(a),advanced=new LinearLayout(a),preferences=new LinearLayout(a);for(LinearLayout page:new LinearLayout[]{basic,advanced,preferences})page.setOrientation(1);FrameLayoutHost host=new FrameLayoutHost(a,basic,advanced,preferences);outer.addView(host);
    EditText name=FeatureDialogs.field(a,basic,"环境名称（最多 24 字）",initial.optString("name"),android.text.InputType.TYPE_CLASS_TEXT);basic.addView(a.label("平台：ChatGPT · chatgpt.com\n系统：Android "+Build.VERSION.RELEASE+"\n浏览器内核：系统 WebView "+EnvironmentAudit.packageVersion()+"\n手机语言："+Locale.getDefault().toLanguageTag()+"\n手机时区："+TimeZone.getDefault().getID()+"\n\n系统、内核与地区信息显示真实值，没有模拟 Windows 或替换浏览器内核。",14,Ui.MUTED));
    String[] levels={"兼容","标准（默认）","强化"};Spinner privacy=new Spinner(a);privacy.setAdapter(new ArrayAdapter<>(a,android.R.layout.simple_spinner_dropdown_item,levels));privacy.setSelection(Math.max(0,Math.min(2,initial.optInt("privacyLevel",1))));advanced.addView(a.label("当前隐私保护等级",15,Ui.INK));advanced.addView(privacy);advanced.addView(a.label("标准：精简 UA，加载前限制 WebRTC、设备信息、电量和网络类型。\n强化：另限制 Canvas 和音频像素读取，可能影响网页功能。\n\n这不是随机指纹或完整内核伪装。后台脚本尚未完整覆盖，可在环境自检中核对。",14,Ui.MUTED));Button audit=new Button(a);audit.setText("打开环境自检");advanced.addView(audit);audit.setOnClickListener(v->EnvironmentAuditUi.show(a));
    CheckBox[] options=new CheckBox[AppPrefs.KEYS.length];for(int i=0;i<options.length;i++){options[i]=new CheckBox(a);options[i].setText(AppPrefs.LABELS[i]);options[i].setChecked(initial.has(AppPrefs.KEYS[i])?initial.optBoolean(AppPrefs.KEYS[i]):AppPrefs.enabled(a,AppPrefs.KEYS[i]));preferences.addView(options[i]);}preferences.addView(a.label("自动历史仅同步网页可见列表，完整同步仍可手动操作。关闭草稿保存不删除已有草稿。关闭后台等待不撤销网页提问。缓存策略只处理无引用的旧下载中间文件，保留聊天、Cookie 和已保存文件。",13,Ui.MUTED));
    for(int i=0;i<3;i++){final int page=i;Button tab=new Button(a);tab.setText(new String[]{"基础设置","高级指纹","偏好设置"}[i]);tab.setTextSize(12);tabs.addView(tab,new LinearLayout.LayoutParams(0,-2,1));tab.setOnClickListener(v->host.page(page));}host.page(0);ScrollView scroll=new ScrollView(a);scroll.addView(outer);AlertDialog dialog=new AlertDialog.Builder(a).setTitle("编辑 "+Profiles.display(a,Profiles.slot(a))).setView(scroll).setPositiveButton("保存修改",null).setNeutralButton("保存编辑草稿",null).setNegativeButton("取消",null).create();
    java.util.function.Supplier<JSONObject> read=()->{JSONObject out=new JSONObject();try{out.put("name",name.getText().toString().trim());out.put("privacyLevel",privacy.getSelectedItemPosition());for(int i=0;i<options.length;i++)out.put(AppPrefs.KEYS[i],options[i].isChecked());}catch(Exception ignored){}return out;};
    dialog.setOnShowListener(d->{dialog.getButton(-3).setOnClickListener(v->{ProfileCatalog.get(a).draft(Profiles.slot(a),read.get());a.status("环境编辑草稿已保存，当前设置未改动");dialog.dismiss();});dialog.getButton(-1).setOnClickListener(v->{JSONObject value=read.get();String title=value.optString("name");if(title.isEmpty()||title.length()>24){name.setError("请输入 1–24 字的名称");host.page(0);return;}ChatSession s=a.session;int level=value.optInt("privacyLevel");boolean change=level!=s.privacy.level();if(change&&ProfileUi.working(s)){a.status("当前有未完成任务，结束后再调整保护等级");return;}if(level>0&&(!s.privacy.earlySupported()||!s.guard.workerProtection)){a.status("此等级需要更新 Android System WebView，设置未改动");return;}Profiles.rename(a,Profiles.slot(a),title);AppPrefs.apply(a,value);s.prefs.edit().putInt("privacyLevel",level).commit();ProfileCatalog.get(a).draft(Profiles.slot(a),null);if(!AppPrefs.enabled(a,"backgroundWait"))ChatService.end(a);if(change){s.audit.cancel();s.invalidateConnection();s.privacy.apply();s.openConnection(true,true);}s.audit.refresh(true);ProfileCatalog.get(a).heartbeat(s,true);dialog.dismiss();if(a.hub!=null)a.hub.refresh();a.status("环境设置已保存");});});dialog.show();}
  static final class FrameLayoutHost extends android.widget.FrameLayout {final LinearLayout[] pages;FrameLayoutHost(MainActivity a,LinearLayout... views){super(a);pages=views;for(LinearLayout v:views)addView(v);}void page(int selected){for(int i=0;i<pages.length;i++)pages[i].setVisibility(i==selected?android.view.View.VISIBLE:android.view.View.GONE);}}
}
