package local.pocketchat;
import android.app.*;import android.widget.*;import android.os.Build;import android.text.*;import org.json.*;import java.util.*;

/** Designed editor preserves the existing draft/apply contract and real browser identity. */
final class EnvironmentEditorUi {
  static JSONObject current(MainActivity a){JSONObject values=AppPrefs.values(a);try{values.put("name",Profiles.display(a,Profiles.slot(a)));values.put("privacyLevel",a.session.privacy.level());}catch(Exception ignored){}return values;}
  static void show(MainActivity a){editTab(a,0);}
  static void editTab(MainActivity a,int tab){JSONObject draft=J.parse(ProfileCatalog.get(a).item(Profiles.slot(a)).optString("draft"));if(draft.length()>0)new AlertDialog.Builder(a).setTitle("发现窗口编辑草稿").setMessage("这份草稿尚未应用。").setPositiveButton("继续编辑草稿",(d,w)->edit(a,draft,tab)).setNeutralButton("编辑当前设置",(d,w)->edit(a,current(a),tab)).setNegativeButton("取消",null).show();else edit(a,current(a),tab);}
  static void edit(MainActivity a,JSONObject value){edit(a,value,0);}
  static void edit(MainActivity a,JSONObject initial,int tab){Dialog dialog=new Dialog(a);LinearLayout root=DesignUi.screen(a),outer=DesignUi.body(a,root,"编辑窗口",()->dialog.dismiss());LinearLayout tabs=DesignUi.row(a);outer.addView(tabs);LinearLayout basic=DesignUi.column(a),browser=DesignUi.column(a),preferences=DesignUi.column(a);FrameLayoutHost host=new FrameLayoutHost(a,basic,browser,preferences);outer.addView(host);LinearLayout basicCard=DesignUi.card(a);EditText name=DesignUi.input(basicCard,"窗口名称（最多 24 字）",initial.optString("name"),"输入名称");TextView counter=DesignUi.text(a,name.length()+" / 24",11,DesignUi.MUTED);basicCard.addView(counter);name.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int x,int c,int f){}public void onTextChanged(CharSequence s,int x,int b,int c){counter.setText(s.length()+" / 24");}public void afterTextChanged(Editable e){}});DesignUi.field(basicCard,"平台类型","ChatGPT · chatgpt.com");DesignUi.field(basicCard,"Android 版本","Android "+Build.VERSION.RELEASE+"（API "+Build.VERSION.SDK_INT+"）");DesignUi.field(basicCard,"WebView 版本",EnvironmentAudit.packageVersion());DesignUi.field(basicCard,"手机语言",Locale.getDefault().toLanguageTag());DesignUi.field(basicCard,"手机时区",TimeZone.getDefault().getID());DesignUi.addCard(basic,basicCard);DesignUi.addCard(basic,DesignUi.setting(a,"globe","独立语言与时区参数","当前显示手机真实值","开发中",()->FutureFeatures.open(a,FutureFeatures.Feature.LANGUAGE_TIMEZONE,Profiles.slot(a))));
    LinearLayout browserCard=DesignUi.card(a);DesignUi.field(browserCard,"浏览器内核","Chromium · Android System WebView");DesignUi.field(browserCard,"实际 User-Agent",a.remote.getSettings().getUserAgentString());android.util.DisplayMetrics metrics=a.getResources().getDisplayMetrics();DesignUi.field(browserCard,"屏幕分辨率",metrics.widthPixels+" × "+metrics.heightPixels+"（当前方向）");DesignUi.field(browserCard,"字体指纹","系统默认，扩展参数尚未接入");TextView levelTitle=DesignUi.text(a,"隐私保护等级",14,DesignUi.TEXT);levelTitle.setPadding(0,a.dp(12),0,a.dp(6));browserCard.addView(levelTitle);Spinner privacy=new Spinner(a);privacy.setAdapter(new ArrayAdapter<>(a,android.R.layout.simple_spinner_dropdown_item,new String[]{"兼容","标准（默认）","强化"}));privacy.setSelection(Math.max(0,Math.min(2,initial.optInt("privacyLevel",1))));browserCard.addView(privacy);DesignUi.note(browserCard,"标准：加载前限制 WebRTC 和部分设备字段。强化：进一步限制 Canvas 与音频读取。保护等级在保存后应用。");DesignUi.field(browserCard,"当前 WebGL 状态",a.session.privacy.earlyInstalled?"可用 · 图形设备信息限制中":"系统默认，尚无加载前限制");DesignUi.field(browserCard,"当前 Canvas / 音频读取",a.session.privacy.level()==2&&a.session.privacy.earlyInstalled?"强化限制中":"允许读取");DesignUi.field(browserCard,"当前 WebRTC 本机接口",a.session.privacy.earlyInstalled?"加载前限制":"未覆盖，待自检核对");DesignUi.field(browserCard,"网页地理位置","不授权");DesignUi.addCard(browser,browserCard);DesignUi.action(browser,"环境自检与变更",true,()->EnvironmentAuditUi.show(a));for(FutureFeatures.Feature f:new FutureFeatures.Feature[]{FutureFeatures.Feature.CUSTOM_FINGERPRINT,FutureFeatures.Feature.PROXY_EXTENSION,FutureFeatures.Feature.AUTOMATION})DesignUi.addCard(browser,DesignUi.setting(a,"shield",f.title,"预留扩展接口","开发中",()->FutureFeatures.open(a,f,Profiles.slot(a))));
    CheckBox[] options=new CheckBox[AppPrefs.KEYS.length];LinearLayout prefCard=DesignUi.card(a);for(int i=0;i<options.length;i++){options[i]=new CheckBox(a);options[i].setText(AppPrefs.LABELS[i]);options[i].setTextColor(DesignUi.TEXT);options[i].setTextSize(14);options[i].setChecked(initial.has(AppPrefs.KEYS[i])?initial.optBoolean(AppPrefs.KEYS[i]):AppPrefs.enabled(a,AppPrefs.KEYS[i]));prefCard.addView(options[i]);}DesignUi.addCard(preferences,prefCard);DesignUi.note(preferences,"历史自动同步只处理可见列表。完整同步仍可手动发起。关闭后台等待不撤销网页提问；旧临时文件清理保留聊天、登录和已保存文件。");
    updateTabs(a,tabs,host,tab);LinearLayout actions=DesignUi.row(a);actions.setPadding(a.dp(12),a.dp(10),a.dp(12),a.dp(10));java.util.function.Supplier<JSONObject> read=()->{JSONObject out=new JSONObject();try{out.put("name",name.getText().toString().trim());out.put("privacyLevel",privacy.getSelectedItemPosition());for(int i=0;i<options.length;i++)out.put(AppPrefs.KEYS[i],options[i].isChecked());}catch(Exception ignored){}return out;};Button cancel=DesignUi.button(a,"取消",false,()->dialog.dismiss()),draft=DesignUi.button(a,"保存草稿",false,()->{ProfileCatalog.get(a).draft(Profiles.slot(a),read.get());a.status("窗口编辑草稿已保存");dialog.dismiss();}),save=DesignUi.button(a,"保存修改",true,()->{JSONObject value=read.get();if(apply(a,value,name)){dialog.dismiss();}});for(Button button:new Button[]{cancel,draft,save}){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,a.dp(42),1);p.setMargins(a.dp(3),0,a.dp(3),0);actions.addView(button,p);}root.addView(actions);dialog.setContentView(root);dialog.show();dialog.getWindow().setBackgroundDrawableResource(android.R.color.transparent);dialog.getWindow().setLayout(-1,-1);}
  static void updateTabs(MainActivity a,LinearLayout tabs,FrameLayoutHost host,int selected){host.page(selected);tabs.removeAllViews();tabs.addView(DesignUi.tabs(a,new String[]{"基础","浏览器","偏好"},selected,n->updateTabs(a,tabs,host,n)),new LinearLayout.LayoutParams(-1,-2));}
  static boolean apply(MainActivity a,JSONObject value,EditText name){String title=value.optString("name");if(title.isEmpty()||title.length()>24){name.setError("请输入 1–24 字名称");return false;}ChatSession s=a.session;int level=value.optInt("privacyLevel");boolean change=level!=s.privacy.level();if(change&&ProfileUi.working(s)){a.status("当前有未完成任务，结束后再调整保护等级");return false;}if(level>0&&(!s.privacy.earlySupported()||!s.guard.workerProtection)){a.status("请更新 Android System WebView，设置未应用");return false;}Profiles.rename(a,Profiles.slot(a),title);AppPrefs.apply(a,value);s.prefs.edit().putInt("privacyLevel",level).commit();ProfileCatalog.get(a).draft(Profiles.slot(a),null);if(!AppPrefs.enabled(a,"backgroundWait"))ChatService.end(a);if(change){s.audit.cancel();s.invalidateConnection();s.privacy.apply();s.openConnection(true,true);}s.audit.refresh(true);ProfileCatalog.get(a).heartbeat(s,true);if(a.hub!=null)a.hub.refresh();a.status("窗口设置已保存");return true;}
  static final class FrameLayoutHost extends android.widget.FrameLayout {final LinearLayout[] pages;FrameLayoutHost(MainActivity a,LinearLayout... views){super(a);pages=views;for(LinearLayout v:views)addView(v);}void page(int n){for(int i=0;i<pages.length;i++)pages[i].setVisibility(i==n?android.view.View.VISIBLE:android.view.View.GONE);}}
}
