package local.pocketchat;

import android.app.*;
import android.content.*;
import android.net.Uri;
import android.webkit.*;
import android.widget.*;
import android.view.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

/** Downloads keep the configured route and save automatically to an app-owned destination. */
class FileDownloads {
  static final int SAVE=83;static final long MAX=512L*1024*1024;
  final MainActivity a;final ExecutorService worker=Executors.newSingleThreadExecutor();
  volatile InputStream nativeInput;volatile boolean cancelled;volatile HttpURLConnection connection;volatile File temp;volatile boolean active,destroyed;String imageLabel="",name="文件",mime="application/octet-stream",sourceId="",sourceKey="",sourceUrl="",retryUrl="",agent="",blobKey="",blobPage="";volatile long ticket=0;long blobSize,offset,ignoreUntil=0;Dialog dialog;AlertDialog noticeDialog;TextView progress;
  final SavedFileActions savedActions;final DownloadTasks tasks;JSONObject task;boolean resumeRequested=false,minimized=false,completeFile=false,awaitingPicker=false;long pickerTicket=-1;volatile Uri savingDestination;AlertDialog manager;String resumeValidator="",resumeAddress="";volatile long receivedBytes=0,totalBytes=-1;
  FileDownloads(MainActivity a){this.a=a;savedActions=new SavedFileActions(a);tasks=new DownloadTasks(a);a.remote.setDownloadListener((url,ua,cd,type,size)->accept(url,ua,cd,type,size));a.remote.responseDownload=this::acceptResponse;}
  void acceptResponse(org.mozilla.geckoview.WebResponse response){
    InputStream input=response.body;
    if(input==null){a.status("网页未提供文件内容，请重新点按下载");return;}
    if(destroyed||active&&!retryUrl.isEmpty()||awaitingPicker||System.currentTimeMillis()<ignoreUntil){try{input.close();}catch(IOException ignored){}a.status("请先完成当前下载，再下载这个文件");return;}
    try{AppPrefs.requireDownloadNetwork(a);if(!a.session.guard.allowed())throw new IOException("受保护连接已中断，下载已暂停");}catch(IOException error){try{input.close();}catch(IOException ignored){}a.status(error.getMessage());return;}
    if(!active){newTask("","",a.conversation);active=true;a.session.transferActive=true;a.session.updateBrowserActivity();cancelled=false;++ticket;}
    retryUrl=response.uri;String proposed=GeckoWebView.header(response,"Content-Type"),disposition=GeckoWebView.header(response,"Content-Disposition");
    if(sourceId.isEmpty()||name.equals("文件"))name=safeName(URLUtil.guessFileName(response.uri,disposition,proposed));mime=type(name,proposed);mark("downloading","");
    response.setReadTimeoutMillis(25000);nativeInput=input;long attempt=ticket;showProgress("正在下载 "+name+"…");
    worker.execute(()->{try(InputStream stream=input){
      if(response.statusCode>=400)throw new IOException("网页未能提供文件（HTTP "+response.statusCode+"），请在原网页重新点按下载");
      long expected=-1;try{if(GeckoWebView.header(response,"Content-Encoding").isEmpty()||"identity".equalsIgnoreCase(GeckoWebView.header(response,"Content-Encoding")))expected=Long.parseLong(GeckoWebView.header(response,"Content-Length"));}catch(Exception ignored){}
      if(expected>MAX)throw new IOException("文件超过 512 MB");
      File file=File.createTempFile("download-",".part",a.getCacheDir());temp=file;totalBytes=expected;receivedBytes=0;
      a.handler.post(()->{if(valid(attempt)){DownloadTasks.put(task,"partial",file.getName());tasks.save();}});
      try(OutputStream output=new FileOutputStream(file)){byte[] buffer=new byte[65536];int count;long reported=0;
        while((count=stream.read(buffer))!=-1){AppPrefs.requireDownloadNetwork(a);if(!valid(attempt)||!a.session.guard.allowed())throw new IOException("下载已暂停");if(receivedBytes+count>MAX||a.getCacheDir().getUsableSpace()<64L*1024*1024)throw new IOException("文件过大或剩余空间不足");output.write(buffer,0,count);receivedBytes+=count;if(System.currentTimeMillis()-reported>400){reported=System.currentTimeMillis();a.handler.post(()->{if(valid(attempt))transferProgress();});}}
      }
      if(expected>=0&&receivedBytes!=expected)throw new IOException("文件未下载完整，请在原网页重新下载");
      a.handler.post(()->{if(valid(attempt)){transferProgress();choose(attempt);}});
    }catch(Exception error){fail(attempt,error.getMessage());}finally{if(nativeInput==input)nativeInput=null;}});
  }
  static boolean https(String url){try{Uri u=Uri.parse(url);return "https".equals(u.getScheme())&&u.getHost()!=null&&u.getUserInfo()==null&&!url.matches("(?s).*[\\x00-\\x20\\\\].*");}catch(Exception e){return false;}}
  static String safeName(String value){String clean=(value==null?"文件":value).replaceAll("[\\\\/:*?\"<>|\\p{Cntrl}]","_").trim();return clean.isEmpty()?"文件":clean.length()>160?clean.substring(clean.length()-160):clean;}
  static String type(String name,String proposed){String ext=name.lastIndexOf('.')>=0?name.substring(name.lastIndexOf('.')+1).toLowerCase(Locale.ROOT):"";String known=MimeTypeMap.getSingleton().getMimeTypeFromExtension(ext);return known!=null?known:proposed==null||proposed.isEmpty()?"application/octet-stream":proposed.split(";")[0];}
  boolean intercept(String url){if(!active||!retryUrl.isEmpty()||sourceId.isEmpty()||!https(url))return false;Uri u=Uri.parse(url);String path=u.getPath()==null?"":u.getPath();if(MainActivity.chatUrl(url)&&!path.contains("/files/")&&!path.matches("(?i).*[.](docx?|pdf|xlsx?|pptx?|zip|csv|txt)$"))return false;accept(url,a.remote.getSettings().getUserAgentString(),"",type(name,null),-1);return true;}
  boolean sameSource(){return sourceUrl.equals(a.conversation)&&!a.session.navigating&&MainActivity.chatUrl(a.remote.getUrl());}
  void open(String id,String key){try{AppPrefs.requireDownloadNetwork(a);}catch(IOException e){a.status(e.getMessage());return;}if(awaitingPicker){a.status("请先关闭文件保存窗口");return;}if(active){a.status("请先完成或取消当前下载");return;}if(a.session.offline||!a.session.networkReady||a.session.navigating){a.status("请联网并等待对话加载后再下载");return;}if(!resumeRequested)newTask(id,key,a.conversation);resumeRequested=false;retryUrl="";ignoreUntil=0;sourceId=id;sourceKey=key;sourceUrl=a.conversation;active=true;a.session.transferActive=true;a.session.updateBrowserActivity();cancelled=false;long attempt=++ticket;showProgress("正在获取文件下载链接…");a.runDriver("file-prepare",J.obj("id",id,"key",key,"expectedUrl",sourceUrl),r->{if(!valid(attempt))return;if(!r.optBoolean("ok")){fail(attempt,r.optString("reason","文件链接暂不可用"));return;}name=safeName(r.optString("name","文件"));imageLabel="image".equals(r.optString("kind"))?name:"";String direct=r.optString("direct");if(!direct.isEmpty()&&!GeckoWebView.active(a.remote)){accept(direct,a.remote.getSettings().getUserAgentString(),"","image".equals(r.optString("kind"))?"image/png":null,-1);return;}a.handler.postDelayed(()->point(attempt,false),120);});}
  void point(long attempt,boolean followup){if(!valid(attempt)||!sameSource()){fail(attempt,"对话已改变，请返回原对话下载");return;}a.runDriver(followup?"file-followup":"file-point",J.obj("id",sourceId,"key",sourceKey,"name",name,"expectedUrl",sourceUrl),r->{if(!valid(attempt))return;JSONObject point=r.optJSONObject("touch");if(point!=null){float x=(float)(point.optDouble("x")*a.remote.getWidth()/point.optDouble("width",1)),y=(float)(point.optDouble("y")*a.remote.getHeight()/point.optDouble("height",1));long time=android.os.SystemClock.uptimeMillis();a.remote.requestFocus();MotionEvent down=MotionEvent.obtain(time,time,MotionEvent.ACTION_DOWN,x,y,0);down.setSource(InputDevice.SOURCE_TOUCHSCREEN);a.remote.dispatchTouchEvent(down);down.recycle();a.handler.postDelayed(()->{if(!valid(attempt))return;MotionEvent up=MotionEvent.obtain(time,android.os.SystemClock.uptimeMillis(),MotionEvent.ACTION_UP,x,y,0);up.setSource(InputDevice.SOURCE_TOUCHSCREEN);a.remote.dispatchTouchEvent(up);up.recycle();},60);}if(!followup)a.handler.postDelayed(()->{if(valid(attempt)&&retryUrl.isEmpty())point(attempt,true);},1200);else a.handler.postDelayed(()->{if(valid(attempt)&&retryUrl.isEmpty())fail(attempt,"网页未提供下载，请重试或查看原网页");},8000);});}
  boolean valid(long attempt){return active&&!cancelled&&!destroyed&&attempt==ticket;}
  void accept(String url,String ua,String disposition,String proposed,long length){if(awaitingPicker)return;if(System.currentTimeMillis()<ignoreUntil)return;if(active&&!retryUrl.isEmpty())return;if(!https(url)&&!url.startsWith("blob:https://")){a.status("这个下载地址暂不支持，请查看原网页");return;}if(!active){if(!resumeRequested)newTask("","",a.conversation);resumeRequested=false;imageLabel="";sourceId="";sourceKey="";sourceUrl=a.conversation;active=true;a.session.transferActive=true;a.session.updateBrowserActivity();cancelled=false;++ticket;name=safeName(URLUtil.guessFileName(url,disposition,proposed));}if(length>MAX||length>a.getCacheDir().getUsableSpace()-64L*1024*1024){fail(ticket,"文件超过本机下载限额或可用空间，请使用浏览器另行下载");return;}if(name.equals("文件")||sourceId.isEmpty()||name.matches("图片 [0-9]+"))name=safeName(URLUtil.guessFileName(url,disposition,proposed));mime=type(name,proposed);if(!imageLabel.isEmpty()&&mime.startsWith("image/"))name=imageLabel+"."+imageExtension(mime);retryUrl=url;agent=ua;mark("downloading","");long attempt=ticket;showProgress("正在下载 "+name+"…");if(url.startsWith("blob:"))startBlob(attempt,url);else worker.execute(()->download(attempt,url,ua));}
  static String imageExtension(String type){String ext=MimeTypeMap.getSingleton().getExtensionFromMimeType(type);return ext==null?"png":ext;}
  Proxy route()throws Exception{AppPrefs.requireDownloadNetwork(a);if(!a.session.guard.allowed())throw new IOException("受保护连接已中断，下载已暂停");if(a.session.internalNetwork()){NativeNetwork n=NativeNetwork.get(a);if(!n.ready||!n.coreAlive())throw new IOException("应用代理未连接，请恢复连接后重试");Uri u=Uri.parse(n.proxy());return new Proxy(Proxy.Type.HTTP,new InetSocketAddress(u.getHost(),u.getPort()));}String proxy=a.prefs.getString("proxy","");if(proxy.isEmpty())return Proxy.NO_PROXY;if(!MainActivity.validProxy(proxy))throw new IOException("代理配置无效");Uri u=Uri.parse(proxy);if("https".equals(u.getScheme()))throw new IOException("当前代理类型请使用原网页下载");return new Proxy("socks".equals(u.getScheme())?Proxy.Type.SOCKS:Proxy.Type.HTTP,new InetSocketAddress(u.getHost(),u.getPort()));}
  HttpURLConnection connect(String url,Proxy proxy)throws Exception{return (HttpURLConnection)new URL(url).openConnection(proxy);}
  void download(long attempt,String initial,String ua){
    File local=temp;
    try{
      if(local==null||!local.isFile()){local=File.createTempFile("download-",".part",a.getCacheDir());temp=local;}
      File partial=local;a.handler.post(()->{if(valid(attempt)){DownloadTasks.put(task,"partial",partial.getName());tasks.save();}});
      Proxy proxy=route();String url=initial;
      for(int redirects=0;redirects<=5;redirects++){
        if(!valid(attempt))throw new IOException("下载已取消");AppPrefs.requireDownloadNetwork(a);if(!https(url)||!BrowserNetworkGuard.publicHttps(Uri.parse(url)))throw new IOException("下载地址或重定向不受支持");if(!a.session.guard.allowed())throw new IOException("受保护连接已中断，下载已暂停");
        HttpURLConnection c=connect(url,proxy);connection=c;c.setInstanceFollowRedirects(false);c.setConnectTimeout(10000);c.setReadTimeout(25000);c.setRequestProperty("Accept-Encoding","identity");
        if(ua!=null)c.setRequestProperty("User-Agent",ua);String cookie=GeckoWebView.active(a.remote)?((GeckoWebView)a.remote).downloadCookies(url):android.webkit.CookieManager.getInstance().getCookie(url);if(cookie!=null)c.setRequestProperty("Cookie",cookie);
        long base=local.length();String expected=resumeValidator;
        if(base>0&&!expected.isEmpty()&&resumeAddress.equals(DownloadRange.resource(url))){c.setRequestProperty("Range","bytes="+base+"-");c.setRequestProperty("If-Range",expected);}else base=0;
        try{
          int code=c.getResponseCode();if(!valid(attempt)||!a.session.guard.allowed())throw new IOException("下载已暂停，受保护连接不可用");if(code>=300&&code<400){String next=c.getHeaderField("Location");if(next==null)throw new IOException("下载重定向缺少地址");url=new URL(new URL(url),next).toString();continue;}
          if(code!=200&&code!=206){if(code==416){resumeValidator="";resumeAddress="";}throw new IOException(code==401||code==403?"链接已过期，点继续重新获取文件":"下载失败（HTTP "+code+"）");}
          long total;try{total=DownloadRange.total(c,base,expected);}catch(IOException invalid){resumeValidator="";resumeAddress="";try(RandomAccessFile reset=new RandomAccessFile(local,"rw")){reset.setLength(0);}receivedBytes=0;throw invalid;}
          if(code==200)base=0;
          if(total>MAX||total-base>a.getCacheDir().getUsableSpace()-64L*1024*1024)throw new IOException("文件超过本机 512 MB 限额或剩余空间不足");
          String encoding=c.getContentEncoding();if(encoding!=null&&!encoding.equalsIgnoreCase("identity"))throw new IOException("文件编码不支持安全续传，请使用原网页下载");
          String nextValidator=DownloadRange.validator(c.getHeaderField("ETag"),c.getHeaderField("Last-Modified")),nextAddress=DownloadRange.resource(url);
          String contentType=c.getContentType();if(contentType!=null&&contentType.startsWith("image/")){mime=contentType.split(";")[0];name=imageLabel.isEmpty()?safeName(URLUtil.guessFileName(url,c.getHeaderField("Content-Disposition"),mime)):imageLabel+"."+imageExtension(mime);}if(contentType!=null&&contentType.startsWith("text/html")&&!mime.equals("text/html"))throw new IOException("文件链接返回了登录网页，请在原网页检查");
          receivedBytes=base;totalBytes=total;long received=base,reported=0;
          try(InputStream in=c.getInputStream();OutputStream out=new FileOutputStream(local,code==206)){
            resumeValidator=nextValidator;resumeAddress=nextAddress;
            byte[] bytes=new byte[65536];int size;
            while((size=in.read(bytes))!=-1){AppPrefs.requireDownloadNetwork(a);if(!valid(attempt)||!a.session.guard.allowed())throw new IOException("下载已暂停，受保护连接不可用");if(a.getCacheDir().getUsableSpace()<64L*1024*1024)throw new IOException("本机剩余空间不足，请清理后继续");received+=size;if(received>MAX)throw new IOException("文件超过 512 MB");out.write(bytes,0,size);receivedBytes=received;
              if(System.currentTimeMillis()-reported>400){reported=System.currentTimeMillis();a.handler.post(()->{if(valid(attempt))transferProgress();});}
            }
          }
          if(total>=0&&received!=total)throw new IOException("文件未下载完整，可继续下载");
          a.handler.post(()->{if(valid(attempt)){transferProgress();choose(attempt);}});return;
        }finally{c.disconnect();if(connection==c)connection=null;}
      }
      throw new IOException("文件重定向次数过多");
    }catch(Exception e){fail(attempt,e.getMessage());}
  }
  void startBlob(long attempt,String url){try{Uri origin=Uri.parse(a.remote.getUrl()),blobOrigin=Uri.parse(url.substring(5));if(!Objects.equals(origin.getScheme(),blobOrigin.getScheme())||!Objects.equals(origin.getHost(),blobOrigin.getHost())||origin.getPort()!=blobOrigin.getPort())throw new IOException("文件页面已改变，请重试");if(temp!=null)temp.delete();temp=File.createTempFile("download-",".part",a.getCacheDir());DownloadTasks.put(task,"partial",temp.getName());tasks.save();resumeValidator="";blobPage=a.remote.getUrl();blobKey="__pocketFile"+UUID.randomUUID().toString().replace("-","");String key=JSONObject.quote(blobKey);a.remote.evaluateJavascript("void(fetch("+JSONObject.quote(url)+").then(r=>r.blob()).then(b=>window["+key+"]={blob:b,size:b.size,mime:b.type,ready:true}).catch(()=>window["+key+"]={error:true}))",r->pollBlob(attempt,System.currentTimeMillis()+15000));}catch(Exception e){fail(attempt,e.getMessage());}}
  boolean blobValid(long attempt){return valid(attempt)&&Objects.equals(blobPage,a.remote.getUrl());}
  void pollBlob(long attempt,long deadline){if(!blobValid(attempt)){fail(attempt,"文件页面已改变，请重试");return;}a.remote.evaluateJavascript("(()=>{const f=window["+JSONObject.quote(blobKey)+"];return f?{ready:f.ready,size:f.size,mime:f.mime,error:f.error}:{};})()",raw->{if(!valid(attempt))return;JSONObject f=J.parse(raw);if(f.optBoolean("error")){fail(attempt,"文件链接已失效，请重试获取");return;}if(f.optBoolean("ready")){blobSize=f.optLong("size");totalBytes=blobSize;receivedBytes=0;if(f.optString("mime").startsWith("image/")){mime=f.optString("mime");name=imageLabel.isEmpty()?safeName(URLUtil.guessFileName(retryUrl,"",mime)):imageLabel+"."+imageExtension(mime);}if(blobSize>MAX||blobSize>a.getCacheDir().getUsableSpace()-64L*1024*1024){fail(attempt,"文件超过 512 MB 或剩余空间不足");return;}offset=0;chunk(attempt);}else if(System.currentTimeMillis()<deadline)a.handler.postDelayed(()->pollBlob(attempt,deadline),120);else fail(attempt,"读取文件超时，请重试");});}
  void chunk(long attempt){if(!blobValid(attempt)){fail(attempt,"文件页面已改变，请重试");return;}if(offset>=blobSize){clearBlob();choose(attempt);return;}long end=Math.min(blobSize,offset+192*1024);String key=JSONObject.quote(blobKey);a.remote.evaluateJavascript("void((async()=>{const f=window["+key+"];if(!f)return;try{const bytes=new Uint8Array(await f.blob.slice("+offset+","+end+").arrayBuffer());let text='';for(let i=0;i<bytes.length;i+=8192)text+=String.fromCharCode(...bytes.subarray(i,i+8192));f.chunk=btoa(text);}catch{f.error=true;}})())",r->readChunk(attempt,end,System.currentTimeMillis()+10000));}
  void readChunk(long attempt,long end,long deadline){if(!blobValid(attempt)){fail(attempt,"文件页面已改变，请重试");return;}a.remote.evaluateJavascript("(()=>{const f=window["+JSONObject.quote(blobKey)+"];if(!f||f.error)return {error:true};if(typeof f.chunk!=='string')return {};const chunk=f.chunk;delete f.chunk;return {chunk};})()",raw->{if(!valid(attempt))return;JSONObject f=J.parse(raw);if(f.optBoolean("error")){fail(attempt,"读取文件失败");return;}if(!f.has("chunk")){if(System.currentTimeMillis()<deadline)a.handler.postDelayed(()->readChunk(attempt,end,deadline),100);else fail(attempt,"读取文件超时");return;}File file=temp;worker.execute(()->{try{byte[] bytes=android.util.Base64.decode(f.getString("chunk"),android.util.Base64.DEFAULT);if(bytes.length!=end-offset||!valid(attempt))throw new IOException();try(OutputStream out=new FileOutputStream(file,true)){out.write(bytes);}offset=end;receivedBytes=end;totalBytes=blobSize;a.handler.post(()->{if(valid(attempt)){transferProgress();chunk(attempt);}});}catch(Exception e){fail(attempt,"文件片段保存失败，请重试");}});});}
  void chooseManually(long attempt){if(!valid(attempt))return;completeFile=true;mark("choosing","");dismiss();pickerTicket=attempt;awaitingPicker=true;try{a.startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType(mime).putExtra(Intent.EXTRA_TITLE,name),SAVE);}catch(ActivityNotFoundException e){awaitingPicker=false;fail(attempt,"设备没有文件保存器");}}
  void discard(DefaultDownloads.Target target){if(worker.isShutdown())new Thread(()->target.abort(),"download-cleanup").start();else worker.execute(()->target.abort());}
  void choose(long attempt){
    if(!valid(attempt))return;completeFile=true;mark("saving","");showProgress("正在保存到默认下载位置…");File file=temp;String chosenName=name,chosenMime=mime;JSONObject chosenTask=task;
    worker.execute(()->{try{DefaultDownloads.Target target=DefaultDownloads.create(a,chosenName,chosenMime);a.handler.post(()->{if(!valid(attempt)){discard(target);return;}savingDestination=target.uri;DownloadTasks.put(chosenTask,"pendingDestination",target.uri.toString(),"pendingLocation",target.location,"pendingName",target.name);tasks.save();worker.execute(()->{
      try{try(InputStream in=new FileInputStream(file);OutputStream out=target.output()){byte[] bytes=new byte[65536];int count;while((count=in.read(bytes))!=-1){if(!valid(attempt))throw new IOException("保存已暂停");out.write(bytes,0,count);}out.flush();}if(!valid(attempt))throw new IOException("保存已暂停");target.publish();a.handler.post(()->{if(!valid(attempt)){discard(target);return;}savingDestination=null;name=target.name;remember(target.uri);DownloadTasks.put(chosenTask,"uri",target.uri.toString(),"location",target.location);chosenTask.remove("pendingDestination");chosenTask.remove("pendingLocation");chosenTask.remove("pendingName");mark("saved","");ChatService.downloaded(a,chosenTask.optString("id"),name);active=false;a.session.transferActive=false;a.session.updateBrowserActivity();retryUrl="";dismiss();file.delete();temp=null;if(a.hub!=null&&a.hub.page==1)a.hub.refresh();if(!destroyed)noticeDialog=new AlertDialog.Builder(a).setTitle("文件已保存").setMessage(name+"\n"+target.location).setPositiveButton("打开文件",(d,w)->openSaved(target.uri,mime)).setNeutralButton("下载页面",(d,w)->a.hub.select(1)).setNegativeButton("完成",null).show();});
      }catch(Exception e){target.abort();a.handler.post(()->{if(target.uri.equals(savingDestination))savingDestination=null;chosenTask.remove("pendingDestination");chosenTask.remove("pendingLocation");chosenTask.remove("pendingName");tasks.save();});fail(attempt,"默认保存失败，文件已下载。可重试或从下载管理另存为。");}
    });});}catch(Exception e){fail(attempt,"默认保存位置不可用，文件已下载，可从下载管理另存为。");}});
  }
  void result(int code,Intent data){long chosen=pickerTicket;awaitingPicker=false;pickerTicket=-1;if(!valid(chosen)){if(data!=null&&data.getData()!=null)deleteIncomplete(data.getData());return;}if(code!=Activity.RESULT_OK||data==null||data.getData()==null){pause();return;}long attempt=ticket;Uri uri=data.getData();savingDestination=uri;try{a.getContentResolver().takePersistableUriPermission(uri,data.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION));}catch(Exception ignored){}File file=temp;mark("saving","");showProgress("正在保存文件…");worker.execute(()->{try{try(InputStream in=new FileInputStream(file);OutputStream out=a.getContentResolver().openOutputStream(uri,"wt")){if(out==null)throw new IOException();byte[] bytes=new byte[65536];int count;while((count=in.read(bytes))!=-1){if(!valid(attempt))throw new IOException();out.write(bytes,0,count);}out.flush();}a.handler.post(()->{if(!valid(attempt)){deleteIncomplete(uri);return;}savingDestination=null;remember(uri);DownloadTasks.put(task,"uri",uri.toString(),"location","你选择的保存位置");mark("saved","");ChatService.downloaded(a,task.optString("id"),name);active=false;a.session.transferActive=false;a.session.updateBrowserActivity();retryUrl="";dismiss();file.delete();temp=null;noticeDialog=new AlertDialog.Builder(a).setTitle("文件已保存").setMessage(name).setPositiveButton("打开文件",(d,w)->openSaved(uri,mime)).setNegativeButton("完成",null).show();});}catch(Exception e){deleteIncomplete(uri);savingDestination=null;fail(attempt,"保存失败，请选择可写入的位置后重试");}});}
  void deleteIncomplete(Uri uri){try{if(android.provider.DocumentsContract.isDocumentUri(a,uri))android.provider.DocumentsContract.deleteDocument(a.getContentResolver(),uri);else a.getContentResolver().delete(uri,null,null);}catch(Exception ignored){}}
  void remember(Uri uri){JSONArray previous=J.parse(a.prefs.getString("downloadHistory","{}")).optJSONArray("files"),files=new JSONArray();files.put(J.obj("name",name,"mime",mime,"uri",uri.toString(),"time",System.currentTimeMillis()));if(previous!=null)for(int i=0;i<Math.min(49,previous.length());i++)if(!uri.toString().equals(previous.optJSONObject(i).optString("uri")))files.put(previous.optJSONObject(i));a.prefs.edit().putString("downloadHistory",J.obj("files",files).toString()).apply();}
  void openSaved(Uri uri,String type){openSaved(uri,type,name);}
  void openSaved(Uri uri,String type,String title){if("application/pdf".equals(type)||type.startsWith("image/")){a.startActivity(new Intent(a,Profiles.preview(a)).putExtra("uri",uri.toString()).putExtra("name",title).putExtra("mime",type));return;}try{a.startActivity(new Intent(Intent.ACTION_VIEW).setDataAndType(uri,type).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION));}catch(ActivityNotFoundException e){a.status("文件已保存；手机尚未安装支持此格式的查看器");}catch(Exception e){a.status("文件已移动或访问失效，请重新下载");}}
  void showProgress(String text){if(destroyed||minimized)return;if(dialog==null){LinearLayout box=new LinearLayout(a);box.setGravity(Gravity.CENTER_VERTICAL);box.setPadding(a.dp(24),a.dp(20),a.dp(24),a.dp(20));box.addView(new ProgressBar(a),new LinearLayout.LayoutParams(a.dp(26),a.dp(26)));progress=a.label(text,15,Ui.INK);progress.setPadding(a.dp(16),0,0,0);box.addView(progress,new LinearLayout.LayoutParams(0,-2,1));AlertDialog d=new AlertDialog.Builder(a).setTitle("下载文件").setView(box).setPositiveButton("收起",(x,w)->{minimized=true;dismiss();}).setNeutralButton("暂停",(x,w)->pause()).setNegativeButton("取消",(x,w)->cancel()).create();d.setCanceledOnTouchOutside(false);d.setOnCancelListener(x->cancel());dialog=d;d.show();}progress.setText(text);}
  void retry(){if(active||awaitingPicker)return;minimized=false;ignoreUntil=0;cancelled=false;resumeRequested=false;if(completeFile&&temp!=null&&temp.isFile()){active=true;a.session.transferActive=true;a.session.updateBrowserActivity();choose(++ticket);return;}String id=sourceId,key=sourceKey,url=retryUrl;if(!id.isEmpty()&&!sameSource()){a.status("请返回原对话后重新下载");return;}if(a.session.offline||!a.session.networkReady){a.status("请恢复连接后继续下载");return;}if(id.isEmpty()&&url.isEmpty()){a.status("请回原网页再次点按下载");return;}resumeRequested=true;retryUrl="";if(!id.isEmpty())open(id,key);else accept(url,agent,"",mime,-1);resumeRequested=false;}
  void clearBlob(){if(!blobKey.isEmpty()&&Objects.equals(blobPage,a.remote.getUrl()))a.remote.evaluateJavascript("delete window["+JSONObject.quote(blobKey)+"]",null);blobKey="";}
  void dismiss(){if(dialog!=null){dialog.dismiss();dialog=null;}}
  void destroy(){if(active)pause();if(manager!=null)manager.dismiss();if(noticeDialog!=null)noticeDialog.dismiss();destroyed=true;savedActions.close();worker.shutdown();}
  void newTask(String id,String key,String url){name="文件";mime="application/octet-stream";imageLabel="";completeFile=false;task=tasks.add(id,key,url);temp=null;resumeValidator="";resumeAddress="";receivedBytes=0;totalBytes=-1;minimized=false;}
  void mark(String state,String reason){if(task==null)return;DownloadTasks.put(task,"state",state,"reason",reason==null?"":reason,"name",name,"mime",mime,"received",receivedBytes,"total",totalBytes,"validator",resumeValidator,"resource",resumeAddress,"complete",completeFile);if(temp!=null)DownloadTasks.put(task,"partial",temp.getName());tasks.save();}
  void transferProgress(){mark("downloading","");showProgress(name+"\n"+DownloadTasks.progress(task));}
  void fail(long attempt,String reason){a.handler.post(()->{if(!valid(attempt))return;mark(reason!=null&&reason.startsWith("仅 Wi-Fi")?"paused":"failed",reason);active=false;a.session.transferActive=false;a.session.updateBrowserActivity();dismiss();clearBlob();if(!destroyed)noticeDialog=new AlertDialog.Builder(a).setTitle("下载未完成").setMessage((reason==null?"请重试":reason)+"\n已保存的下载进度会在链接支持时继续使用。").setPositiveButton("继续 / 重试",(d,w)->retry()).setNeutralButton("下载管理",(d,w)->history()).setNegativeButton("关闭",null).show();});}
  void pause(){if(!active)return;ignoreUntil=System.currentTimeMillis()+1500;cancelled=true;active=false;a.session.transferActive=false;a.session.updateBrowserActivity();ticket++;if(connection!=null)connection.disconnect();InputStream nativeStream=nativeInput;nativeInput=null;if(nativeStream!=null)new Thread(()->{try{nativeStream.close();}catch(IOException ignored){}},"download-close").start();clearBlob();dismiss();Uri incomplete=savingDestination;savingDestination=null;if(incomplete!=null&&!worker.isShutdown())worker.execute(()->deleteIncomplete(incomplete));mark("paused","点击继续；网页临时文件可能需要重新下载");}
  void cancel(){pause();ignoreUntil=System.currentTimeMillis()+3000;completeFile=false;mark("cancelled","你已取消下载");retryUrl="";File file=temp;temp=null;if(file!=null&&!worker.isShutdown())worker.execute(()->file.delete());}
  void loadTask(JSONObject row){task=row;name=row.optString("name","文件");mime=row.optString("mime","application/octet-stream");sourceId=row.optString("source");sourceKey=row.optString("key");sourceUrl=row.optString("conversation");retryUrl="";temp=tasks.partial(row);resumeValidator=row.optString("validator");resumeAddress=row.optString("resource");completeFile=row.optBoolean("complete")&&temp!=null;receivedBytes=temp==null?0:temp.length();totalBytes=row.optLong("total",-1);imageLabel="";}
  void history(){if(manager!=null&&manager.isShowing())return;LinearLayout box=new LinearLayout(a);box.setOrientation(1);box.setPadding(a.dp(16),a.dp(8),a.dp(16),a.dp(8));ListView list=new ListView(a);box.addView(list,new LinearLayout.LayoutParams(-1,a.dp(360)));List<JSONObject> rows=new ArrayList<>();for(int i=0;i<tasks.rows.length();i++)rows.add(tasks.rows.optJSONObject(i));JSONArray old=J.parse(a.prefs.getString("downloadHistory","{}")).optJSONArray("files");if(old!=null)for(int i=0;i<old.length();i++){JSONObject r=old.optJSONObject(i);boolean duplicate=false;for(JSONObject item:rows)if(item.optString("uri").equals(r.optString("uri")))duplicate=true;if(!duplicate){JSONObject copy=J.parse(r.toString());DownloadTasks.put(copy,"state","saved");rows.add(copy);}}ArrayAdapter<String> adapter=new ArrayAdapter<>(a,android.R.layout.simple_list_item_1,new ArrayList<>());list.setAdapter(adapter);Runnable refresh=new Runnable(){public void run(){if(manager==null||!manager.isShowing())return;adapter.clear();for(JSONObject r:rows){String state=r.optString("state");adapter.add(r.optString("name")+"\n"+DownloadTasks.label(state)+(state.equals("saved")?"":" · "+DownloadTasks.progress(r))+(r.optString("reason").isEmpty()?"":"\n"+r.optString("reason")));}if(rows.isEmpty())adapter.add("还没有下载记录");adapter.notifyDataSetChanged();a.handler.postDelayed(this,700);}};list.setOnItemClickListener((p,v,n,id)->{if(n<rows.size())taskActions(rows.get(n));});manager=new AlertDialog.Builder(a).setTitle("下载管理").setView(box).setNegativeButton("关闭",null).create();manager.show();refresh.run();}
  void taskActions(JSONObject r){if(r.optString("state").equals("saved")){savedActions.show(r);return;}boolean current=task!=null&&task.optString("id").equals(r.optString("id"));if(active&&current){new AlertDialog.Builder(a).setTitle(r.optString("name")).setItems(new String[]{"查看进度","暂停","取消下载"},(d,n)->{if(n==0){minimized=false;showProgress(DownloadTasks.progress(r));}else if(n==1)pause();else cancel();}).show();return;}LinearLayout detail=new LinearLayout(a);detail.setOrientation(1);TextView reason=a.label(r.optString("reason")+"\n"+DownloadTasks.progress(r),14,Ui.MUTED);reason.setPadding(a.dp(20),a.dp(10),a.dp(20),a.dp(10));detail.addView(reason);if(r.optBoolean("complete")&&tasks.partial(r)!=null){Button save=new Button(a);save.setText("另存为已下载文件");detail.addView(save);save.setOnClickListener(v->{if(active||awaitingPicker){a.status("请先完成当前下载");return;}loadTask(r);cancelled=false;active=true;a.session.transferActive=true;a.session.updateBrowserActivity();chooseManually(++ticket);});}new AlertDialog.Builder(a).setTitle(r.optString("name")).setView(detail).setPositiveButton("继续下载",(d,w)->{if(active){a.status("请先暂停或完成当前下载");return;}String liveUrl=current?retryUrl:"";loadTask(r);retryUrl=liveUrl;if(!completeFile&&sourceId.isEmpty()&&retryUrl.isEmpty()){a.status("请回原网页再次点按下载，临时链接不会长期保存");return;}if(!completeFile&&!sourceId.isEmpty()&&!sameSource()){a.status("请返回该文件所在对话，再从下载管理继续");return;}retry();}).setNeutralButton("取消并清理",(d,w)->{if(active){a.status("请先暂停当前下载");return;}loadTask(r);cancel();}).setNegativeButton("关闭",null).show();}

}
