package local.pocketchat;

/** Read-only compatibility metadata; actual Firefox settings use the native SDK. */
@SuppressWarnings("deprecation")
final class GeckoSettings extends android.webkit.WebSettings {
  String userAgent="";
  @Override public boolean enableSmoothTransition(){return false;}
  @Override public boolean getAllowContentAccess(){return false;}
  @Override public boolean getAllowFileAccess(){return false;}
  @Override public boolean getAllowFileAccessFromFileURLs(){return false;}
  @Override public boolean getAllowUniversalAccessFromFileURLs(){return false;}
  @Override public boolean getBlockNetworkImage(){return false;}
  @Override public boolean getBlockNetworkLoads(){return false;}
  @Override public boolean getBuiltInZoomControls(){return false;}
  @Override public int getCacheMode(){return 0;}
  @Override public java.lang.String getCursiveFontFamily(){return null;}
  @Override public boolean getDatabaseEnabled(){return false;}
  @Override public java.lang.String getDatabasePath(){return null;}
  @Override public int getDefaultFixedFontSize(){return 0;}
  @Override public int getDefaultFontSize(){return 0;}
  @Override public java.lang.String getDefaultTextEncodingName(){return null;}
  @Override public android.webkit.WebSettings.ZoomDensity getDefaultZoom(){return null;}
  @Override public int getDisabledActionModeMenuItems(){return 0;}
  @Override public boolean getDisplayZoomControls(){return false;}
  @Override public boolean getDomStorageEnabled(){return false;}
  @Override public java.lang.String getFantasyFontFamily(){return null;}
  @Override public java.lang.String getFixedFontFamily(){return null;}
  @Override public boolean getJavaScriptCanOpenWindowsAutomatically(){return false;}
  @Override public boolean getJavaScriptEnabled(){return false;}
  @Override public android.webkit.WebSettings.LayoutAlgorithm getLayoutAlgorithm(){return null;}
  @Override public boolean getLightTouchEnabled(){return false;}
  @Override public boolean getLoadWithOverviewMode(){return false;}
  @Override public boolean getLoadsImagesAutomatically(){return false;}
  @Override public boolean getMediaPlaybackRequiresUserGesture(){return false;}
  @Override public int getMinimumFontSize(){return 0;}
  @Override public int getMinimumLogicalFontSize(){return 0;}
  @Override public int getMixedContentMode(){return 0;}
  @Override public boolean getOffscreenPreRaster(){return false;}
  @Override public android.webkit.WebSettings.PluginState getPluginState(){return null;}
  @Override public boolean getSafeBrowsingEnabled(){return false;}
  @Override public java.lang.String getSansSerifFontFamily(){return null;}
  @Override public boolean getSaveFormData(){return false;}
  @Override public boolean getSavePassword(){return false;}
  @Override public java.lang.String getSerifFontFamily(){return null;}
  @Override public java.lang.String getStandardFontFamily(){return null;}
  @Override public int getTextZoom(){return 0;}
  @Override public boolean getUseWideViewPort(){return false;}
  @Override public java.lang.String getUserAgentString(){return userAgent;}
  @Override public void setAllowContentAccess(boolean p0){}
  @Override public void setAllowFileAccess(boolean p0){}
  @Override public void setAllowFileAccessFromFileURLs(boolean p0){}
  @Override public void setAllowUniversalAccessFromFileURLs(boolean p0){}
  @Override public void setBlockNetworkImage(boolean p0){}
  @Override public void setBlockNetworkLoads(boolean p0){}
  @Override public void setBuiltInZoomControls(boolean p0){}
  @Override public void setCacheMode(int p0){}
  @Override public void setCursiveFontFamily(java.lang.String p0){}
  @Override public void setDatabaseEnabled(boolean p0){}
  @Override public void setDatabasePath(java.lang.String p0){}
  @Override public void setDefaultFixedFontSize(int p0){}
  @Override public void setDefaultFontSize(int p0){}
  @Override public void setDefaultTextEncodingName(java.lang.String p0){}
  @Override public void setDefaultZoom(android.webkit.WebSettings.ZoomDensity p0){}
  @Override public void setDisabledActionModeMenuItems(int p0){}
  @Override public void setDisplayZoomControls(boolean p0){}
  @Override public void setDomStorageEnabled(boolean p0){}
  @Override public void setEnableSmoothTransition(boolean p0){}
  @Override public void setFantasyFontFamily(java.lang.String p0){}
  @Override public void setFixedFontFamily(java.lang.String p0){}
  @Override public void setGeolocationDatabasePath(java.lang.String p0){}
  @Override public void setGeolocationEnabled(boolean p0){}
  @Override public void setJavaScriptCanOpenWindowsAutomatically(boolean p0){}
  @Override public void setJavaScriptEnabled(boolean p0){}
  @Override public void setLayoutAlgorithm(android.webkit.WebSettings.LayoutAlgorithm p0){}
  @Override public void setLightTouchEnabled(boolean p0){}
  @Override public void setLoadWithOverviewMode(boolean p0){}
  @Override public void setLoadsImagesAutomatically(boolean p0){}
  @Override public void setMediaPlaybackRequiresUserGesture(boolean p0){}
  @Override public void setMinimumFontSize(int p0){}
  @Override public void setMinimumLogicalFontSize(int p0){}
  @Override public void setMixedContentMode(int p0){}
  @Override public void setNeedInitialFocus(boolean p0){}
  @Override public void setOffscreenPreRaster(boolean p0){}
  @Override public void setPluginState(android.webkit.WebSettings.PluginState p0){}
  @Override public void setRenderPriority(android.webkit.WebSettings.RenderPriority p0){}
  @Override public void setSafeBrowsingEnabled(boolean p0){}
  @Override public void setSansSerifFontFamily(java.lang.String p0){}
  @Override public void setSaveFormData(boolean p0){}
  @Override public void setSavePassword(boolean p0){}
  @Override public void setSerifFontFamily(java.lang.String p0){}
  @Override public void setStandardFontFamily(java.lang.String p0){}
  @Override public void setSupportMultipleWindows(boolean p0){}
  @Override public void setSupportZoom(boolean p0){}
  @Override public void setTextZoom(int p0){}
  @Override public void setUseWideViewPort(boolean p0){}
  @Override public void setUserAgentString(java.lang.String p0){}
  @Override public boolean supportMultipleWindows(){return false;}
  @Override public boolean supportZoom(){return false;}
}
