package local.pocketchat;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.net.Uri;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.webkit.*;
import android.widget.*;
import android.text.*;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import androidx.webkit.ProxyController;
import androidx.webkit.ProxyConfig;
import androidx.webkit.WebViewFeature;

public class MainActivity extends Activity {
  static final String ORIGIN="https://chatgpt.com/", LOCAL="https://appassets.androidplatform.net/";
  final Handler handler=new Handler(Looper.getMainLooper());
  WebView remote,reader; EditText input; TextView status; Button send,webButton; LinearLayout composer;
  DesignChrome designChrome;AppHub hub;ChatSession session; ConversationStore conversations; long seenConfirmation=0,seenWebConfirmation=0,seenDelivery=-1,shownGoogleLoginNotice=-1; final ChatSession.Observer sessionObserver=()->applySession();
  SharedPreferences prefs; JSONObject pending; JSONArray entries=new JSONArray();
  String driver,conversation="",lastTranscript="",stableReply="",lastBubbleColor=""; int stableTicks=0;
  boolean pageMode=false,readerReady=false,readerLoaded=false,readerDirty=true,active=false,inFlight=false,submitting=false,destroyed=false;
  boolean networkReady=false;String pageError="";
  LoadingUi loading;Attachments attachments;MessageActions messageActions;FileDownloads downloads;DraftUi draftUi;TextView exitIpLine,networkLine;
  LinearLayout toolbar;TextView nativeTab,webTab;AlertDialog networkDialog;String lastUiStatus="";TextView modelTitle,effortChip,webNotice;Ui.IconButton navigation;Dialog drawer;String currentModel="",currentEffort="";
  interface Result {void accept(JSONObject value);}
  int dp(int n){return (int)(getResources().getDisplayMetrics().density*n+.5f);}
  void status(String s){status.setText(s);boolean quiet=s.startsWith("已连接")||s.equals("回复完成");status.setVisibility(quiet?View.GONE:View.VISIBLE);boolean attention=s.matches(".*(失败|错误|请|待确认|未完成|无法).*" );status.setTextColor(attention?DesignUi.RED:Ui.MUTED);boolean nativeFeedback=hub!=null&&hub.page!=AppHub.CHAT&&!quiet&&!s.startsWith("正在")&&!s.startsWith("准备连接");if(!s.isEmpty()&&!s.equals(lastUiStatus)){if(nativeFeedback&&attention)hub.feedback(s,true);else if(nativeFeedback||pageMode&&attention)Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}lastUiStatus=s;}
  String asset(String path)throws IOException {try(InputStream in=getAssets().open(path)){ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] buf=new byte[8192];int n;while((n=in.read(buf))>0)b.write(buf,0,n);return b.toString("UTF-8");}}
  JSONObject object(String s){try{return new JSONObject(s);}catch(Exception e){return new JSONObject();}}
  JSONObject fields(Object... p){JSONObject o=new JSONObject();try{for(int i=0;i<p.length;i+=2)o.put((String)p[i],p[i+1]);}catch(Exception ignored){}return o;}
  Button button(String title,LinearLayout row,View.OnClickListener cb){Button b=new Button(this);b.setText(title);b.setAllCaps(false);b.setTextSize(14);b.setMinWidth(0);b.setMinimumWidth(0);row.addView(b,new LinearLayout.LayoutParams(0,dp(46),1));b.setOnClickListener(cb);return b;}
  @Override protected void attachBaseContext(Context base){super.attachBaseContext(new ProfileContext(base,Profiles.processSlot()));}
  @Override public void onCreate(Bundle state){super.onCreate(state);if(Build.VERSION.SDK_INT>=30)getWindow().setDecorFitsSystemWindows(false);
    prefs=getSharedPreferences("chat",MODE_PRIVATE);pageMode=prefs.getBoolean("pageMode",false);pending=object(prefs.getString("pending","{}"));if(pending.length()==0)pending=null;
    try{driver=asset("page-driver.js");}catch(Exception e){driver="";}
    conversation=prefs.getString("conversation","");session=ChatSession.get(this);entries=session.entries;conversations=new ConversationStore(this);seenConfirmation=session.confirmationVersion;seenWebConfirmation=session.webConfirmationVersion;
    LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setBackground(new DesignUi.Stars(this));DesignUi.chrome(this);
    ReferenceUi.insets(this,root);
    designChrome=new DesignChrome(this,root);
    modelTitle=label("ChatGPT",18,Ui.INK);exitIpLine=label("出口 IP：待核实",11,Ui.MUTED);exitIpLine.setVisibility(View.GONE);
    status=new TextView(this);status.setTextSize(12);status.setTextColor(Ui.MUTED);status.setPadding(dp(22),dp(4),dp(22),dp(8));status.setOnClickListener(v->{if(session.pending!=null)ReplyState.show(this);else if(session.offline||session.connecting||session.recoveryScheduled||!session.networkReady)NetworkStatusUi.show(this);else showPage(true);});status.setContentDescription("连接状态，点按查看网页");loading=new LoadingUi(this);
    webNotice=new TextView(this);webNotice.setText("网页会话  ·  点击返回聊天");webNotice.setTextSize(12);webNotice.setTextColor(Ui.MUTED);webNotice.setPadding(dp(22),dp(8),dp(22),dp(8));webNotice.setBackgroundColor(Ui.SOFT);webNotice.setVisibility(View.GONE);webNotice.setOnClickListener(v->showPage(false));
    FrameLayout stack=new FrameLayout(this);root.addView(stack,new LinearLayout.LayoutParams(-1,0,1));
    remote=session.web;if(remote.getParent() instanceof ViewGroup)((ViewGroup)remote.getParent()).removeView(remote);reader=new WebView(this);configure(reader);remote.setImportantForAccessibility(View.IMPORTANT_FOR_ACCESSIBILITY_NO_HIDE_DESCENDANTS);
    attachments=new Attachments(this);messageActions=new MessageActions(this);downloads=new FileDownloads(this);draftUi=new DraftUi(this);remote.setWebViewClient(remoteClient());remote.setWebChromeClient(attachments.chrome());
    reader.setWebViewClient(new WebViewClient(){
      @Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return true;}
      @Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){
        Uri u=r.getUrl();if(!"appassets.androidplatform.net".equals(u.getHost())||!"https".equals(u.getScheme()))return blocked();
        String path=u.getPath().substring(1);if(path.contains(".."))return blocked();
        try{String mime=path.endsWith(".js")?"application/javascript":path.endsWith(".css")?"text/css":path.endsWith(".woff2")?"font/woff2":path.endsWith(".woff")?"font/woff":path.endsWith(".ttf")?"font/ttf":"text/html";return new WebResourceResponse(mime,"UTF-8",getAssets().open(path));}catch(Exception e){return blocked();}
      }
      @Override public void onPageFinished(WebView v,String url){readerReady=true;render(false);}
    });
    stack.addView(remote,new FrameLayout.LayoutParams(-1,-1));stack.addView(reader,new FrameLayout.LayoutParams(-1,-1));stack.addView(loading.cover,new FrameLayout.LayoutParams(-1,-1));
    composer=new LinearLayout(this);composer.setOrientation(1);composer.setPadding(dp(16),dp(8),dp(16),dp(3));composer.setBackgroundColor(Ui.PAPER);composer.addView(status);composer.addView(loading.band);
    LinearLayout card=new LinearLayout(this);card.setOrientation(1);android.graphics.drawable.GradientDrawable cardBackground=Ui.shape(this,Ui.SOFT,18);cardBackground.setStroke(Math.max(1,dp(1)/2),0xff214666);card.setBackground(cardBackground);card.setPadding(dp(8),dp(5),dp(8),dp(8));card.setElevation(dp(2));composer.addView(card,new LinearLayout.LayoutParams(-1,-2));card.addView(attachments.view,new LinearLayout.LayoutParams(-1,dp(88)));
    input=new EditText(this);input.setTextSize(16);input.setTextColor(Ui.INK);input.setHintTextColor(0xff777777);input.setHint("询问任何问题");input.setBackgroundColor(Color.TRANSPARENT);input.setPadding(dp(7),dp(6),dp(7),dp(4));input.setMinHeight(dp(38));input.setIncludeFontPadding(false);input.setGravity(Gravity.TOP|Gravity.START);if(Build.VERSION.SDK_INT>=28)input.setLineHeight(dp(26));input.setMinLines(1);input.setMaxLines(6);input.setInputType(131073);input.setText(AppPrefs.enabled(this,"saveDraft")?prefs.getString("draft",""):"");input.setContentDescription("消息输入框");card.addView(input,new LinearLayout.LayoutParams(-1,-2));
    input.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int a,int b,int c){if(AppPrefs.enabled(MainActivity.this,"saveDraft"))prefs.edit().putString("draft",s.toString()).apply();if(attachments!=null)attachments.render();}public void afterTextChanged(Editable e){}});
    LinearLayout tools=new LinearLayout(this);tools.setGravity(Gravity.CENTER_VERTICAL);tools.setPadding(0,0,0,0);Ui.IconButton plus=new Ui.IconButton(this,"plus","添加内容",false);tools.addView(plus,new LinearLayout.LayoutParams(dp(36),dp(36)));plus.setOnClickListener(v->addSheet());
    effortChip=new TextView(this);effortChip.setText("选择模型 ⌄");effortChip.setTextSize(13);effortChip.setIncludeFontPadding(false);effortChip.setTextColor(Ui.MUTED);effortChip.setGravity(Gravity.CENTER_VERTICAL);effortChip.setPadding(dp(7),0,dp(9),0);effortChip.setBackground(Ui.ripple(this,Color.TRANSPARENT,18));tools.addView(effortChip,new LinearLayout.LayoutParams(-2,dp(36)));effortChip.setOnClickListener(v->modelSheet());View spacer=new View(this);tools.addView(spacer,new LinearLayout.LayoutParams(0,1,1));
    send=new Ui.IconButton(this,"arrow","发送消息",true);send.setOnClickListener(v->sendPrompt());LinearLayout.LayoutParams sendLayout=new LinearLayout.LayoutParams(dp(36),dp(36));sendLayout.setMargins(dp(5),0,0,0);tools.addView(send,sendLayout);card.addView(tools);
    TextView footnote=new TextView(this);footnote.setText("ChatGPT 也可能会犯错，请核查重要信息。");footnote.setTextSize(10);footnote.setTextColor(0xff969696);footnote.setGravity(Gravity.CENTER);footnote.setIncludeFontPadding(false);footnote.setPadding(0,dp(8),0,dp(3));composer.addView(footnote);root.addView(composer);setContentView(root);hub=new AppHub(this,root,stack);
    session.add(sessionObserver);startNetwork();
    showPage(prefs.getBoolean("pageMode",false));status(pending==null?"准备连接 · 首次使用请登录网页版":"上次发送状态待确认 · 不会自动重发");openNotification(getIntent());
  }
  void configure(WebView v){WebSettings s=v.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);s.setSupportMultipleWindows(false);s.setJavaScriptCanOpenWindowsAutomatically(false);s.setMediaPlaybackRequiresUserGesture(true);s.setSafeBrowsingEnabled(true);CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(v,false);}
  static WebResourceResponse blocked(){return new WebResourceResponse("text/plain","UTF-8",new ByteArrayInputStream(new byte[0]));}
  static boolean validProxy(String value){try{Uri u=Uri.parse(value);return Arrays.asList("http","https","socks").contains(u.getScheme())&&u.getHost()!=null&&u.getPort()>0&&u.getPort()<65536&&u.getUserInfo()==null&&(u.getPath()==null||u.getPath().isEmpty())&&u.getQuery()==null&&u.getFragment()==null;}catch(Exception e){return false;}}
  void startNetwork(){session.connect();if(!prefs.getBoolean("networkConfigured",false)&&!getIntent().getBooleanExtra("openEnvironmentEditor",false)&&(!getIntent().hasExtra("openWindowAction")||"chat".equals(getIntent().getStringExtra("openWindowAction"))))handler.postDelayed(()->networkSettings(),350);}
  void networkSettings(){FeatureDialogs.network(this);}
  void externalNetworkSettings(){
    if(DesignNetworkUi.busy(this)){status("请等待当前操作完成，再修改网络。");return;}
    LinearLayout box=DesignUi.column(this);box.setPadding(dp(18),dp(8),dp(18),dp(16));
    DesignUi.note(box,Profiles.display(this,Profiles.slot(this))+" · 使用已配置好完整链路的应用代理。");
    String saved=prefs.getString("proxy","");
    EditText proxy=DesignUi.input(box,"代理地址",saved,"http://主机:端口 或 socks://主机:端口");proxy.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_URI);
    DesignUi.note(box,"本机代理可填写 http://127.0.0.1:7890，其中 127.0.0.1 指这部手机。保存后会重新连接此环境。");
    TextView notice=DesignUi.text(this,"",13,DesignUi.RED);notice.setAccessibilityLiveRegion(View.ACCESSIBILITY_LIVE_REGION_POLITE);box.addView(notice);
    ScrollView scroll=new ScrollView(this);scroll.addView(box);
    AlertDialog dialog=new AlertDialog.Builder(this).setTitle("应用专用代理").setView(scroll).setPositiveButton("保存并连接",null).setNegativeButton("取消",null).create();
    dialog.show();DesignUi.protectEdits(this,dialog,()->!saved.equals(proxy.getText().toString()));
    dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{
      if(DesignNetworkUi.busy(this)){notice.setText("当前操作还未完成，请稍后再保存。");return;}
      String value=proxy.getText().toString().trim();
      if(!validProxy(value)){proxy.setError("填写 http(s)://主机:端口 或 socks://主机:端口，且不含账号密码或路径");proxy.requestFocus();return;}
      prefs.edit().putBoolean("networkConfigured",true).putString("proxy",value).putString("networkMode","external").commit();dialog.dismiss();session.reconnect();
    });
  }
  static boolean chatUrl(String url){try{Uri u=Uri.parse(url);return "https".equals(u.getScheme())&&"chatgpt.com".equals(u.getHost())&&u.getUserInfo()==null&&(u.getPort()==-1||u.getPort()==443);}catch(Exception e){return false;}}
  WebViewClient remoteClient(){WebViewClient original=session.client();return new WebViewClient(){@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){return original.shouldInterceptRequest(v,r);}@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){if(r.isForMainFrame()&&downloads!=null&&downloads.intercept(r.getUrl().toString()))return true;return original.shouldOverrideUrlLoading(v,r);}@Override public void onPageStarted(WebView v,String u,android.graphics.Bitmap i){original.onPageStarted(v,u,i);}@Override public void onPageCommitVisible(WebView v,String u){original.onPageCommitVisible(v,u);}@Override public void onPageFinished(WebView v,String u){original.onPageFinished(v,u);}@Override public void onReceivedError(WebView v,WebResourceRequest r,WebResourceError e){original.onReceivedError(v,r,e);}@Override public void onReceivedHttpError(WebView v,WebResourceRequest r,WebResourceResponse response){original.onReceivedHttpError(v,r,response);}};}
  TextView modeTab(String text,String description,Runnable action){TextView tab=label(text,13,Ui.INK);tab.setGravity(Gravity.CENTER);tab.setIncludeFontPadding(false);tab.setContentDescription(description);tab.setOnClickListener(v->action.run());return tab;}
  void ensureReader(){if(readerLoaded)return;readerLoaded=true;reader.loadUrl(LOCAL+"index.html");}
  void showPage(boolean show){if(hub!=null&&hub.page!=0)hub.show(0);boolean preserveWebFocus=show&&pageMode&&reader.getVisibility()==View.GONE;pageMode=show;prefs.edit().putBoolean("pageMode",show).apply();remote.setImportantForAccessibility(show?View.IMPORTANT_FOR_ACCESSIBILITY_AUTO:View.IMPORTANT_FOR_ACCESSIBILITY_NO_HIDE_DESCENDANTS);reader.setVisibility(show?View.GONE:View.VISIBLE);composer.setVisibility(show?View.GONE:View.VISIBLE);webNotice.setVisibility(View.GONE);nativeTab.setSelected(!show);webTab.setSelected(show);nativeTab.setBackground(show?Ui.shape(this,Ui.SOFT,8):DesignUi.gradient(this));webTab.setBackground(show?DesignUi.gradient(this):Ui.shape(this,Ui.SOFT,8));nativeTab.setTextColor(show?Ui.MUTED:android.graphics.Color.WHITE);webTab.setTextColor(show?android.graphics.Color.WHITE:Ui.MUTED);loading.update();if(show&&!preserveWebFocus){input.clearFocus();reader.clearFocus();remote.requestFocus();}else if(!show){remote.clearFocus();reader.requestFocus();}if(!preserveWebFocus)((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(input.getWindowToken(),0);if(show){reader.onPause();requestWebNotifications();}else{reader.onResume();session.webStore.loadIfNeeded();ensureReader();applySession();}if(designChrome!=null)designChrome.update();session.wakePolling();}
  void requestWebNotifications(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=android.content.pm.PackageManager.PERMISSION_GRANTED&&!prefs.getBoolean("webNotificationAsked",false)){prefs.edit().putBoolean("webNotificationAsked",true).apply();requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},91);}}
  void runDriver(String action,JSONObject args,Result cb){session.runDriver(action,args,r->cb.accept(r));}
  void sendPrompt(){if(!attachments.beforeSend())return;if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=android.content.pm.PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},91);session.submit(input.getText().toString());}
  final Runnable ticker=new Runnable(){public void run(){if(!active||destroyed)return;if(!pageMode)localActions();attachments.refresh();NetworkMetricsUi.update(MainActivity.this);handler.postDelayed(this,1200);}};
  void sync(){session.sync();}
  void applySession(){if(input==null||destroyed)return;LoginHelpUi.maybeShow(this);pending=session.pending;networkReady=session.networkReady;submitting=session.submitting;JSONObject state=session.state;if(state.optBoolean("modelKnown")){currentModel=state.optString("model");currentEffort=state.optString("effort");String text=currentEffort.isEmpty()?currentModel:currentEffort;effortChip.setText((text.equalsIgnoreCase("Extra High")?"极高":text)+" ⌄");}
    if(seenWebConfirmation!=session.webConfirmationVersion){seenWebConfirmation=session.webConfirmationVersion;attachments.sent();}
    if(seenConfirmation!=session.confirmationVersion){seenConfirmation=session.confirmationVersion;attachments.sent();if(input.getText().toString().equals(session.confirmedPrompt))input.setText("");}
    if(pageMode){entries=session.entries;conversation=session.conversation;readerDirty=true;send.setEnabled(networkReady&&!session.offline&&pending==null&&!submitting&&!session.operation&&!session.navigating&&!session.navigationFailed);if(!session.status.equals(lastUiStatus))status(session.status);NetworkMetricsUi.update(this);return;}
    String bubble=state.optString("userBubbleColor");if(bubble.matches("rgba?\\([0-9., %]+\\)")&&!bubble.equals(lastBubbleColor)){lastBubbleColor=bubble;prefs.edit().putString("webBubbleColor",bubble).apply();if(readerReady)reader.evaluateJavascript("window.chat&&window.chat.appearance("+JSONObject.quote(bubble)+")",null);}String serial=session.entries.toString();if(readerDirty||!serial.equals(lastTranscript)||!conversation.equals(session.conversation)||seenDelivery!=session.deliveries.revision){seenDelivery=session.deliveries.revision;entries=session.entries;conversation=session.conversation;lastTranscript=serial;conversations.saveMessages(conversation,entries);render(false);}send.setEnabled(networkReady&&!session.offline&&pending==null&&!submitting&&!session.operation&&!session.navigating&&!session.navigationFailed);input.setEnabled(true);if(!pageMode){modelTitle.setText(entries.length()==0?"ChatGPT":"");modelTitle.setEnabled(entries.length()==0);}status(session.status);ExitIpUi.update(this);NetworkMetricsUi.update(this);loading.update();attachments.render();if(draftUi!=null)draftUi.update();if(designChrome!=null)designChrome.update();
  }
  void render(boolean bottom){if(pageMode||!readerReady){readerDirty=true;return;}readerDirty=false;rememberConversation();if(readerReady){WebPerfStats.reader();reader.evaluateJavascript("window.chat&&window.chat.receive("+fields("type","messages","conversation",conversation,"entries",session.deliveries.decorate(conversation,entries,session.activeDeliveryId),"forceBottom",bottom,"bubbleColor",prefs.getString("webBubbleColor","rgb(232, 243, 254)"))+")",null);}}
  void newChat(){if(!attachments.allowNavigation(()->newChat()))return;if(pending!=null||submitting||session.operation){status("请先完成当前任务");return;}session.activeDeliveryId="";session.deliveries.revision++;if(AppPrefs.enabled(this,"saveDraft"))conversations.draft(conversation,input.getText().toString());input.setText("");if(drawer!=null)drawer.dismiss();session.navigate(ORIGIN,"正在准备新对话…");showPage(prefs.getBoolean("pageMode",false));}
  TextView label(String text,int size,int color){TextView v=new TextView(this);v.setText(text);v.setTextSize(size);v.setTextColor(color);return v;}
  LinearLayout sheetRow(String glyph,String text,Runnable action){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(14),dp(4),dp(14),dp(4));row.setBackground(Ui.ripple(this,Color.TRANSPARENT,14));if(!glyph.isEmpty()){android.widget.ImageView icon=new android.widget.ImageView(this);icon.setImageDrawable(new Ui.Icon(glyph,Ui.INK));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(22),dp(22));p.rightMargin=dp(16);row.addView(icon,p);}TextView title=label(text,16,Ui.INK);title.setGravity(Gravity.CENTER_VERTICAL);title.setSingleLine(true);title.setEllipsize(TextUtils.TruncateAt.END);row.addView(title,new LinearLayout.LayoutParams(0,dp(48),1));row.setOnClickListener(v->action.run());row.setContentDescription(text);return row;}
  void sheet(String title,String[] glyphs,String[] rows,Runnable[] actions){((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(input.getWindowToken(),0);Dialog dialog=new Dialog(this);LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(dp(12),dp(10),dp(12),dp(18));box.setBackground(Ui.shape(this,Ui.SOFT,24));View handle=new View(this);handle.setBackground(Ui.shape(this,0xffdddddd,3));LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(dp(34),dp(4));hp.gravity=Gravity.CENTER;hp.bottomMargin=dp(16);box.addView(handle,hp);TextView heading=label(title,18,Ui.INK);heading.setTypeface(android.graphics.Typeface.create("sans-serif-medium",0));heading.setPadding(dp(14),0,dp(14),dp(14));box.addView(heading);LinearLayout options=new LinearLayout(this);options.setOrientation(1);for(int i=0;i<rows.length;i++){final int n=i;options.addView(sheetRow(glyphs[i],rows[i],()->{dialog.dismiss();actions[n].run();}));}ScrollView scroller=new ScrollView(this);scroller.setFillViewport(false);scroller.addView(options);int cap=(int)(getResources().getDisplayMetrics().heightPixels*.68);box.addView(scroller,new LinearLayout.LayoutParams(-1,Math.min(rows.length*dp(56),cap)));dialog.setContentView(box);Window w=dialog.getWindow();w.setBackgroundDrawableResource(android.R.color.transparent);w.setDimAmount(.25f);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);w.setGravity(Gravity.BOTTOM);w.setLayout(-1,-2);dialog.show();w.setLayout(-1,-2);}
  void moreSheet(){
    String[] rows={"新对话","刷新网页","在当前对话中搜索","下载管理","发送记录","恢复暂存草稿","加载更早的消息",pageMode?"切换到简洁":"切换到原网页","环境与设置"};
    Runnable[] actions={()->newChat(),()->session.retryCurrent(),()->searchConversation(),()->hub.select(1),()->DeliveryUi.list(this),()->messageActions.restoreDraft(),()->loadOlder(),()->showPage(!pageMode),()->menu()};
    ReferenceUi.Modal d=new ReferenceUi.Modal(this,"会话选项");if(LoginPagePolicy.google(remote.getUrl()))d.body.addView(ReferenceUi.link(this,"登录帮助",()->{d.dismiss();LoginHelpUi.show(this);}),new LinearLayout.LayoutParams(-1,dp(48)));for(int i=0;i<rows.length;i++){final int n=i;Button b=ReferenceUi.link(this,rows[i],()->{d.dismiss();actions[n].run();});b.setTextColor(ReferenceUi.TEXT);b.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);d.body.addView(b,new LinearLayout.LayoutParams(-1,dp(48)));}d.show();
  }
  void searchConversation(){showPage(false);EditText query=new EditText(this);query.setSingleLine(true);query.setHint("搜索已加载的全部消息");TextView count=label("按消息显示搜索结果",13,Ui.MUTED);LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(dp(20),dp(12),dp(20),0);box.addView(query);box.addView(count);long[] serial={0};java.util.function.IntConsumer find=step->{long request=++serial[0];reader.evaluateJavascript("JSON.stringify(window.chat.search("+JSONObject.quote(query.getText().toString())+","+step+"))",raw->{if(request!=serial[0])return;try{JSONObject result=new JSONObject((String)new JSONTokener(raw).nextValue());int total=result.optInt("total");count.setText(total==0?"没有匹配（仅搜索已加载内容）":"第 "+result.optInt("index")+" / "+total+" 条匹配消息");}catch(Exception ignored){count.setText("搜索暂不可用");}});};AlertDialog d=new AlertDialog.Builder(this).setTitle("对话内搜索").setView(box).setPositiveButton("下一条",null).setNeutralButton("上一条",null).setNegativeButton("关闭",null).create();query.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void afterTextChanged(Editable e){}public void onTextChanged(CharSequence s,int a,int b,int c){find.accept(0);}});d.setOnShowListener(v->{d.getButton(-1).setOnClickListener(w->find.accept(1));d.getButton(-3).setOnClickListener(w->find.accept(-1));});d.setOnDismissListener(v->{serial[0]++;reader.evaluateJavascript("window.chat.endSearch()",null);});d.show();d.getWindow().setDimAmount(0);d.getWindow().setGravity(Gravity.TOP);}
  void loadOlder(){if(session.offline){status("当前离线，已显示本地保存的消息");return;}session.asyncDriver("history-older",new JSONObject(),12000,r->{status(r.optString("reason","已检查更早的消息"));session.sync();});}
  void addSheet(){sheet("添加内容",new String[]{"image","file","clipboard"},new String[]{"选择图片","上传 PDF / 文件","粘贴剪贴板文字"},new Runnable[]{()->attachments.open("image"),()->attachments.open("file"),()->{android.content.ClipboardManager c=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(c.hasPrimaryClip()&&c.getPrimaryClip().getItemCount()>0){CharSequence value=c.getPrimaryClip().getItemAt(0).coerceToText(this);int pos=Math.max(0,input.getSelectionStart());input.getText().insert(pos,value);input.requestFocus();}}});}
  void modelSheet(){FeatureDialogs.models(this);}
  void openModel(){FeatureDialogs.models(this);}
  @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==74)attachments.result(result,data);if(request==FileDownloads.SAVE)downloads.result(result,data);if(request==SavedFileActions.EXPORT)downloads.savedActions.result(result,data);}
  JSONArray recentChats(){JSONArray list=conversations.list();if(!prefs.getBoolean("historyMigrated",false)){try{conversations.merge(new JSONArray(prefs.getString("recentChats","[]")),false);list=conversations.list();prefs.edit().putBoolean("historyMigrated",true).apply();}catch(Exception ignored){}}return list;}
  void mergeChats(JSONArray incoming){conversations.merge(incoming,false);}
  void rememberConversation(){if(conversations!=null)conversations.saveMessages(conversation,entries);}
  void switchConversation(String url){if(!attachments.allowNavigation(()->switchConversation(url)))return;if(pending!=null||submitting||session.operation){status("请先完成当前任务");return;}if(AppPrefs.enabled(this,"saveDraft"))conversations.draft(conversation,input.getText().toString());input.setText(AppPrefs.enabled(this,"saveDraft")?conversations.draft(url):"");if(drawer!=null)drawer.dismiss();session.navigate(url,"正在打开对话…");showPage(prefs.getBoolean("pageMode",false));}
  LinearLayout drawerRow(String glyph,String text,Runnable action){LinearLayout row=sheetRow(glyph,text,action);TextView label=(TextView)row.getChildAt(row.getChildCount()-1);label.setTextSize(14);label.getLayoutParams().height=dp(36);row.setPadding(dp(12),0,dp(12),0);if(row.getChildCount()>1&&row.getChildAt(0) instanceof ImageView){row.getChildAt(0).getLayoutParams().width=dp(20);row.getChildAt(0).getLayoutParams().height=dp(20);}return row;}
  void showDrawer(){
    drawer=new Dialog(this);LinearLayout panel=new LinearLayout(this);panel.setOrientation(1);panel.setPadding(dp(10),dp(10),dp(10),dp(12));panel.setBackgroundColor(Ui.PAPER);
    LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);TextView name=label("ChatGPT",18,Ui.INK);name.setTypeface(android.graphics.Typeface.create("sans-serif-medium",0));name.setPadding(dp(12),0,0,0);bar.addView(name,new LinearLayout.LayoutParams(0,dp(48),1));Ui.IconButton close=new Ui.IconButton(this,"close","关闭会话列表",false);bar.addView(close,new LinearLayout.LayoutParams(dp(44),dp(44)));close.setOnClickListener(v->drawer.dismiss());panel.addView(bar);
    EditText search=new EditText(this);search.setSingleLine(true);search.setTextSize(14);search.setHint("搜索聊天");search.setIncludeFontPadding(false);search.setHintTextColor(0xff808080);search.setPadding(dp(16),0,dp(12),0);search.setBackground(Ui.shape(this,0xffeeeeee,12));LinearLayout.LayoutParams searchLayout=new LinearLayout.LayoutParams(-1,dp(40));searchLayout.setMargins(dp(5),dp(10),dp(5),dp(12));panel.addView(search,searchLayout);
    panel.addView(drawerRow("new","新对话",()->newChat()));TextView recent=label("最近聊天",12,Ui.MUTED);recent.setPadding(dp(12),dp(20),0,dp(6));panel.addView(recent);
    ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);LinearLayout chats=new LinearLayout(this);chats.setOrientation(1);scroll.addView(chats);panel.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
    Runnable refresh=()->{chats.removeAllViews();String query=search.getText().toString().trim().toLowerCase(Locale.ROOT);JSONArray list=recentChats();int count=0;for(int i=0;i<list.length();i++){JSONObject chat=list.optJSONObject(i);if(chat==null)continue;String title=chat.optString("title","未命名对话"),url=chat.optString("url");if(!title.toLowerCase(Locale.ROOT).contains(query))continue;LinearLayout row=drawerRow("",title,()->{if(pending!=null||submitting){Toast.makeText(this,"请先确认上次发送状态",Toast.LENGTH_SHORT).show();return;}switchConversation(url);});row.setOnLongClickListener(v->{FeatureDialogs.chatActions(this,chat,()->{if(drawer!=null)drawer.dismiss();showDrawer();});return true;});TextView rowTitle=(TextView)row.getChildAt(row.getChildCount()-1);rowTitle.setTextSize(14);rowTitle.setTypeface(android.graphics.Typeface.create("sans-serif",0));rowTitle.getLayoutParams().height=dp(36);row.setPadding(dp(12),0,dp(12),0);if(url.equals(conversation))row.setBackground(Ui.ripple(this,0xffe9e9e9,12));chats.addView(row);count++;}if(count==0){TextView empty=label(query.isEmpty()?"这里会显示你最近打开的对话":"没有找到匹配的对话",14,Ui.MUTED);empty.setPadding(dp(14),dp(14),dp(14),0);chats.addView(empty);}};
    search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int a,int b,int c){refresh.run();}public void afterTextChanged(Editable e){}});refresh.run();panel.addView(drawerRow("chat","同步全部历史",()->FeatureDialogs.syncHistory(this,refresh)),3);
    panel.addView(drawerRow("chat","网页历史",()->{drawer.dismiss();showPage(true);if(chatUrl(remote.getUrl()))remote.evaluateJavascript("(()=>{const b=[...document.querySelectorAll('button')].find(x=>/^(Open sidebar|打开边栏|打开侧边栏)$/.test(x.getAttribute('aria-label')||''));if(b)b.click()})()",null);}));
    View divider=new View(this);divider.setBackgroundColor(0xffeeeeee);panel.addView(divider,new LinearLayout.LayoutParams(-1,dp(1)));panel.addView(drawerRow("settings","设置",()->{drawer.dismiss();menu();}));TextView account=label("元婴期院士 · "+Profiles.display(this,Profiles.slot(this)),12,Ui.MUTED);account.setPadding(dp(14),0,0,dp(8));panel.addView(account);
    drawer.setContentView(panel);Window w=drawer.getWindow();w.setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(Ui.PAPER));w.setDimAmount(.25f);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);w.setGravity(Gravity.LEFT|Gravity.TOP);w.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE|WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN);drawer.show();w.setLayout(Math.min(dp(260),(int)(getResources().getDisplayMetrics().widthPixels*.88)),-1);
    if(AppPrefs.enabled(this,"autoHistory"))runDriver("chats",new JSONObject(),result->{JSONArray remoteChats=result.optJSONArray("chats");if(remoteChats!=null&&remoteChats.length()>0){mergeChats(remoteChats);if(drawer.isShowing())refresh.run();}});
  }
  void localActions(){if(!readerReady)return;reader.evaluateJavascript("JSON.stringify((window.pocketActions||[]).splice(0,20))",raw->{try{String s=(String)new JSONTokener(raw).nextValue();JSONArray a=new JSONArray(s);for(int i=0;i<a.length();i++){JSONObject item=a.getJSONObject(i);String action=item.optString("action"),text=item.optString("text");if(item.has("conversation")&&!conversation.equals(item.optString("conversation")))continue;if(action.equals("delivery-action")||(action.equals("message-menu")&&item.optString("id").startsWith("local:"))){DeliveryUi.show(this,item.optString("id").replaceFirst("^local:",""));continue;}if(action.equals("edit-message")){JSONObject e=messageActions.entry(item.optString("id"));if(e!=null)messageActions.edit(e);continue;}if(action.equals("regenerate-message")){messageActions.regenerate(item.optString("id"));continue;}if(action.equals("message-menu")){messageActions.menu(item.optString("id"));continue;}if(action.equals("download-file")){downloads.open(item.optString("id"),text);continue;}if(action.equals("older")){loadOlder();continue;}if(action.equals("preview")){attachments.preview(item.optString("id"),text);continue;}if(action.equals("open-link")){String link=text;new AlertDialog.Builder(this).setMessage(link).setPositiveButton("用浏览器打开",(d,w)->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(link)));}catch(Exception ignored){}}).setNegativeButton("取消",null).show();continue;}if(text.isEmpty())for(int j=0;j<entries.length();j++)if(entries.getJSONObject(j).optString("id").equals(item.optString("id")))text=entries.getJSONObject(j).optString("text");if(action.equals("export-message")){Intent share=new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,text);startActivity(Intent.createChooser(share,"分享回复"));}else{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("回复",text));Toast.makeText(this,"已复制",Toast.LENGTH_SHORT).show();}}}catch(Exception ignored){}});}
  void menu(){
    String[] choices={"编辑当前环境","当前环境网络","环境自检","管理全部环境","应用设置","重新加载网页","确认上次发送状态"};
    new AlertDialog.Builder(this).setTitle("环境 · "+Profiles.display(this,Profiles.slot(this))).setItems(choices,(d,n)->{
      if(n==0)EnvironmentEditorUi.show(this);if(n==1)hub.select(4);if(n==2)EnvironmentAuditUi.show(this);if(n==3)ProfileUi.show(this);if(n==4)hub.select(3);if(n==5)session.retryCurrent();
      if(n==6){showPage(true);new AlertDialog.Builder(this).setMessage("先查看网页确认上次提问是否已经发送。解除等待不会重发，草稿会保留。").setPositiveButton("已核对，解除等待",(x,y)->session.abandonWait()).setNegativeButton("继续等待",null).show();}
    }).setNegativeButton("关闭",null).show();
  }
  void openNotification(Intent intent){if(intent==null)return;String windowAction=intent.getStringExtra("openWindowAction");if(windowAction!=null){intent.removeExtra("openWindowAction");if(intent.getBooleanExtra("forceWebMode",false)){intent.removeExtra("forceWebMode");showPage(true);}if(hub!=null){hub.show("settings".equals(windowAction)?3:"network".equals(windowAction)?4:0);if("network".equals(windowAction))hub.network();}if("edit".equals(windowAction))handler.postDelayed(()->EnvironmentEditorUi.show(this),200);}if(intent.getBooleanExtra("openEnvironmentEditor",false)){intent.removeExtra("openEnvironmentEditor");handler.postDelayed(()->EnvironmentEditorUi.show(this),200);}String download=intent.getStringExtra("openDownload");if(download!=null){intent.removeExtra("openDownload");if(hub!=null)hub.select(1);for(int i=0;i<downloads.tasks.rows.length();i++){JSONObject row=downloads.tasks.rows.optJSONObject(i);if(download.equals(row.optString("id"))){downloads.taskActions(row);break;}}return;}String url=intent.getStringExtra("openConversation");if(!chatUrl(url))return;intent.removeExtra("openConversation");if(hub!=null)hub.select(0);
    if(session.pending!=null||session.submitting||session.operation){status("当前有未完成请求，请先完成等待再打开其他对话");return;}
    if(session.networkReady){if(WebReplyObserver.same(url,remote.getUrl())&&!session.navigationFailed){session.sync();showPage(prefs.getBoolean("pageMode",false));}else switchConversation(url);}
    else{session.requestedConversation=url;session.conversation=url;conversation=url;session.connect();}
  }
  @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);openNotification(intent);}
  @Override protected void onResume(){super.onResume();active=true;AppPrefs.maintainCache(this);if(session!=null){session.add(sessionObserver);session.audit.refresh(true);session.foreground(true);session.connect();}if(hub!=null&&hub.page!=0){hub.refresh();handler.removeCallbacks(hub.tick);handler.postDelayed(hub.tick,2500);}handler.removeCallbacks(ticker);handler.post(ticker);}
  @Override protected void onPause(){super.onPause();if(conversations!=null&&input!=null)if(AppPrefs.enabled(this,"saveDraft"))conversations.draft(conversation,input.getText().toString());active=false;NativeNetwork.get(this).traffic.watch(false);handler.removeCallbacks(ticker);CookieManager.getInstance().flush();if(session!=null){session.remove(sessionObserver);session.audit.cancel();session.foreground(false);}}
  @Override protected void onDestroy(){destroyed=true;if(networkDialog!=null)networkDialog.dismiss();if(draftUi!=null)draftUi.destroy();if(downloads!=null)downloads.destroy();if(attachments!=null)attachments.destroy();if(loading!=null)loading.dismissTask();if(hub!=null)hub.networkWorkspace.close();handler.removeCallbacksAndMessages(null);if(session!=null){session.remove(sessionObserver);session.operation=false;}if(remote!=null&&remote.getParent() instanceof ViewGroup)((ViewGroup)remote.getParent()).removeView(remote);if(reader!=null)reader.destroy();super.onDestroy();}
  @Override public void onBackPressed(){if(hub!=null&&hub.page!=0){hub.select(0);return;}if(session!=null&&session.pending!=null&&!pageMode){moveTaskToBack(true);return;}if(pageMode){showPage(false);return;}super.onBackPressed();}
}
