package local.pocketchat;
import android.app.*;
import android.content.*;
import android.widget.*;
import org.json.*;
import java.util.*;

final class MessageActions {
  final MainActivity a;
  MessageActions(MainActivity a){this.a=a;}
  JSONObject entry(String id){for(int i=0;i<a.entries.length();i++){JSONObject e=a.entries.optJSONObject(i);if(e!=null&&id.equals(e.optString("id")))return e;}return null;}
  void menu(String id){JSONObject e=entry(id);if(e==null)return;boolean user="user".equals(e.optString("role"));String[] options={"复制文字","选择部分文字",user?"编辑后重新提问":"重新生成回复","分享文字"};new AlertDialog.Builder(a).setTitle(user?"这条提问":"这条回复").setItems(options,(d,n)->{if(n==0)((android.content.ClipboardManager)a.getSystemService(Context.CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("消息",e.optString("text")));if(n==1){TextView text=a.label(e.optString("text"),16,Ui.INK);text.setPadding(a.dp(22),a.dp(12),a.dp(22),a.dp(12));text.setTextIsSelectable(true);ScrollView scroll=new ScrollView(a);scroll.addView(text);new AlertDialog.Builder(a).setTitle("长按选择文字").setView(scroll).setPositiveButton("关闭",null).show();}if(n==2){if(user)edit(e);else regenerate(id);}if(n==3)a.startActivity(Intent.createChooser(new Intent(Intent.ACTION_SEND).setType("text/plain").putExtra(Intent.EXTRA_TEXT,e.optString("text")),"分享消息"));}).show();}
  void edit(JSONObject e){String old=a.input.getText().toString(),replacement=e.optString("text");Runnable fill=()->{if(!old.trim().isEmpty()&&!old.equals(replacement))a.prefs.edit().putString("draftBackup:"+a.conversation,old).apply();a.input.setText(replacement);a.input.setSelection(a.input.length());a.input.requestFocus();((android.view.inputmethod.InputMethodManager)a.getSystemService(Context.INPUT_METHOD_SERVICE)).showSoftInput(a.input,android.view.inputmethod.InputMethodManager.SHOW_IMPLICIT);a.status(e.optJSONArray("attachments")!=null&&e.optJSONArray("attachments").length()>0?"已放入输入框；原附件需重新选择，修改后点发送":"已放入输入框，修改后点发送；原消息保留");};if(!old.trim().isEmpty()&&!old.equals(replacement))new AlertDialog.Builder(a).setTitle("先保留当前草稿？").setMessage("当前草稿会保存，可从“更多选项”恢复。").setPositiveButton("保留并编辑",(d,w)->fill.run()).setNegativeButton("取消",null).show();else fill.run();}
  void restoreDraft(){DraftUi.restore(a);}
  void regenerate(String id){ChatSession s=a.session;if(s.pending!=null||s.submitting||s.operation||s.navigating||s.offline||!s.networkReady){a.status("请先完成当前任务并确认网络连接");return;}s.operation=true;s.changed();a.loading.task("正在准备重新生成…");long epoch=s.navigationEpoch;Runnable prepare=()->s.asyncDriver("message-regenerate-prepare",J.obj("id",id,"expectedUrl",a.conversation),4500,r->{if(epoch!=s.navigationEpoch){finish("对话已改变，未重新生成");return;}if(!r.optBoolean("ok")){finish(r.optString("reason","无法重新生成，请查看原网页"));return;}JSONObject job=J.obj("id",UUID.randomUUID().toString(),"kind","regenerate","confirmed",true,"prompt",r.optString("prompt"),"userKey",r.optString("userKey"),"expectedUrl",r.optString("url"),"confirmedUrl",r.optString("url"),"beforeReplyKey",r.optString("replyKey"),"beforeReplyText",r.optString("markdown"),"regenerationObserved",false,"startedAt",System.currentTimeMillis(),"export",true,"attempted",true);try{s.deliveries.begin(r.optString("url"),r.optString("prompt"),null,"regenerate",job.optString("id"));s.deliveries.update(job.optString("id"),"sending","正在请求重新生成",true,r.optString("userKey"),r.optString("url"));}catch(Exception e){finish("保存重新生成记录失败，未执行");return;}if(!a.prefs.edit().putString("pending",job.toString()).commit()){finish("保存请求记录失败，未重新生成");return;}s.activeDeliveryId=job.optString("id");s.pending=job;s.stableReply="";s.stableTicks=0;ChatService.begin(a);s.asyncDriver("message-regenerate-submit",J.obj("id",id,"token",r.optString("token"),"expectedUrl",r.optString("url")),3500,result->{if(s.pending!=job)return;if(!result.optBoolean("ok")&&result.optBoolean("notClicked")){s.delivery(job.optString("id"),"failed",result.optString("reason"),false,"","");s.pending=null;a.prefs.edit().remove("pending").apply();ChatService.end(a);finish(result.optString("reason","未执行重新生成"));}else finish(result.optBoolean("ok")?"重新生成已请求，正在确认…":"重新生成结果待确认 · 不会重复点击");});});if(s.internalNetwork())NativeNetwork.get(a).beforeSend((ok,msg)->{if(epoch!=s.navigationEpoch){finish("连接已改变，未重新生成");return;}if(ok)prepare.run();else finish(msg);});else prepare.run();}
  void finish(String message){a.loading.dismissTask();a.session.operation=false;a.session.setStatus(message);}
}
