package local.pocketchat;
import android.app.*;
import android.widget.*;
import android.view.*;
import java.text.SimpleDateFormat;
import java.util.*;

final class NetworkStatusUi {
  static void show(MainActivity a){ChatSession s=a.session;LinearLayout box=new LinearLayout(a);box.setOrientation(1);box.setPadding(a.dp(24),a.dp(8),a.dp(24),a.dp(12));TextView details=a.label("",15,Ui.INK);details.setLineSpacing(a.dp(6),1);box.addView(details);Button copy=new Button(a);copy.setText("复制耗时诊断");copy.setAllCaps(false);copy.setOnClickListener(v->{((android.content.ClipboardManager)a.getSystemService(android.content.Context.CLIPBOARD_SERVICE)).setPrimaryClip(android.content.ClipData.newPlainText("连接耗时",s.trace.copyText(a,GeckoWebView.active(a.remote))));Toast.makeText(a,"耗时诊断已复制",Toast.LENGTH_SHORT).show();});box.addView(copy);ScrollView scroll=new ScrollView(a);scroll.addView(box);AlertDialog dialog=new AlertDialog.Builder(a).setTitle("连接状态").setView(scroll).setPositiveButton("立即重连",(d,w)->s.reconnect()).setNeutralButton("网络设置",(d,w)->a.networkSettings()).setNegativeButton("关闭",null).create();Runnable update=new Runnable(){public void run(){if(!dialog.isShowing())return;String proxy="使用已配置的手机网络",verified="";if(s.internalNetwork()){NativeNetwork n=NativeNetwork.get(a);proxy=n.starting?"正在启动 / 核对":n.ready&&n.coreAlive()?"运行正常":"尚未连接";verified=n.lastVerified==0?"尚未核实":new SimpleDateFormat("HH:mm:ss",Locale.getDefault()).format(new Date(n.lastVerified));}details.setText(NetworkMetricsUi.line(s,NativeNetwork.get(a),System.currentTimeMillis(),android.os.SystemClock.elapsedRealtime())+"\n\n手机网络："+(s.offline?"已断开":"可用")+"\n应用代理："+proxy+"\n网页状态："+s.connectionStage+(verified.isEmpty()?"":"\n最近出口核实："+verified)+(s.networkIssue.isEmpty()?"":"\n\n"+s.networkIssue)+(s.entryTiming().isEmpty()?"":"\n\n"+s.entryTiming())+"\n\n"+s.trace.text()+"\n\n草稿和待确认发送会保留。重连只恢复连接，不会重复发送消息。");dialog.getButton(-1).setEnabled(!s.offline&&!s.connecting);a.handler.postDelayed(this,1000);}};dialog.setOnShowListener(d->update.run());dialog.setOnDismissListener(d->a.handler.removeCallbacks(update));dialog.show();}
}
