package local.pocketchat;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.*;import android.text.InputType;import android.view.*;import android.widget.*;
import org.json.*;import java.util.*;import java.util.concurrent.*;

/** Three native tabs over the existing per-window network implementation. */
final class NetworkWorkspaceUi {
  final Activity a;final FrameLayout host;final Handler main=new Handler(Looper.getMainLooper());final ExecutorService reader=Executors.newSingleThreadExecutor();
  LinearLayout root,box,tabHost;ScrollView scroll;NetworkCatalog catalog;JSONArray windows=new JSONArray();int tab,filter,focus=-1;boolean focusPending,reading,closed;long lastRead;String lastRendered="";Runnable afterRead;
  NetworkWorkspaceUi(Activity a,FrameLayout host){this.a=a;this.host=host;}
  int dp(int n){return ReferenceUi.dp(a,n);}
  void show(int requested){tab=Math.max(0,Math.min(2,requested));if(root==null)layout();else{if(root.getParent()!=host){host.removeAllViews();host.addView(root,new FrameLayout.LayoutParams(-1,-1));}render();}fetch();}
  void layout(){lastRendered="";root=DesignUi.column(a);root.setBackgroundColor(ReferenceUi.BG);LinearLayout head=DesignUi.row(a);head.setPadding(dp(16),dp(5),dp(16),dp(5));head.addView(ReferenceUi.text(a,"网络",24,ReferenceUi.TEXT,true),new LinearLayout.LayoutParams(0,dp(48),1));Button refresh=ReferenceUi.button(a,"↻",false,()->{lastRead=0;fetch();});refresh.setTextSize(24);refresh.setContentDescription("刷新网络状态");head.addView(refresh,new LinearLayout.LayoutParams(dp(44),dp(44)));root.addView(head);
    tabHost=DesignUi.column(a);tabHost.setPadding(dp(16),0,dp(16),dp(10));root.addView(tabHost);scroll=new ScrollView(a);scroll.setFillViewport(false);box=DesignUi.column(a);box.setPadding(dp(16),0,dp(16),dp(14));scroll.addView(box);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));host.removeAllViews();host.addView(root,new FrameLayout.LayoutParams(-1,-1));render();}
  void select(int next){tab=next;if(a instanceof MainActivity)((MainActivity)a).hub.networkTab=next;filter=0;scroll.scrollTo(0,0);render();}
  void fetch(){if(closed||reading||SystemClock.elapsedRealtime()-lastRead<1800)return;reading=true;lastRead=SystemClock.elapsedRealtime();reader.execute(()->{NetworkCatalog next=new NetworkCatalog(a);JSONArray list=WindowNetworkState.windows(a);main.post(()->{reading=false;if(closed)return;catalog=next;windows=list;if(root!=null&&root.getParent()==host)render();if(afterRead!=null){Runnable done=afterRead;afterRead=null;done.run();}});});}
  void reload(){lastRead=0;fetch();}
  void close(){closed=true;reader.shutdownNow();main.removeCallbacksAndMessages(null);}
  WindowNetworkState state(JSONObject item){JSONObject runtime=item.optJSONObject("runtime");boolean live=item.optBoolean("live");if(a instanceof MainActivity){MainActivity chat=(MainActivity)a;if(chat.session!=null&&item.optJSONObject("row").optInt("slot")==Profiles.slot(a)){runtime=WindowNetworkState.live(chat.session,NativeNetwork.get(chat));live=true;}}return new WindowNetworkState(a,item.optJSONObject("row"),item.optJSONObject("config"),runtime,live,System.currentTimeMillis());}
  void render(){if(box==null)return;StringBuilder key=new StringBuilder(tab+"|"+filter+"|"+focus+"|");if(catalog!=null){key.append(catalog.data.toString());for(int i=0;i<windows.length();i++){WindowNetworkState s=state(windows.optJSONObject(i));key.append(s.name).append(s.state).append(s.mainline()).append(s.subline()).append(NativeNetwork.hash(s.config.toString()));}}if(key.toString().equals(lastRendered)&&!focusPending)return;lastRendered=key.toString();boolean locate=focusPending;int y=scroll.getScrollY();tabHost.removeAllViews();tabHost.addView(ReferenceUi.tabs(a,new String[]{"窗口网络","订阅","出口"},tab,this::select));box.removeAllViews();if(catalog==null){TextView t=ReferenceUi.text(a,"正在读取窗口网络…",13,ReferenceUi.MUTED,false);box.addView(t);return;}if(tab==0)renderWindows();else if(tab==1)renderSubscriptions();else renderExits();scroll.post(()->{if(!locate)scroll.scrollTo(0,y);});}
  void focus(int slot){focus=slot;focusPending=true;filter=0;tab=0;}
  void renderWindows(){
    LinearLayout summary=DesignUi.row(a);int count=0;for(int i=0;i<windows.length();i++)if(matches(state(windows.optJSONObject(i))))count++;summary.addView(ReferenceUi.text(a,count+" 个窗口",13,ReferenceUi.MUTED,false),new LinearLayout.LayoutParams(0,dp(38),1));Button f=ReferenceUi.link(a,filter==0?"筛选":"筛选 ·",this::filters);summary.addView(f,new LinearLayout.LayoutParams(dp(60),dp(48)));box.addView(summary);
    for(int i=0;i<windows.length();i++){JSONObject item=windows.optJSONObject(i);WindowNetworkState s=state(item);if(!matches(s))continue;LinearLayout card=ReferenceUi.card(a);LinearLayout head=DesignUi.row(a);TextView name=ReferenceUi.text(a,s.name,17,ReferenceUi.TEXT,true);ReferenceUi.single(name);head.addView(name,new LinearLayout.LayoutParams(0,-2,1));TextView status=ReferenceUi.text(a,"● "+s.state,11,s.color(),true);status.setPadding(dp(8),0,0,0);head.addView(status);card.addView(head);
      TextView line=ReferenceUi.text(a,s.mainline(),14,ReferenceUi.TEXT,true);line.setMaxLines(2);line.setPadding(0,dp(9),0,0);card.addView(line);card.addView(ReferenceUi.secondary(a,s.subline()));LinearLayout actions=DesignUi.row(a);actions.setPadding(0,dp(6),0,0);
      actions.addView(ReferenceUi.small(a,"编辑网络",true,()->edit(item)),new LinearLayout.LayoutParams(-2,dp(48)));Button measure=ReferenceUi.small(a,"测速",false,()->operate(s.slot,"measure"));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(48));p.leftMargin=dp(8);actions.addView(measure,p);actions.addView(new View(a),new LinearLayout.LayoutParams(0,1,1));actions.addView(ReferenceUi.more(a,()->more(item)),new LinearLayout.LayoutParams(dp(44),dp(48)));card.addView(actions);ReferenceUi.add(box,card);
      if(s.slot==focus){card.setBackground(ReferenceUi.surface(a,ReferenceUi.WHITE,16,0xff94b8ff));if(focusPending){focusPending=false;card.post(()->scroll.smoothScrollTo(0,card.getTop()));}}
    }
    if(count==0)empty("没有匹配的窗口",filter==0?"创建环境后会在这里显示网络。":"调整筛选即可查看其他窗口。");
  }
  boolean matches(WindowNetworkState s){return filter==0||filter==1&&s.connected||filter==2&&!s.connected;}
  void filters(){ReferenceUi.Modal d=new ReferenceUi.Modal(a,"筛选窗口");String[] choices={"全部窗口","已连接","待连接 / 未配置"};for(int i=0;i<choices.length;i++){final int n=i;choice(d,choices[i],"",filter==i,()->{filter=n;focus=-1;d.dismiss();scroll.scrollTo(0,0);render();});}d.show();}
  void empty(String title,String detail){LinearLayout c=ReferenceUi.card(a);c.addView(ReferenceUi.text(a,title,16,ReferenceUi.TEXT,true));c.addView(ReferenceUi.secondary(a,detail));ReferenceUi.add(box,c);}
  void listHeader(String name,Runnable add){LinearLayout head=DesignUi.row(a);head.addView(ReferenceUi.text(a,name,18,ReferenceUi.TEXT,true),new LinearLayout.LayoutParams(0,dp(48),1));head.addView(ReferenceUi.small(a,"＋ 添加",true,add),new LinearLayout.LayoutParams(-2,dp(48)));box.addView(head);}
  void renderSubscriptions(){listHeader("入口订阅",()->subscriptionForm(null));JSONArray all=catalog.subscriptions();for(int i=0;i<all.length();i++){JSONObject s=all.optJSONObject(i);int n=EntrySelection.strings(s.optJSONArray("nodes")).size();String state=s.optString("lastError").isEmpty()?n==0?"尚未读取":"正常":"更新失败";LinearLayout row=ReferenceUi.card(a);row.addView(ReferenceUi.text(a,s.optString("name"),16,ReferenceUi.TEXT,true));row.addView(ReferenceUi.secondary(a,state+" · "+n+" 个入口"));row.addView(ReferenceUi.secondary(a,"更新于 "+updated(s.optLong("updatedAt"))));row.setBackground(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(0x182468f2),ReferenceUi.surface(a,ReferenceUi.WHITE,15,ReferenceUi.LINE),null));row.setOnClickListener(v->subscriptionDetail(s));row.setContentDescription(s.optString("name")+"，查看订阅详情");ReferenceUi.add(box,row);}if(all.length()==0)empty("还没有入口订阅","添加已有的 Clash / Mihomo 订阅地址。");}
  void renderExits(){listHeader("固定出口",()->exitForm(null));JSONArray all=catalog.exits();for(int i=0;i<all.length();i++){JSONObject e=all.optJSONObject(i);LinearLayout row=ReferenceUi.card(a);row.addView(ReferenceUi.text(a,e.optString("name"),16,ReferenceUi.TEXT,true));row.addView(ReferenceUi.secondary(a,e.optString("verifiedIp").isEmpty()?"IP 待核验":e.optString("verifiedIp")));row.addView(ReferenceUi.secondary(a,(e.optString("verifiedIp").isEmpty()?"待核验":"上次已核验")+" · "+uses(e.optString("id"))+" 个窗口使用"));row.setOnClickListener(v->exitDetail(e));row.setBackground(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(0x182468f2),ReferenceUi.surface(a,ReferenceUi.WHITE,15,ReferenceUi.LINE),null));row.setContentDescription(e.optString("name")+"，查看固定出口详情");ReferenceUi.add(box,row);}if(all.length()==0)empty("还没有固定出口","添加已有的 SOCKS5 出口；每个窗口单独选择。");}
  int uses(String id){int n=0;for(int i=0;i<windows.length();i++){WindowNetworkState s=state(windows.optJSONObject(i));if(s.internal&&id.equals(NetworkCatalog.exitId(s.config)))n++;}return n;}
  String updated(long at){if(at<=0)return "未记录";Calendar now=Calendar.getInstance(),date=Calendar.getInstance();date.setTimeInMillis(at);boolean today=now.get(Calendar.YEAR)==date.get(Calendar.YEAR)&&now.get(Calendar.DAY_OF_YEAR)==date.get(Calendar.DAY_OF_YEAR);return new java.text.SimpleDateFormat(today?"'今天' HH:mm":"MM-dd HH:mm",Locale.getDefault()).format(new Date(at));}
  void more(JSONObject item){WindowNetworkState s=state(item);ReferenceUi.Modal d=new ReferenceUi.Modal(a,s.name);String[] labels={"窗口详情","重新连接","网络方式","打开会话"};Runnable[] actions={()->details(item),()->operate(s.slot,"reconnect"),()->networkMode(s.slot),()->openChat(s.slot)};for(int i=0;i<labels.length;i++){final int n=i;Button b=ReferenceUi.link(a,labels[i],()->{d.dismiss();actions[n].run();});b.setTextColor(ReferenceUi.TEXT);b.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);d.body.addView(b,new LinearLayout.LayoutParams(-1,dp(48)));}d.show();}
  void openChat(int slot){if(a instanceof MainActivity&&slot==Profiles.slot(a)){((MainActivity)a).hub.select(AppHub.CHAT);return;}a.startActivity(new Intent(a,Profiles.activity(slot)).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_REORDER_TO_FRONT));}
  void details(JSONObject item){WindowNetworkState s=state(item);ReferenceUi.Modal d=new ReferenceUi.Modal(a,"窗口详情 · "+s.name);field(d,"网络状态",s.state);field(d,"出口地区",s.region.isEmpty()?"未标注":s.region);field(d,"出口 IP",s.ip.isEmpty()?"未核验":s.ip);field(d,"完整线路延迟",s.latency);field(d,"入口订阅",s.subscription);if(s.internal){field(d,"入口选择",s.entryMode);field(d,"当前入口",s.entry.isEmpty()?"未选择":NativeNetwork.display(s.entry));field(d,"固定出口",s.config.optString("exitName",s.config.optString("exitHost")));field(d,"出口核验",updated(s.runtime.optLong("verifiedAt")));}if(!s.runtime.optString("issue").isEmpty())d.note(s.runtime.optString("issue"));d.buttons("关闭",d::dismiss,"编辑网络",()->{d.dismiss();edit(item);});d.show();}
  void field(ReferenceUi.Modal d,String name,String value){DesignUi.field(d.body,name,value);}
  void choice(ReferenceUi.Modal d,String name,String detail,boolean selected,Runnable run){LinearLayout row=DesignUi.row(a);row.setPadding(dp(12),dp(9),dp(12),dp(9));row.setMinimumHeight(dp(58));row.setBackground(ReferenceUi.surface(a,selected?0xfff7faff:ReferenceUi.WHITE,14,selected?0xff94b8ff:ReferenceUi.LINE));TextView mark=ReferenceUi.text(a,selected?"◉":"○",20,selected?ReferenceUi.BLUE:ReferenceUi.MUTED,false);row.addView(mark,new LinearLayout.LayoutParams(dp(30),-2));LinearLayout labels=DesignUi.column(a);TextView title=ReferenceUi.text(a,name,15,ReferenceUi.TEXT,true);ReferenceUi.single(title);labels.addView(title);if(!detail.isEmpty())labels.addView(ReferenceUi.secondary(a,detail));row.addView(labels,new LinearLayout.LayoutParams(0,-2,1));row.setOnClickListener(v->run.run());row.setFocusable(true);row.setContentDescription(name+(selected?"，已选择":""));ReferenceUi.add(d.body,row);}
  void routeRow(ReferenceUi.Modal d,String key,String value,Runnable select){LinearLayout row=DesignUi.row(a);row.setMinimumHeight(dp(66));LinearLayout labels=DesignUi.column(a);labels.addView(ReferenceUi.text(a,key,13,ReferenceUi.MUTED,false));TextView title=ReferenceUi.text(a,value,15,ReferenceUi.TEXT,true);ReferenceUi.single(title);title.setPadding(0,dp(4),0,0);labels.addView(title);row.addView(labels,new LinearLayout.LayoutParams(0,-2,1));row.addView(ReferenceUi.text(a,"›",22,ReferenceUi.MUTED,false));row.setOnClickListener(v->select.run());row.setFocusable(true);row.setBackground(Ui.ripple(a,Color.TRANSPARENT,0));d.body.addView(row);View line=new View(a);line.setBackgroundColor(0xffeef2f7);d.body.addView(line,new LinearLayout.LayoutParams(-1,dp(1)));}
  static final class EditorSession {final ReferenceUi.Modal dialog;final NetworkDraft draft;final Runnable refresh;EditorSession(ReferenceUi.Modal dialog,NetworkDraft draft,Runnable refresh){this.dialog=dialog;this.draft=draft;this.refresh=refresh;}}
  EditorSession edit(JSONObject item){if(catalog==null)return null;WindowNetworkState state=state(item);NetworkDraft draft=new NetworkDraft(state.slot,state.config,catalog);if(draft.entry.isEmpty()||draft.mode.equals("random")&&state.connected){JSONObject sub=catalog.subscription(draft.subscriptionId);if(sub!=null&&EntrySelection.strings(sub.optJSONArray("nodes")).contains(state.entry)&&(!draft.mode.equals("random")||draft.pool.contains(state.entry)))draft.entry=state.entry;}ReferenceUi.Modal d=new ReferenceUi.Modal(a,"编辑网络 · "+state.name);final Runnable[] render={null};final boolean[] saving={false};TextView error=ReferenceUi.text(a,"",12,ReferenceUi.RED,false);error.setAccessibilityLiveRegion(View.ACCESSIBILITY_LIVE_REGION_POLITE);
    render[0]=()->{d.body.removeAllViews();JSONObject s=catalog.subscription(draft.subscriptionId),e=catalog.exit(draft.exitId);routeRow(d,"入口订阅",s==null?"请选择订阅":s.optString("name"),()->selectSubscription(draft,render[0]));routeRow(d,"入口选择",(draft.mode.equals("manual")?"手动指定":"自动随机")+(draft.entry.isEmpty()?" · 待选择":" · "+NativeNetwork.display(draft.entry)),()->selectEntry(draft,render[0]));routeRow(d,"固定出口",e==null?"请选择固定出口":e.optString("name"),()->selectExit(draft,render[0]));d.body.addView(error);d.resize();};
    d.buttons("取消",d::dismiss,"保存并应用",()->{if(saving[0])return;JSONObject candidate;try{candidate=draft.candidate(catalog);}catch(Exception e){error.setText(e.getMessage());d.resize();return;}saving[0]=true;d.primary().setEnabled(false);d.primary().setText("正在应用…");((Button)d.footer.getChildAt(0)).setText("收起");for(int i=0;i<d.body.getChildCount();i++)d.body.getChildAt(i).setEnabled(false);error.setText("正在保存并应用，收起后操作仍会继续…");error.setTextColor(ReferenceUi.MUTED);d.resize();NetworkBridge.run(a,draft.slot,"apply",candidate,draft.baseline,(ok,message,snapshot)->{if(closed||a.isDestroyed())return;saving[0]=false;reload();if(ok){d.dismiss();Toast.makeText(a,message,Toast.LENGTH_SHORT).show();}else if(d.isShowing()){error.setText(message);error.setTextColor(ReferenceUi.RED);if(message.startsWith("配置已保存")){d.buttons("关闭",d::dismiss,"重新连接",()->{d.dismiss();operate(draft.slot,"reconnect");});}else{d.primary().setEnabled(true);d.primary().setText("保存并应用");((Button)d.footer.getChildAt(0)).setText("取消");for(int i=0;i<d.body.getChildCount();i++)d.body.getChildAt(i).setEnabled(true);}d.resize();}});});render[0].run();d.show();return new EditorSession(d,draft,render[0]);}
  ReferenceUi.Modal selectSubscription(NetworkDraft draft,Runnable changed){ReferenceUi.Modal d=new ReferenceUi.Modal(a,"选择入口订阅");for(int i=0;i<catalog.subscriptions().length();i++){JSONObject s=catalog.subscriptions().optJSONObject(i);choice(d,s.optString("name"),EntrySelection.strings(s.optJSONArray("nodes")).size()+" 个入口",s.optString("id").equals(draft.subscriptionId),()->{boolean different=!s.optString("id").equals(draft.subscriptionId);draft.subscription(s.optString("id"),catalog);if(EntrySelection.strings(s.optJSONArray("nodes")).isEmpty()){d.dismiss();loadPool(s,false,()->{draft.normalize(catalog);draft.pool.addAll(EntrySelection.strings(catalog.subscription(draft.subscriptionId).optJSONArray("nodes")));if(draft.mode.equals("random"))draft.randomize(new Random());changed.run();});}else{if(different){draft.pool.addAll(EntrySelection.strings(s.optJSONArray("nodes")));if(draft.mode.equals("random"))draft.randomize(new Random());}d.dismiss();changed.run();}});}if(catalog.subscriptions().length()==0)d.note("还没有订阅，添加已有订阅后即可选择入口。");d.buttons("取消",d::dismiss,"添加订阅",()->{d.dismiss();subscriptionForm(()->selectSubscription(draft,changed));});d.show();return d;}
  ReferenceUi.Modal selectExit(NetworkDraft draft,Runnable changed){ReferenceUi.Modal d=new ReferenceUi.Modal(a,"选择固定出口");for(int i=0;i<catalog.exits().length();i++){JSONObject e=catalog.exits().optJSONObject(i);choice(d,e.optString("name"),e.optString("verifiedIp","IP 待核验"),e.optString("id").equals(draft.exitId),()->{draft.exitId=e.optString("id");d.dismiss();changed.run();});}if(catalog.exits().length()==0)d.note("还没有固定出口，添加已有的 SOCKS5 出口后即可选择。");d.buttons("取消",d::dismiss,"添加出口",()->{d.dismiss();exitForm(()->selectExit(draft,changed));});d.show();return d;}
  ReferenceUi.Modal selectEntry(NetworkDraft draft,Runnable changed){JSONObject sub=catalog.subscription(draft.subscriptionId);if(sub==null)return ReferenceUi.message(a,"选择入口","请先选择入口订阅。");List<String> nodes=EntrySelection.strings(sub.optJSONArray("nodes"));if(nodes.isEmpty()){loadPool(sub,false,()->selectEntry(draft,changed));return null;}
    return new EntryPickerUi(a,draft,nodes,changed).show();}

  void loadPool(JSONObject subscription,boolean update,Runnable next){ReferenceUi.Modal d=new ReferenceUi.Modal(a,update?"更新订阅":"读取入口");LinearLayout progress=DesignUi.progress(a,"正在读取 "+subscription.optString("name"),"当前窗口继续使用原连接。");d.body.addView(progress);d.buttons("收起",d::dismiss,"",()->{});d.show();String id=subscription.optString("id");byte[] cache=update?null:catalog.cache(subscription);long stamp=subscription.optLong("updatedAt");NativeNetwork.previewSubscription(Profiles.context(a,Profiles.slot(a)),subscription.optString("url"),cache,(ok,message,nodes,bytes)->{if(closed||a.isDestroyed())return;if(ok){reader.execute(()->{try{NetworkCatalog fresh=new NetworkCatalog(a);fresh.parsed(id,nodes,bytes,cache==null?System.currentTimeMillis():stamp);main.post(()->{if(closed||a.isDestroyed())return;catalog=fresh;boolean advance=d.isShowing();d.dismiss();reload();if(next!=null&&advance)next.run();});}catch(Exception e){main.post(()->{if(!d.isShowing())return;d.body.removeAllViews();d.note("入口已解析，但缓存保存失败或订阅已更新，请重试。");d.buttons("关闭",d::dismiss,"重试",()->{d.dismiss();loadPool(subscription,update,next);});d.resize();});}});}else if(d.isShowing()){d.body.removeAllViews();d.note(message);d.buttons("关闭",d::dismiss,"重试",()->{d.dismiss();loadPool(subscription,update,next);});d.resize();}});}
  void subscriptionForm(Runnable next){ReferenceUi.Modal d=new ReferenceUi.Modal(a,"添加入口订阅");EditText name=DesignUi.input(d.body,"订阅名称","","例如：工作订阅"),url=DesignUi.input(d.body,"订阅地址","","HTTPS · Clash / Mihomo");url.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);TextView error=ReferenceUi.text(a,"",12,ReferenceUi.RED,false);d.body.addView(error);d.buttons("取消",d::dismiss,"保存订阅",()->{String title=name.getText().toString().trim();if(title.isEmpty()){name.setError("填写订阅名称");return;}try{NetworkCatalog fresh=new NetworkCatalog(a);JSONObject s=fresh.addSubscription(title,url.getText().toString().trim());catalog=fresh;d.dismiss();reload();loadPool(s,false,next);}catch(Exception e){error.setText(e.getMessage());d.resize();}});d.show();}
  void exitForm(Runnable next){ReferenceUi.Modal d=new ReferenceUi.Modal(a,"添加固定出口");EditText name=DesignUi.input(d.body,"出口名称","","例如：工作出口"),region=DesignUi.input(d.body,"地区（可选）","","填写你已知的出口地区"),host=DesignUi.input(d.body,"SOCKS5 服务器","","域名或 IP"),port=DesignUi.input(d.body,"端口","","1–65535"),user=DesignUi.input(d.body,"用户名（可选）","",""),password=DesignUi.input(d.body,"密码（可选）","","");port.setInputType(InputType.TYPE_CLASS_NUMBER);password.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);TextView error=ReferenceUi.text(a,"",12,ReferenceUi.RED,false);d.body.addView(error);d.buttons("取消",d::dismiss,"保存出口",()->{if(name.getText().toString().trim().isEmpty()){name.setError("填写出口名称");return;}try{int number=Integer.parseInt(port.getText().toString());NetworkCatalog fresh=new NetworkCatalog(a);fresh.addExit(name.getText().toString().trim(),region.getText().toString().trim(),host.getText().toString().trim(),number,user.getText().toString(),password.getText().toString());catalog=fresh;d.dismiss();reload();if(next!=null)next.run();}catch(Exception e){error.setText(e instanceof NumberFormatException?"端口应为 1–65535":e.getMessage());d.resize();}});d.show();}
  void subscriptionDetail(JSONObject s){ReferenceUi.Modal d=new ReferenceUi.Modal(a,"订阅详情");field(d,"名称",s.optString("name"));field(d,"入口数量",EntrySelection.strings(s.optJSONArray("nodes")).size()+" 个");field(d,"更新于",updated(s.optLong("updatedAt")));d.note("更新仅更新可选入口；已连接窗口在保存并应用后使用新配置。");d.buttons("关闭",d::dismiss,"更新订阅",()->{d.dismiss();loadPool(s,true,null);});d.show();}
  void exitDetail(JSONObject e){ReferenceUi.Modal d=new ReferenceUi.Modal(a,"出口详情");field(d,"名称",e.optString("name"));field(d,"地区",e.optString("region").isEmpty()?"未标注":e.optString("region"));field(d,"出口 IP",e.optString("verifiedIp").isEmpty()?"待核验":e.optString("verifiedIp"));field(d,"服务器",e.optString("host")+":"+e.optInt("port"));field(d,"使用窗口",uses(e.optString("id"))+" 个");d.buttons("关闭",d::dismiss,"核验出口",()->{List<Integer> owners=new ArrayList<>();for(int i=0;i<windows.length();i++){WindowNetworkState s=state(windows.optJSONObject(i));if(s.internal&&s.connected&&e.optString("id").equals(NetworkCatalog.exitId(s.config)))owners.add(s.slot);}if(owners.isEmpty()){d.note("此出口尚无已连接窗口。保存窗口配置并连接后即可核验。");d.resize();return;}d.dismiss();operate(owners.get(0),"verify");});d.show();}
  void operate(int slot,String action){ReferenceUi.Modal d=new ReferenceUi.Modal(a,action.equals("measure")?"完整线路测速":action.equals("verify")?"核验出口":"重新连接");d.body.addView(DesignUi.progress(a,action.equals("measure")?"正在测量入口与固定出口的完整线路…":"正在检查此窗口网络…",""));d.buttons("收起",d::dismiss,"",()->{});d.show();NetworkBridge.run(a,slot,action,null,null,(ok,message,snapshot)->{if(closed||a.isDestroyed())return;reload();if(d.isShowing()){d.body.removeAllViews();TextView result=ReferenceUi.text(a,message,15,ok?ReferenceUi.GREEN:ReferenceUi.RED,true);d.body.addView(result);d.buttons("关闭",d::dismiss,"",()->{});d.resize();}});}
  void networkMode(int slot){if(catalog==null){afterRead=()->networkMode(slot);reload();return;}ReferenceUi.Modal d=new ReferenceUi.Modal(a,"网络方式 · "+Profiles.display(a,slot));choice(d,"订阅入口 + 固定出口","",false,()->{d.dismiss();for(int i=0;i<windows.length();i++)if(windows.optJSONObject(i).optJSONObject("row").optInt("slot")==slot){edit(windows.optJSONObject(i));return;}});choice(d,"手机网络 / 手机 VPN","",false,()->{d.dismiss();external(slot,false);});choice(d,"应用专用代理","",false,()->{d.dismiss();external(slot,true);});d.show();}
  void external(int slot,boolean proxy){ReferenceUi.Modal d=new ReferenceUi.Modal(a,proxy?"应用专用代理":"手机网络 / VPN");SharedPreferences prefs=Profiles.context(a,slot).getSharedPreferences("chat",0);EditText address=proxy?DesignUi.input(d.body,"代理地址",prefs.getString("proxy",""),"http://主机:端口 或 socks://主机:端口"):null;CheckBox vpn=new CheckBox(a);vpn.setText("手机 VPN 断开时暂停联网");vpn.setTextSize(13);vpn.setChecked(prefs.getBoolean("requireExternalVpn",true));d.body.addView(vpn);TextView error=ReferenceUi.text(a,"",12,ReferenceUi.RED,false);d.body.addView(error);String baseline=NativeNetwork.hash(new SecretStore(Profiles.context(a,slot)).settings().toString());d.buttons("取消",d::dismiss,"保存并应用",()->{String value=proxy?address.getText().toString().trim():"";if(proxy&&!MainActivity.validProxy(value)){address.setError("填写有效的 HTTP / SOCKS 代理地址");return;}d.primary().setEnabled(false);NetworkBridge.run(a,slot,"external",J.obj("proxy",value,"requireExternalVpn",vpn.isChecked()),baseline,(ok,message,state)->{if(closed||a.isDestroyed())return;reload();if(ok)d.dismiss();else{error.setText(message);d.primary().setEnabled(true);d.resize();}});});d.show();}
}
