package local.pocketchat;
import android.app.*;import android.os.SystemClock;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;

final class NetworkMetricsUi {
 static String amount(long bytes){if(bytes<1024)return bytes+" B";if(bytes<1048576)return String.format(Locale.ROOT,"%.1f KB",bytes/1024.0);if(bytes<1073741824L)return String.format(Locale.ROOT,"%.1f MB",bytes/1048576.0);return String.format(Locale.ROOT,"%.2f GB",bytes/1073741824.0);}
 static String speed(long bytes){return amount(bytes)+"/s";}
 static String latency(JSONObject q,long now){long time=q.optLong("lastAt");if(time<=0)return "等待测量";if(now<time-60000||now-time>90000)return "数据待更新";return q.optInt("latest",-1)>0?q.optInt("latest")+" ms":"最近探测未通过";}
 static String stability(JSONObject q,long now){long time=q.optLong("lastAt");if(time<=0||now<time-60000||now-time>90000)return "待探测";if(q.optInt("latest",-1)<=0)return "待复核";if(q.optInt("samples")<3)return "可用，观察中";if(q.optDouble("rate")<.9)return "成功率偏低";if(q.optLong("jitter")>=Math.max(100,q.optLong("mean")*.5))return "延迟波动较大";return "近期稳定";}
 static String speedLine(TrafficMonitor.Sample sample,long now){return sample==null||!sample.fresh(now)?"↓ 下载 —   ↑ 上传 —":"↓ 下载 "+speed(sample.down)+"   ↑ 上传 "+speed(sample.up);}
 static String line(ChatSession s,NativeNetwork n,long now,long monotonic){if(s.offline)return "网络已断开 · 速度与延迟暂不可用";if(!s.internalNetwork())return "使用手机网络 · 内置线路统计未启用";if(n.recoveryBlocked)return "连接已停止 · 出口核实未通过";if(!n.ready||!n.coreAlive())return n.starting?"正在连接 · 等待线路测量":"线路未连接 · 速度与延迟暂不可用";JSONObject q=n.quality.stats(n.currentEntry,now);return "线路："+stability(q,now)+" · 延迟 "+latency(q,now);}
 static String compact(ChatSession s,NativeNetwork n,long now){if(s.offline)return "离线\n点按检查";if(!s.internalNetwork())return "手机网络\n点按详情";if(n.recoveryBlocked)return "出口异常\n连接已停";if(!n.ready||!n.coreAlive())return n.starting?"连接中\n等待测量":"未连接\n点按检查";JSONObject q=n.quality.stats(n.currentEntry,now);String state=stability(q,now).replace("可用，观察中","观察中").replace("延迟波动较大","波动较大");String delay=latency(q,now);if(delay.equals("最近探测未通过"))delay="探测未通过";return state+"\n"+delay;}
 static void update(MainActivity a){if(a.networkLine==null)return;NativeNetwork n=NativeNetwork.get(a);n.traffic.watch(a.active&&!a.destroyed&&a.session.internalNetwork()&&!a.session.offline);try{ProfileCatalog.get(a).heartbeat(a.session,false);}catch(Exception ignored){}a.session.audit.refresh(false);String compact=compact(a.session,n,System.currentTimeMillis());if(a.session.audit.hasChanges())compact=a.session.networkReady&&!a.session.offline&&!n.recoveryBlocked?"环境有变化\n"+compact.substring(compact.indexOf("\n")+1):"• "+compact;if(!compact.contentEquals(a.networkLine.getText()))a.networkLine.setText(compact);a.networkLine.setContentDescription("线路状态与延迟，点按查看网络详情："+line(a.session,n,System.currentTimeMillis(),SystemClock.elapsedRealtime()));a.networkLine.setTextColor(a.session.offline||n.recoveryBlocked?0xffb42318:Ui.MUTED);if(a.designChrome!=null)a.designChrome.update();}
 static String detail(ChatSession s,NativeNetwork n,long now,long monotonic){String text=line(s,n,now,monotonic)+"\n"+ExitIpUi.value(s,n);if(!s.internalNetwork())return text+"\n\n当前统计适用于应用内置代理。手机总体网速未读取。";if(s.offline||!n.ready||!n.coreAlive())return text+"\n\n恢复连接后会自动更新。";JSONObject q=n.quality.stats(n.currentEntry,now);text+="\n"+speedLine(n.traffic.sample,monotonic)+"\n\n入口："+NativeNetwork.display(n.currentEntry);if(q.optLong("lastAt")>0)text+="\n最近探测："+Math.max(0,(now-q.optLong("lastAt"))/1000)+" 秒前";int count=q.optInt("samples");if(count>0)text+="\n探测成功率："+Math.round(q.optDouble("rate")*100)+"%（"+q.optInt("successes")+" / "+count+" 次）";if(q.optInt("successes")>0)text+="\n平均延迟："+q.optLong("mean")+" ms · 延迟波动："+q.optLong("jitter")+" ms";if(n.currentEntry.equals(n.lastProbeEntry)&&n.lastProbeDurationAt>0&&now-n.lastProbeDurationAt<=90000)text+="\n最近完整探测："+n.lastProbeDuration+" ms（建连及探测请求的总耗时）";TrafficMonitor.Sample sample=n.traffic.sample;if(sample!=null&&sample.fresh(monotonic))text+="\n\n本次代理启动累计\n下载 "+amount(sample.downTotal)+" · 上传 "+amount(sample.upTotal);return text+"\n\n速度是内置代理记录的实际传输量，约每秒更新；空闲时接近 0 属于正常情况，不代表线路带宽。\n延迟采用 Clash 的统一延迟口径，经当前入口和固定出口探测：通常取复用连接后的第二次请求耗时；内核无法完成第二次请求时可能回退到首次请求。完整探测耗时另列，包含建连和探测请求，不能与顶部延迟直接比较。约每 30 秒复测，与模型思考或生成用时无关。成功率与波动取最近 30 分钟内最多 20 次探测。少于 3 次时显示观察中；成功率低于 90% 或波动明显时会提示关注。近期稳定只代表探测记录，不保证网站服务或模型响应时间。";}
 static void show(MainActivity a){if(a.networkDialog!=null&&a.networkDialog.isShowing())return;NativeNetwork n=NativeNetwork.get(a);TextView content=a.label("",14,Ui.INK);content.setPadding(a.dp(24),a.dp(8),a.dp(24),a.dp(12));content.setLineSpacing(a.dp(4),1);ScrollView scroll=new ScrollView(a);LinearLayout box=new LinearLayout(a);box.setOrientation(1);box.addView(content);Button verify=new Button(a);verify.setText("查看 / 核实出口 IP");verify.setOnClickListener(v->ExitIpUi.show(a));box.addView(verify,new LinearLayout.LayoutParams(-1,-2));Button audit=new Button(a);audit.setText("环境自检 / 查看变化");audit.setOnClickListener(v->EnvironmentAuditUi.show(a));box.addView(audit,new LinearLayout.LayoutParams(-1,-2));scroll.addView(box);AlertDialog dialog=new AlertDialog.Builder(a).setTitle("网络情况").setView(scroll).setPositiveButton("测一下延迟",null).setNeutralButton("连接详情",(d,w)->NetworkStatusUi.show(a)).setNegativeButton("关闭",null).create();a.networkDialog=dialog;Runnable tick=new Runnable(){public void run(){if(!dialog.isShowing())return;content.setText(detail(a.session,n,System.currentTimeMillis(),SystemClock.elapsedRealtime()));Button measure=dialog.getButton(-1);measure.setText(n.measuringLatency?"正在测量…":"测一下延迟");measure.setEnabled(a.session.internalNetwork()&&!a.session.offline&&n.ready&&!n.starting&&!n.measuringLatency&&SystemClock.elapsedRealtime()-n.lastManualProbe>=5000);a.handler.postDelayed(this,1000);}};dialog.setOnShowListener(d->{dialog.getButton(-1).setOnClickListener(v->{n.measureLatency((ok,message)->{update(a);if(!ok)Toast.makeText(a,message,Toast.LENGTH_SHORT).show();});dialog.getButton(-1).setEnabled(false);});tick.run();});dialog.setOnDismissListener(d->{a.handler.removeCallbacks(tick);if(a.networkDialog==dialog)a.networkDialog=null;});dialog.show();}
}
