package local.pocketchat;
import android.content.*;import android.net.Uri;import org.json.*;import java.util.*;import java.nio.charset.StandardCharsets;

/** An encrypted library of existing subscriptions/exits. It never chooses a global default. */
final class NetworkCatalog {
  static final Object lock=new Object();final Set<String> changedSubscriptions=new HashSet<>(),changedExits=new HashSet<>();final Context c;final SecretStore store;final JSONObject data;
  NetworkCatalog(Context c){this.c=c;store=new SecretStore(Profiles.context(c,0));JSONObject saved=new JSONObject();try{byte[] raw=store.get("network-catalog");if(raw!=null)saved=J.parse(new String(raw,StandardCharsets.UTF_8));}catch(Exception ignored){}data=saved;if(!data.has("subscriptions"))put(data,"subscriptions",new JSONArray());if(!data.has("exits"))put(data,"exits",new JSONArray());collect();}
  static void put(JSONObject o,String key,Object value){try{o.put(key,value);}catch(JSONException e){throw new IllegalArgumentException(e);}}
  static String exitId(JSONObject s){return NativeNetwork.hash(s.optString("exitHost")+":"+s.optInt("exitPort")+":"+s.optString("exitUser")+":"+s.optString("exitPassword"));}
  static String cacheSlot(String url){StringBuilder name=new StringBuilder("pool-");for(char x:NativeNetwork.hash(url).toCharArray())name.append("abcdefghijklmnop".charAt(Character.digit(x,16)));return name.toString();}
  static String subscriptionName(JSONObject s){String name=s.optString("subscriptionName");if(!name.isEmpty())return name;String host=Uri.parse(s.optString("subscriptionUrl")).getHost();return host==null?"未选订阅":host;}
  JSONArray subscriptions(){return data.optJSONArray("subscriptions");}JSONArray exits(){return data.optJSONArray("exits");}
  static JSONObject find(JSONArray list,String id){if(list!=null)for(int i=0;i<list.length();i++){JSONObject x=list.optJSONObject(i);if(x!=null&&id.equals(x.optString("id")))return x;}return null;}
  JSONObject subscription(String id){return find(subscriptions(),id);}JSONObject exit(String id){return find(exits(),id);}
  void collect(){JSONArray rows=ProfileCatalog.get(c).list();for(int i=0;i<rows.length();i++){JSONObject row=rows.optJSONObject(i);if(!row.optBoolean("created")&&!row.optBoolean("deleting"))continue;int slot=row.optInt("slot");SecretStore vault=new SecretStore(Profiles.context(c,slot));JSONObject config=vault.settings();String url=config.optString("subscriptionUrl");
    if(!url.isEmpty()){String id=NativeNetwork.hash(url);JSONObject s=subscription(id);if(s==null){s=J.obj("id",id,"name",subscriptionName(config),"url",url,"owner",slot,"nodes",new JSONArray());subscriptions().put(s);}try{JSONObject meta=J.parse(new String(Optional.ofNullable(vault.get("subscription-meta")).orElse(new byte[0]),StandardCharsets.UTF_8));JSONObject ui=J.parse(new String(Optional.ofNullable(vault.get("subscription-ui")).orElse(new byte[0]),StandardCharsets.UTF_8));boolean newer=id.equals(meta.optString("urlHash"))&&meta.optLong("updatedAt")>s.optLong("updatedAt");if(id.equals(ui.optString("urlHash"))&&(EntrySelection.strings(s.optJSONArray("nodes")).isEmpty()||newer)){put(s,"nodes",ui.optJSONArray("nodes"));put(s,"owner",slot);}if(newer){put(s,"updatedAt",meta.optLong("updatedAt"));put(s,"owner",slot);}}catch(Exception ignored){}
    }
    if(!config.optString("exitHost").isEmpty()){String id=exitId(config);JSONObject e=exit(id);if(e==null){e=J.obj("id",id,"name",config.optString("exitName",config.optString("exitHost")),"region",config.optString("exitRegion"),"host",config.optString("exitHost"),"port",config.optInt("exitPort"),"user",config.optString("exitUser"),"password",config.optString("exitPassword"));exits().put(e);}try{JSONObject baseline=J.parse(new String(Optional.ofNullable(vault.get("exit-baseline")).orElse(new byte[0]),StandardCharsets.UTF_8));if(id.equals(baseline.optString("fingerprint")))put(e,"verifiedIp",baseline.optString("ip"));}catch(Exception ignored){}
    }
  }}
  java.io.File lockFile(){return new java.io.File(Profiles.context(c,0).getNoBackupFilesDir(),"network-catalog.lock");}
  JSONObject saved()throws Exception{byte[] raw=store.get("network-catalog");return raw==null?new JSONObject():J.parse(new String(raw,StandardCharsets.UTF_8));}
  void save()throws Exception{synchronized(lock){try(java.io.RandomAccessFile handle=new java.io.RandomAccessFile(lockFile(),"rw");java.nio.channels.FileLock held=handle.getChannel().lock()){saveLocked(saved());}}}
  void saveLocked(JSONObject latest)throws Exception{for(String key:new String[]{"subscriptions","exits"}){JSONArray merged=latest.optJSONArray(key);if(merged==null)merged=new JSONArray();JSONArray local=data.optJSONArray(key);Set<String> dirty=key.equals("subscriptions")?changedSubscriptions:changedExits;for(int i=0;i<local.length();i++){JSONObject item=local.optJSONObject(i),existing=find(merged,item.optString("id"));if(existing==null)merged.put(item);else if(dirty.contains(item.optString("id"))||item.optLong("updatedAt")>existing.optLong("updatedAt")){for(int n=0;n<merged.length();n++)if(merged.optJSONObject(n)==existing){merged.put(n,item);break;}}}put(latest,key,merged);}store.put("network-catalog",latest.toString().getBytes(StandardCharsets.UTF_8));put(data,"subscriptions",latest.optJSONArray("subscriptions"));put(data,"exits",latest.optJSONArray("exits"));changedSubscriptions.clear();changedExits.clear();}
  byte[] cache(JSONObject subscription){String url=subscription.optString("url");try{byte[] own=store.get(cacheSlot(url));if(own!=null&&subscription.optLong("cacheUpdatedAt")>=subscription.optLong("updatedAt"))return own;SecretStore owner=new SecretStore(Profiles.context(c,subscription.optInt("owner")));JSONObject meta=J.parse(new String(Optional.ofNullable(owner.get("subscription-meta")).orElse(new byte[0]),StandardCharsets.UTF_8));if(NativeNetwork.hash(url).equals(meta.optString("urlHash"))&&meta.optLong("updatedAt")>=subscription.optLong("updatedAt"))return owner.get("subscription");}catch(Exception ignored){}return null;}
  void parsed(String id,JSONArray nodes,byte[] bytes,long updatedAt)throws Exception{synchronized(lock){try(java.io.RandomAccessFile handle=new java.io.RandomAccessFile(lockFile(),"rw");java.nio.channels.FileLock held=handle.getChannel().lock()){
    JSONObject s=subscription(id),latest=saved(),current=find(latest.optJSONArray("subscriptions"),id);if(s==null)throw new IllegalArgumentException("订阅已移除");if(updatedAt<Math.max(s.optLong("updatedAt"),current==null?0:current.optLong("updatedAt")))throw new java.io.IOException("订阅已更新，请重新读取当前入口");String slot=cacheSlot(s.optString("url"));byte[] previous=store.get(slot);JSONObject before=J.parse(s.toString());
    try{if(current!=null)put(s,"name",current.optString("name"));put(s,"nodes",nodes);changedSubscriptions.add(id);if(updatedAt>0)put(s,"updatedAt",updatedAt);put(s,"cacheUpdatedAt",updatedAt);store.put(slot,bytes);saveLocked(latest);}catch(Exception error){NetworkUiProvider.restore(store,slot,previous);for(Iterator<String> keys=s.keys();keys.hasNext();){keys.next();keys.remove();}for(Iterator<String> keys=before.keys();keys.hasNext();){String key=keys.next();put(s,key,before.opt(key));}changedSubscriptions.remove(id);throw error;}
  }}}
  JSONObject addSubscription(String name,String url)throws Exception{NativeNetwork.validate(J.obj("subscriptionUrl",url,"exitHost","localhost","exitPort",1));String id=NativeNetwork.hash(url);JSONObject s=subscription(id);if(s==null){s=J.obj("id",id,"name",name,"url",url,"owner",Profiles.slot(c),"nodes",new JSONArray());subscriptions().put(s);}else put(s,"name",name);changedSubscriptions.add(id);save();return s;}
  JSONObject addExit(String name,String region,String host,int port,String user,String password)throws Exception{JSONObject config=J.obj("subscriptionUrl","https://localhost/","exitHost",host,"exitPort",port,"exitUser",user,"exitPassword",password);NativeNetwork.validate(config);String id=exitId(config);JSONObject e=exit(id);if(e==null){e=J.obj("id",id,"name",name,"region",region,"host",host,"port",port,"user",user,"password",password);exits().put(e);}else{put(e,"name",name);put(e,"region",region);}changedExits.add(id);save();return e;}
}
