package local.pocketchat;
import org.json.*;import java.util.*;import java.io.IOException;

/** Detached candidate. No preferences, route selection, or live connection writes occur here. */
final class NetworkDraft {
  final int slot;final String baseline;final JSONObject original;String subscriptionId="",exitId="",mode="random",entry="";final LinkedHashSet<String> pool=new LinkedHashSet<>();
  NetworkDraft(int slot,JSONObject original,NetworkCatalog catalog){this.slot=slot;this.original=J.parse(original.toString());baseline=NetworkChanges.hash(Profiles.context(catalog.c,slot));String url=original.optString("subscriptionUrl");if(!url.isEmpty())subscriptionId=NativeNetwork.hash(url);if(!original.optString("exitHost").isEmpty())exitId=NetworkCatalog.exitId(original);mode="manual".equals(original.optString("entryMode"))?"manual":"random";entry=original.optString("entry");pool.addAll(EntrySelection.strings(original.optJSONArray("entryPool")));JSONObject sub=catalog.subscription(subscriptionId);if(!original.has("entryMode")&&sub!=null)pool.addAll(EntrySelection.strings(sub.optJSONArray("nodes")));normalize(catalog);}
  void subscription(String id,NetworkCatalog catalog){if(!id.equals(subscriptionId)){subscriptionId=id;pool.clear();entry="";}normalize(catalog);}
  void normalize(NetworkCatalog catalog){JSONObject sub=catalog.subscription(subscriptionId);List<String> nodes=sub==null?new ArrayList<>():EntrySelection.strings(sub.optJSONArray("nodes"));pool.retainAll(nodes);if(!nodes.contains(entry)||("random".equals(mode)&&!pool.contains(entry)))entry="";}
  void randomize(Random random){entry=EntrySelection.random(pool,random);}
  JSONObject candidate(NetworkCatalog catalog)throws Exception{JSONObject s=catalog.subscription(subscriptionId),e=catalog.exit(exitId);if(s==null)throw new IOException("请选择入口订阅");if(e==null)throw new IOException("请选择固定出口");JSONObject value=J.parse(original.toString());for(String key:new String[]{"subscriptionUrl","subscriptionName","exitHost","exitPort","exitUser","exitPassword","exitName","exitRegion","entryMode","entryPool","entry"})value.remove(key);
    NetworkCatalog.put(value,"subscriptionUrl",s.optString("url"));NetworkCatalog.put(value,"subscriptionName",s.optString("name"));NetworkCatalog.put(value,"exitHost",e.optString("host"));NetworkCatalog.put(value,"exitPort",e.optInt("port"));NetworkCatalog.put(value,"exitUser",e.optString("user"));NetworkCatalog.put(value,"exitPassword",e.optString("password"));NetworkCatalog.put(value,"exitName",e.optString("name"));NetworkCatalog.put(value,"exitRegion",e.optString("region"));NetworkCatalog.put(value,"entryMode",mode);NetworkCatalog.put(value,"entryPool",new JSONArray(pool));NetworkCatalog.put(value,"entry",entry);NativeNetwork.validate(value);EntrySelection.validate(value,EntrySelection.strings(s.optJSONArray("nodes")));return value;
  }
}
