package local.pocketchat;
import android.content.*;import org.json.*;import java.util.*;

/** Recent complete-chain samples; a healthy route is not replaced for one fast probe. */
final class RouteQuality {
 static final long WINDOW=30*60*1000L,COOLDOWN=5*60*1000L;
 final SharedPreferences prefs;JSONObject data;String scope="",selected="",candidate="";long switched=0;int wins=0;
 RouteQuality(Context c){prefs=c.getSharedPreferences("route-quality",0);data=J.parse(prefs.getString("samples","{}"));scope=prefs.getString("scope","");selected=prefs.getString("selected","");candidate=prefs.getString("candidate","");switched=prefs.getLong("switched",0);wins=prefs.getInt("wins",0);}
 synchronized void configure(String value){if(value.equals(scope))return;scope=value;data=new JSONObject();selected="";candidate="";switched=0;wins=0;save();}
 synchronized void record(String name,int delay,long now){if(name==null||name.isEmpty())return;JSONArray old=data.optJSONArray(name),next=new JSONArray();if(old!=null)for(int i=Math.max(0,old.length()-19);i<old.length();i++){JSONObject x=old.optJSONObject(i);if(x!=null&&now-x.optLong("t")<=WINDOW&&x.optLong("t")<=now+60000)next.put(x);}next.put(J.obj("t",now,"d",delay));try{data.put(name,next);}catch(Exception ignored){}save();}
 synchronized JSONObject stats(String name,long now){JSONArray a=data.optJSONArray(name);int count=0,ok=0,failures=0;double sum=0,squares=0;int latest=-1;long lastAt=0;if(a!=null)for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(now-x.optLong("t")>WINDOW||x.optLong("t")>now+60000)continue;int d=x.optInt("d",-1);count++;latest=d;lastAt=x.optLong("t");if(d>0){ok++;sum+=d;squares+=(double)d*d;failures=0;}else failures++;}double mean=ok==0?0:sum/ok,jitter=ok==0?0:Math.sqrt(Math.max(0,squares/ok-mean*mean)),rate=count==0?0:(double)ok/count;double score=ok==0?1000000:mean+1.5*jitter+3000*(1-rate)+failures*1000+Math.max(0,3-count)*180;return J.obj("samples",count,"successes",ok,"rate",rate,"mean",Math.round(mean),"jitter",Math.round(jitter),"score",score,"latest",latest,"lastAt",lastAt,"failures",failures);}
 synchronized String choose(List<String> names,String current,boolean force,boolean busy,long now){String best="";double score=Double.MAX_VALUE;for(String name:names){JSONObject x=stats(name,now);if(x.optInt("latest")>0&&x.optDouble("score")<score){best=name;score=x.optDouble("score");}}if(best.isEmpty())return current;if(best.equals(candidate))wins++;else{candidate=best;wins=1;}save();if(force||current.isEmpty())return best;JSONObject health=stats(current,now);if(health.optInt("latest")<=0)return health.optInt("failures")>=2?best:current;if(best.equals(current)||busy||cooldown(now)>0||wins<2)return current;JSONObject c=stats(current,now),n=stats(best,now);if(n.optInt("samples")<3||n.optDouble("rate")<.8)return current;double previous=c.optDouble("score");return score<=previous*.75&&previous-score>=100?best:current;}
 synchronized long cooldown(long now){if(switched>now+60000){switched=now;save();}return Math.max(0,Math.min(COOLDOWN,COOLDOWN-(now-switched)));}
 synchronized void selected(String name,long now){if(!name.equals(selected)){selected=name;switched=now;candidate="";wins=0;save();}}
 void save(){prefs.edit().putString("scope",scope).putString("samples",data.toString()).putString("selected",selected).putString("candidate",candidate).putLong("switched",switched).putInt("wins",wins).apply();}
}
