package local.pocketchat;
import android.app.*;import android.content.*;import android.os.*;import android.text.*;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;

/** Window manager stays native; opening or creating a window is an explicit action. */
public class WindowHomeActivity extends Activity {
  LinearLayout root,cards,filters;TextView count;EditText search;int filter;final Handler handler=new Handler(Looper.getMainLooper());boolean preparing;String lastSignature="";
  final Runnable update=()->{refresh();handler.postDelayed(this.update,3000);};
  int dp(int n){return DesignUi.dp(this,n);}
  @Override public void onCreate(Bundle state){super.onCreate(state);root=DesignUi.screen(this);LinearLayout box=DesignUi.body(this,root,"窗口管理",null);LinearLayout tools=DesignUi.row(this);tools.addView(DesignUi.icon(this,"window",DesignUi.CYAN,36));count=DesignUi.text(this,"",13,DesignUi.MUTED);count.setPadding(dp(10),0,0,0);tools.addView(count,new LinearLayout.LayoutParams(0,-2,1));Button refresh=DesignUi.button(this,"↻",false,()->{lastSignature="";refresh();});refresh.setContentDescription("刷新窗口状态");tools.addView(refresh,new LinearLayout.LayoutParams(dp(36),dp(36)));box.addView(tools);
    DesignUi.action(box,"＋  创建新窗口",true,()->createWindow());search=DesignUi.input(box,"搜索窗口","","输入窗口名称");search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){lastSignature="";refresh();}public void afterTextChanged(Editable e){}});HorizontalScrollView filterScroll=new HorizontalScrollView(this);filterScroll.setHorizontalScrollBarEnabled(false);filters=DesignUi.row(this);filterScroll.addView(filters);LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(-1,dp(40));fp.topMargin=dp(12);box.addView(filterScroll,fp);cards=DesignUi.column(this);box.addView(cards);root.addView(DesignUi.nav(this,1,n->{if(n==1){filter=0;search.setText("");lastSignature="";refresh();}else if(n==2)startActivity(new Intent(this,DownloadCenterActivity.class));else openWindow(AppSettings.defaultSlot(this),n==3?"network":n==4?"settings":"default");},null));setContentView(root);refresh();}
  @Override protected void onResume(){super.onResume();lastSignature="";handler.removeCallbacks(update);handler.post(update);}
  @Override protected void onPause(){handler.removeCallbacks(update);super.onPause();}
  @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);lastSignature="";refresh();}
  Set<Integer> live(){Set<Integer> out=new HashSet<>();try{List<ActivityManager.RunningAppProcessInfo> rows=getSystemService(ActivityManager.class).getRunningAppProcesses();if(rows!=null)for(ActivityManager.RunningAppProcessInfo r:rows)out.add(r.pid);}catch(Exception ignored){}return out;}
  int lastWindow(){int selected=0;long time=0;JSONArray rows=ProfileCatalog.get(this).list();for(int i=0;i<rows.length();i++){JSONObject r=rows.optJSONObject(i);if(r.optBoolean("created")&&r.optLong("opened")>time){time=r.optLong("opened");selected=r.optInt("slot");}}return selected;}
  void refresh(){if(cards==null)return;JSONArray rows=ProfileCatalog.get(this).list();Set<Integer> running=live();int[] counts=new int[5];for(int i=0;i<rows.length();i++){JSONObject r=rows.optJSONObject(i);if(!r.optBoolean("created"))continue;counts[0]++;if(r.optBoolean("favorite"))counts[1]++;if(running.contains(r.optInt("pid")))counts[2]++;if(r.optBoolean("waiting")&&running.contains(r.optInt("pid")))counts[3]++;if(!r.optString("problem").isEmpty())counts[4]++;}String query=search.getText().toString().trim().toLowerCase(Locale.ROOT);String signature=rows.toString()+running+filter+query+AppSettings.defaultSlot(this);if(signature.equals(lastSignature))return;lastSignature=signature;count.setText("窗口总数  "+counts[0]+" / 8\n默认："+Profiles.display(this,AppSettings.defaultSlot(this)));filters.removeAllViews();String[] titles={"全部","收藏","已打开","等待回复","异常"};for(int i=0;i<5;i++){final int selected=i;Button b=DesignUi.button(this,titles[i]+" "+counts[i],i==filter,()->{filter=selected;lastSignature="";refresh();});b.setTextSize(11);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(i==3?90:74),dp(34));p.rightMargin=dp(6);filters.addView(b,p);}cards.removeAllViews();int shown=0;int[] colors={DesignUi.CYAN,0xffefbc49,0xffb768ff,DesignUi.GREEN};
    for(int i=0;i<rows.length();i++){JSONObject r=rows.optJSONObject(i);if(!r.optBoolean("created"))continue;boolean live=running.contains(r.optInt("pid")),fresh=System.currentTimeMillis()-r.optLong("seen")<60000;if(filter==1&&!r.optBoolean("favorite")||filter==2&&!live||filter==3&&!(r.optBoolean("waiting")&&live)||filter==4&&r.optString("problem").isEmpty()||!r.optString("name").toLowerCase(Locale.ROOT).contains(query))continue;shown++;int id=r.optInt("slot"),color=colors[id%4];LinearLayout card=DesignUi.card(this);card.setContentDescription("打开窗口："+r.optString("name"));card.setClickable(true);card.setFocusable(true);card.setOnClickListener(v->openWindow(id,"chat"));LinearLayout heading=DesignUi.row(this);heading.addView(DesignUi.icon(this,"window",color,40));LinearLayout titlesBox=DesignUi.column(this);titlesBox.setPadding(dp(10),0,dp(5),0);titlesBox.addView(DesignUi.text(this,(r.optBoolean("favorite")?"★ ":"")+r.optString("name"),16,DesignUi.TEXT));titlesBox.addView(DesignUi.text(this,"chatgpt.com",11,DesignUi.MUTED));heading.addView(titlesBox,new LinearLayout.LayoutParams(0,-2,1));String status=!r.optString("problem").isEmpty()?"需处理":live?r.optBoolean("waiting")?"等待中":fresh?"运行中":"待核对":"未运行";heading.addView(DesignUi.badge(this,"● "+status,!r.optString("problem").isEmpty()?DesignUi.RED:live?DesignUi.GREEN:DesignUi.MUTED));card.addView(heading);LinearLayout meta=DesignUi.row(this);meta.setPadding(0,dp(10),0,dp(8));if(id==AppSettings.defaultSlot(this)){meta.addView(DesignUi.badge(this,"默认",DesignUi.CYAN));}TextView info=DesignUi.text(this,"  "+r.optString("page","原网页")+" · 独立 Cookie",11,DesignUi.MUTED);meta.addView(info,new LinearLayout.LayoutParams(0,-2,1));if(r.optLong("opened")>0)meta.addView(DesignUi.text(this,android.text.format.DateFormat.format("MM-dd HH:mm",r.optLong("opened")).toString(),10,DesignUi.MUTED));card.addView(meta);LinearLayout buttons=DesignUi.row(this);String[] labels={"▷ 打开","编辑","···"};for(int j=0;j<3;j++){final int action=j;Button b=DesignUi.button(this,labels[j],false,()->{if(action==0)openWindow(id,"chat");if(action==1)openWindow(id,"edit");if(action==2)menu(id);});b.setTextSize(12);b.setContentDescription(labels[j]+" "+r.optString("name"));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(32),j==2?.45f:1);if(j>0)p.leftMargin=dp(6);buttons.addView(b,p);}card.addView(buttons);DesignUi.addCard(cards,card);
    }if(shown==0)DesignUi.note(cards,"没有符合条件的窗口。");}
  void menu(int id){JSONObject row=ProfileCatalog.get(this).item(id);String[] names={"打开窗口","编辑窗口","修改名称",row.optBoolean("favorite")?"取消收藏":"收藏窗口",id==AppSettings.defaultSlot(this)?"当前默认窗口":"设为默认窗口","网络设置","清理登录数据 · 开发中","删除窗口 · 开发中"};new AlertDialog.Builder(this).setTitle(row.optString("name")).setItems(names,(d,n)->{if(n==0)openWindow(id,"chat");if(n==1)openWindow(id,"edit");if(n==2)rename(id);if(n==3){ProfileCatalog.get(this).favorite(id,!row.optBoolean("favorite"));lastSignature="";refresh();}if(n==4){AppSettings.defaultSlot(this,id);lastSignature="";refresh();}if(n==5)openWindow(id,"network");if(n==6)FutureFeatures.open(this,FutureFeatures.Feature.PROFILE_DATA_CLEAR,id);if(n==7)FutureFeatures.open(this,FutureFeatures.Feature.PROFILE_DELETE,id);}).setNegativeButton("取消",null).show();}
  void rename(int id){LinearLayout box=DesignUi.column(this);box.setPadding(dp(20),0,dp(20),dp(15));EditText name=DesignUi.input(box,"窗口名称",Profiles.display(this,id),"最多 24 字");AlertDialog d=new AlertDialog.Builder(this).setTitle("修改窗口名称").setView(box).setPositiveButton("保存",null).setNegativeButton("取消",null).create();d.setOnShowListener(v->d.getButton(-1).setOnClickListener(w->{String value=name.getText().toString().trim();if(value.isEmpty()||value.length()>24){name.setError("名称需要 1–24 字");return;}Profiles.rename(this,id,value);d.dismiss();lastSignature="";refresh();}));d.show();}
  void openWindow(int id,String action){if(id<0||id>=Profiles.MAX)return;if(id>0&&Build.VERSION.SDK_INT<28){SavedFileActions.toast(this,"独立窗口需要 Android 9 或更新版本");return;}ProfileCatalog.get(this).opened(id);Intent intent=new Intent(this,Profiles.activity(id)).putExtra("openWindowAction",action.equals("default")?"chat":action).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_REORDER_TO_FRONT);if(action.equals("default"))intent.putExtra("forceWebMode",true);startActivity(intent);}
  void createWindow(){if(preparing)return;if(Build.VERSION.SDK_INT<28){SavedFileActions.toast(this,"独立窗口需要 Android 9 或更新版本");return;}JSONArray windows=ProfileCatalog.get(this).list();int next=-1;for(int i=1;i<windows.length();i++)if(!windows.optJSONObject(i).optBoolean("created")){next=i;break;}if(next<0){SavedFileActions.toast(this,"已达到 8 个窗口");return;}new Wizard(next,windows).show();}
  final class Wizard {
    final int id;final JSONArray windows;final Dialog dialog=new Dialog(WindowHomeActivity.this);LinearLayout body;int step,sourceType;String title;int sourceSlot;boolean makeDefault;Wizard(int id,JSONArray windows){this.id=id;this.windows=windows;title="窗口 "+(id+1);sourceSlot=AppSettings.defaultSlot(WindowHomeActivity.this);}
    void show(){LinearLayout screen=DesignUi.screen(WindowHomeActivity.this);body=DesignUi.body(WindowHomeActivity.this,screen,"创建窗口",()->dialog.dismiss());dialog.setContentView(screen);dialog.show();dialog.getWindow().setBackgroundDrawableResource(android.R.color.transparent);dialog.getWindow().setLayout(-1,-1);render();}
    void render(){body.removeAllViews();body.addView(DesignUi.tabs(WindowHomeActivity.this,new String[]{"① 基本信息","② 配置来源","③ 完成"},step,n->{if(n<step){step=n;render();}}));if(step==0){EditText name=DesignUi.input(body,"窗口名称",title,"例如：工作号、研究专用");name.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int a,int b,int c){title=s.toString();}public void afterTextChanged(Editable e){}});DesignUi.field(body,"选择平台","ChatGPT · chatgpt.com");DesignUi.addCard(body,DesignUi.setting(WindowHomeActivity.this,"globe","其他平台","预留平台接入接口","开发中",()->FutureFeatures.open(WindowHomeActivity.this,FutureFeatures.Feature.OTHER_PLATFORMS,id)));DesignUi.action(body,"下一步：配置来源 →",true,()->{if(title.trim().isEmpty()||title.trim().length()>24){name.setError("名称需要 1–24 字");return;}title=title.trim();step=1;render();});}
      if(step==1){String[] choices={"使用默认配置","从现有窗口复制","自定义配置"};for(int i=0;i<3;i++){final int n=i;LinearLayout card=DesignUi.card(WindowHomeActivity.this);RadioButton radio=new RadioButton(WindowHomeActivity.this);radio.setText(choices[i]);radio.setTextColor(DesignUi.TEXT);radio.setChecked(sourceType==i);card.addView(radio);card.addView(DesignUi.text(WindowHomeActivity.this,i==0?"复制默认窗口的网络配置":i==1?"选择一个窗口，只复制网络设置":"新窗口内手动设置网络",12,DesignUi.MUTED));radio.setOnClickListener(v->{sourceType=n;render();});DesignUi.addCard(body,card);}if(sourceType==1){String[] names=new String[windows.length()];java.util.List<Integer> ids=new ArrayList<>();java.util.List<String> labels=new ArrayList<>();for(int i=0;i<windows.length();i++)if(windows.optJSONObject(i).optBoolean("created")){ids.add(i);labels.add(windows.optJSONObject(i).optString("name"));}Spinner spinner=new Spinner(WindowHomeActivity.this);spinner.setAdapter(new ArrayAdapter<>(WindowHomeActivity.this,android.R.layout.simple_spinner_dropdown_item,labels));int selected=ids.indexOf(sourceSlot);spinner.setSelection(selected>=0?selected:0);spinner.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long item){sourceSlot=ids.get(pos);}public void onNothingSelected(android.widget.AdapterView<?> p){}});body.addView(spinner);}DesignUi.note(body,"登录、Cookie、聊天、草稿和环境自检基线分别保存。这里的复制只涉及网络配置。");DesignUi.action(body,"下一步：确认创建 →",true,()->{step=2;render();});}
      if(step==2){DesignUi.field(body,"窗口名称",title);DesignUi.field(body,"平台","ChatGPT");DesignUi.field(body,"配置来源",sourceType==2?"自定义配置":Profiles.display(WindowHomeActivity.this,sourceType==0?AppSettings.defaultSlot(WindowHomeActivity.this):sourceSlot));CheckBox selected=new CheckBox(WindowHomeActivity.this);selected.setText("设为默认窗口");selected.setChecked(makeDefault);selected.setOnCheckedChangeListener((b,c)->makeDefault=c);body.addView(selected);DesignUi.action(body,"创建并打开",true,()->create());}}
    void create(){if(preparing)return;preparing=true;Context source=Profiles.context(WindowHomeActivity.this,sourceType==0?AppSettings.defaultSlot(WindowHomeActivity.this):sourceSlot);boolean clone=sourceType!=2;dialog.dismiss();new Thread(()->{String error="";try{Profiles.prepare(source,id,clone);Profiles.rename(source,id,title);if(makeDefault)AppSettings.defaultSlot(source,id);}catch(Exception e){error="窗口准备失败，请重试";}String failure=error;handler.post(()->{preparing=false;if(isFinishing()||isDestroyed())return;lastSignature="";refresh();if(failure.isEmpty())openWindow(id,sourceType==2?"network":"chat");else SavedFileActions.toast(WindowHomeActivity.this,failure);});},"window-create").start();}
  }
}
