package local.pocketchat;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.os.*;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;

/** Native launcher: listing windows never creates a ChatSession or starts its network. */
public class WindowHomeActivity extends Activity {
  static final int BG=0xff030b1a, CARD=0xff071a30, WHITE=0xffedf5ff, MUTED=0xff9baeca, CYAN=0xff25cfff;
  LinearLayout root,cards,filters;TextView count;EditText search;int filter;final Handler handler=new Handler(Looper.getMainLooper());boolean preparing;
  final Runnable update=()->{refresh();handler.postDelayed(this.update,5000);};
  int dp(int n){return Ui.dp(this,n);}
  TextView text(String s,int size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);v.setIncludeFontPadding(false);return v;}
  GradientDrawable surface(int color,int stroke){GradientDrawable d=Ui.shape(this,color,16);d.setStroke(dp(1),stroke);return d;}
  Button button(String s,Runnable action){Button b=new Button(this);b.setAllCaps(false);b.setText(s);b.setTextSize(14);b.setTextColor(WHITE);b.setMinWidth(0);b.setMinimumWidth(0);b.setBackground(surface(CARD,0xff17426c));b.setPadding(dp(12),0,dp(12),0);b.setOnClickListener(v->action.run());return b;}
  @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);getWindow().getDecorView().setSystemUiVisibility(0);root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(BG);root.setFitsSystemWindows(true);ScrollView scroll=new ScrollView(this);LinearLayout body=new LinearLayout(this);body.setOrientation(1);body.setPadding(dp(18),dp(18),dp(18),dp(20));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
    TextView brand=text("元婴期院士",27,WHITE);brand.setTypeface(Typeface.DEFAULT_BOLD);body.addView(brand);TextView sub=text("Android ChatGPT 网页客户端",13,MUTED);sub.setPadding(0,dp(5),0,dp(24));body.addView(sub);
    TextView heading=text("独立窗口",24,WHITE);heading.setTypeface(Typeface.DEFAULT_BOLD);body.addView(heading);TextView hint=text("选择窗口进入聊天，登录与本机数据分别保存",13,MUTED);hint.setPadding(0,dp(8),0,dp(14));body.addView(hint);
    count=text("窗口总数",17,WHITE);count.setPadding(dp(16),dp(14),dp(16),dp(14));count.setBackground(surface(CARD,0xff2558bc));body.addView(count,new LinearLayout.LayoutParams(-1,-2));
    Button create=button("＋  创建新窗口",()->createWindow());create.setTextSize(18);GradientDrawable gradient=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{0xff086cff,0xff641eff});gradient.setCornerRadius(dp(16));gradient.setStroke(dp(1),CYAN);create.setBackground(gradient);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(54));cp.topMargin=dp(14);body.addView(create,cp);
    search=new EditText(this);search.setSingleLine(true);search.setTextSize(14);search.setTextColor(WHITE);search.setHintTextColor(MUTED);search.setHint("搜索窗口名称");search.setPadding(dp(14),0,dp(14),0);search.setBackground(surface(CARD,0xff17426c));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(46));sp.topMargin=dp(16);body.addView(search,sp);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int c,int after){}public void onTextChanged(CharSequence s,int start,int before,int c){refresh();}public void afterTextChanged(Editable e){}});
    filters=new LinearLayout(this);LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(-1,dp(42));fp.topMargin=dp(12);body.addView(filters,fp);cards=new LinearLayout(this);cards.setOrientation(1);body.addView(cards);
    LinearLayout bar=new LinearLayout(this);bar.setPadding(dp(12),dp(8),dp(12),dp(8));for(String label:new String[]{"聊天","下载","窗口","设置"}){Button b=button(label,()->{if(label.equals("窗口")){filter=0;search.setText("");refresh();}else if(label.equals("下载"))startActivity(new Intent(this,DownloadCenterActivity.class));else openWindow(lastWindow(),label.equals("设置")?"settings":"chat");});if(label.equals("窗口"))b.setTextColor(CYAN);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,dp(44),1);bp.setMargins(dp(3),0,dp(3),0);bar.addView(b,bp);}root.addView(bar);setContentView(root);refresh();
  }
  @Override protected void onResume(){super.onResume();handler.removeCallbacks(update);handler.post(update);}
  @Override protected void onPause(){handler.removeCallbacks(update);super.onPause();}
  @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);refresh();}
  Set<Integer> live(){Set<Integer> out=new HashSet<>();try{List<ActivityManager.RunningAppProcessInfo> rows=getSystemService(ActivityManager.class).getRunningAppProcesses();if(rows!=null)for(ActivityManager.RunningAppProcessInfo r:rows)out.add(r.pid);}catch(Exception ignored){}return out;}
  int lastWindow(){int selected=0;long time=0;JSONArray rows=ProfileCatalog.get(this).list();for(int i=0;i<rows.length();i++){JSONObject r=rows.optJSONObject(i);if(r.optBoolean("created")&&r.optLong("opened")>time){time=r.optLong("opened");selected=r.optInt("slot");}}return selected;}
  void refresh(){if(cards==null)return;JSONArray rows=ProfileCatalog.get(this).list();Set<Integer> running=live();int total=0,favorites=0,alive=0;for(int i=0;i<rows.length();i++){JSONObject r=rows.optJSONObject(i);if(r.optBoolean("created")){total++;if(r.optBoolean("favorite"))favorites++;if(running.contains(r.optInt("pid"))&&System.currentTimeMillis()-r.optLong("seen")<60000)alive++;}}count.setText("窗口总数  "+total+" / "+Profiles.MAX+"\n各窗口独立配置网络");filters.removeAllViews();String[] names={"全部 ("+total+")","收藏 ("+favorites+")","已打开 ("+alive+")"};for(int i=0;i<3;i++){final int selected=i;Button b=button(names[i],()->{filter=selected;refresh();});b.setTextSize(12);if(filter==i)b.setBackground(surface(0xff103f9a,CYAN));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1);p.setMargins(i==0?0:dp(6),0,0,0);filters.addView(b,p);}cards.removeAllViews();String query=search.getText().toString().trim().toLowerCase(Locale.ROOT);int shown=0;
    for(int i=0;i<rows.length();i++){JSONObject r=rows.optJSONObject(i);if(!r.optBoolean("created"))continue;boolean live=running.contains(r.optInt("pid"))&&System.currentTimeMillis()-r.optLong("seen")<60000;if(filter==1&&!r.optBoolean("favorite")||filter==2&&!live||!r.optString("name").toLowerCase(Locale.ROOT).contains(query))continue;shown++;int id=r.optInt("slot");LinearLayout card=new LinearLayout(this);card.setOrientation(1);card.setPadding(dp(14),dp(14),dp(14),dp(14));card.setBackground(surface(CARD,0xff1674be));card.setContentDescription("打开窗口："+r.optString("name"));card.setClickable(true);card.setFocusable(true);card.setOnClickListener(v->openWindow(id,"chat"));
      LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView title=text((r.optBoolean("favorite")?"★ ":"")+r.optString("name"),20,WHITE);title.setTypeface(Typeface.DEFAULT_BOLD);top.addView(title,new LinearLayout.LayoutParams(0,-2,1));Button menu=button("⋮",()->menu(id));menu.setContentDescription("窗口操作："+r.optString("name"));top.addView(menu,new LinearLayout.LayoutParams(dp(40),dp(40)));card.addView(top);TextView info=text("chatgpt.com   ·   "+(live?r.optBoolean("waiting")?"等待回复":"已打开":"未运行"),14,live?0xff28dfbd:MUTED);info.setPadding(0,dp(5),0,dp(10));card.addView(info);card.addView(text("独立存储   ·   Cookie 隔离",13,CYAN));TextView opened=text(r.optLong("opened")>0?"上次打开  "+android.text.format.DateFormat.format("MM-dd HH:mm",r.optLong("opened")):"点此进入窗口",12,MUTED);opened.setPadding(0,dp(10),0,0);card.addView(opened);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(12);cards.addView(card,p);
    }if(shown==0){TextView empty=text("没有符合条件的窗口",15,MUTED);empty.setPadding(0,dp(24),0,dp(24));cards.addView(empty);}
  }
  void menu(int id){JSONObject row=ProfileCatalog.get(this).item(id);new AlertDialog.Builder(this).setTitle(row.optString("name")).setItems(new String[]{"打开窗口","编辑窗口","修改名称",row.optBoolean("favorite")?"取消收藏":"收藏窗口","网络设置"},(d,n)->{if(n==0)openWindow(id,"chat");if(n==1)openWindow(id,"edit");if(n==2)rename(id);if(n==3){ProfileCatalog.get(this).favorite(id,!row.optBoolean("favorite"));refresh();}if(n==4)openWindow(id,"network");}).setNegativeButton("取消",null).show();}
  void rename(int id){EditText name=new EditText(this);name.setSingleLine(true);name.setText(Profiles.display(this,id));AlertDialog d=new AlertDialog.Builder(this).setTitle("修改窗口名称").setView(name).setPositiveButton("保存",null).setNegativeButton("取消",null).create();d.setOnShowListener(v->d.getButton(-1).setOnClickListener(w->{String value=name.getText().toString().trim();if(value.isEmpty()||value.length()>24){name.setError("名称需要 1–24 字");return;}Profiles.rename(this,id,value);d.dismiss();refresh();}));d.show();}
  void openWindow(int id,String action){if(id<0||id>=Profiles.MAX)return;if(id>0&&Build.VERSION.SDK_INT<28){Toast.makeText(this,"独立窗口需要 Android 9 或更新版本",Toast.LENGTH_SHORT).show();return;}ProfileCatalog.get(this).opened(id);startActivity(new Intent(this,Profiles.activity(id)).putExtra("openWindowAction",action).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_REORDER_TO_FRONT));}
  void createWindow(){if(preparing)return;if(Build.VERSION.SDK_INT<28){Toast.makeText(this,"独立窗口需要 Android 9 或更新版本",Toast.LENGTH_SHORT).show();return;}JSONArray rows=ProfileCatalog.get(this).list();int next=-1;for(int i=1;i<rows.length();i++)if(!rows.optJSONObject(i).optBoolean("created")){next=i;break;}if(next<0){Toast.makeText(this,"已达到 8 个窗口",Toast.LENGTH_SHORT).show();return;}final int id=next;EditText name=new EditText(this);name.setSingleLine(true);name.setText("窗口 "+(id+1));LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(dp(20),0,dp(20),0);box.addView(name);CheckBox copy=new CheckBox(this);copy.setText("复制上次使用窗口的网络配置");copy.setChecked(true);box.addView(copy);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("创建新窗口").setView(box).setPositiveButton("创建并打开",null).setNegativeButton("取消",null).create();dialog.setOnShowListener(v->dialog.getButton(-1).setOnClickListener(w->{String title=name.getText().toString().trim();if(title.isEmpty()||title.length()>24){name.setError("名称需要 1–24 字");return;}boolean clone=copy.isChecked();Context source=Profiles.context(this,lastWindow());preparing=true;dialog.dismiss();new Thread(()->{String error="";try{Profiles.prepare(source,id,clone);Profiles.rename(source,id,title);}catch(Exception e){error="窗口准备失败，已有数据已保留";}String failure=error;handler.post(()->{preparing=false;if(isFinishing()||isDestroyed())return;refresh();if(failure.isEmpty())openWindow(id,"chat");else Toast.makeText(this,failure,Toast.LENGTH_LONG).show();});},"window-create").start();}));dialog.show();}
}
