package local.pocketchat;
import android.app.ActivityManager;import android.content.*;import android.os.Bundle;import org.json.*;import java.util.*;import java.nio.charset.StandardCharsets;

/** Read model shared by the chat strip and window cards; missing/stale readings stay explicit. */
final class WindowNetworkState {
  final int slot;final String name,state,region,ip,latency,entry,subscription,entryMode;final JSONObject config,runtime;final boolean internal,connected;final long now;
  WindowNetworkState(Context c,JSONObject row,JSONObject config,JSONObject runtime,boolean live,long now){
    this.slot=row.optInt("slot");name=row.optString("name");this.config=config;this.runtime=runtime;this.now=now;SharedPreferences prefs=Profiles.context(c,slot).getSharedPreferences("chat",0);internal="internal".equals(runtime.optString("mode",prefs.getString("networkMode","external")));boolean configured=runtime.has("configured")?runtime.optBoolean("configured"):prefs.getBoolean("networkConfigured",false);boolean fresh=live&&now>=runtime.optLong("at")-60000&&now-runtime.optLong("at")<45000;
    connected=fresh&&runtime.optBoolean("connected");state=!configured?"未配置":!fresh?"未运行":runtime.optBoolean("offline")?"离线":runtime.optBoolean("blocked")?"出口异常":runtime.optBoolean("starting")?"连接中":!runtime.optString("issue").isEmpty()||runtime.optLong("delayAt")>0&&now-runtime.optLong("delayAt")<90000&&runtime.optInt("delay",-1)<=0&&internal?"需检查":connected?"正常":"未连接";
    region=runtime.optBoolean("blocked")?"":config.optString("exitRegion");subscription=internal?NetworkCatalog.subscriptionName(config):(runtime.has("proxy")?runtime.optBoolean("proxy"):!prefs.getString("proxy","").isEmpty())?"应用代理":"手机网络 / VPN";
    entryMode="manual".equals(config.optString("entryMode"))?"手动指定":"random".equals(config.optString("entryMode"))?"自动随机":"自动选择";
    boolean sameExit=internal&&NetworkCatalog.exitId(config).equals(runtime.optString("exitId")),sameSubscription=internal&&NativeNetwork.hash(config.optString("subscriptionUrl")).equals(runtime.optString("subscriptionId"));
    ip=sameExit?runtime.optBoolean("blocked")&&!runtime.optString("observedIp").isEmpty()?runtime.optString("observedIp"):runtime.optString("ip"):"";entry=sameSubscription?runtime.optString("entry"):config.optString("entry");
    long measured=runtime.optLong("delayAt");boolean measuredHere=sameExit&&sameSubscription&&entry.equals(runtime.optString("delayEntry"));int delay=runtime.optInt("delay",-1);
    latency=!connected||!measuredHere||measured<=0?"延迟未测":now-measured>90000||now<measured-60000?"延迟待更新":delay>0?delay+" ms":"探测未通过";
  }
  int color(){return connected&&state.equals("正常")?ReferenceUi.GREEN:state.equals("离线")||state.equals("出口异常")?ReferenceUi.RED:state.equals("需检查")||state.equals("连接中")?ReferenceUi.ORANGE:ReferenceUi.MUTED;}
  String mainline(){return (region.isEmpty()?"地区未标注":region)+" · "+(ip.isEmpty()?"IP 未核验":connected?ip:"上次 "+ip)+" · "+latency;}
  String strip(){return mainline()+" · "+(state.equals("正常")?"已连接":state);}
  String subline(){if(!internal)return subscription;if(config.optString("subscriptionUrl").isEmpty())return "尚未选择订阅与固定出口";return subscription+" · "+entryMode+" · "+(entry.isEmpty()?"入口待选择":NativeNetwork.display(entry));}
  static JSONObject live(ChatSession s,NativeNetwork n){long now=System.currentTimeMillis();SharedPreferences prefs=n.context.getSharedPreferences("chat",0);boolean internal="internal".equals(prefs.getString("networkMode","external"));JSONObject config=n.settings==null?new JSONObject():n.settings;JSONObject q=n.quality.stats(n.currentEntry,now);return J.obj("at",now,"pid",android.os.Process.myPid(),"mode",prefs.getString("networkMode","external"),"configured",prefs.getBoolean("networkConfigured",false),"proxy",!prefs.getString("proxy","").isEmpty(),"connected",s==null?n.ready&&n.coreAlive():s.networkReady&&!s.offline&&(!internal||n.ready&&n.coreAlive()),"offline",s!=null&&s.offline,"starting",n.starting||s!=null&&s.connecting,"blocked",internal&&n.recoveryBlocked,"issue",s==null?n.recoveryBlocked?n.message:"":s.networkIssue,"exitId",internal?n.fingerprint:"","subscriptionId",internal?NativeNetwork.hash(config.optString("subscriptionUrl")):"","ip",internal?n.exitIp:"","observedIp",internal?n.observedExitIp:"","verifiedAt",internal?n.lastVerified:0,"entry",internal?n.currentEntry:"","delay",internal?q.optInt("latest",-1):-1,"delayAt",internal?q.optLong("lastAt"):0,"delayEntry",internal?n.currentEntry:"");}
  static WindowNetworkState current(MainActivity a){NativeNetwork n=NativeNetwork.get(a);JSONObject config=n.settings==null?new JSONObject():n.settings;return new WindowNetworkState(a,ProfileCatalog.get(a).item(Profiles.slot(a)),config,live(a.session,n),true,System.currentTimeMillis());}
  static JSONArray windows(Context c){JSONArray out=new JSONArray(),rows=ProfileCatalog.get(c).list();Set<Integer> processes=new HashSet<>();try{List<ActivityManager.RunningAppProcessInfo> all=c.getSystemService(ActivityManager.class).getRunningAppProcesses();if(all!=null)for(ActivityManager.RunningAppProcessInfo p:all)if(p.uid==android.os.Process.myUid())for(int slot=0;slot<Profiles.MAX;slot++)if(p.processName.equals(c.getPackageName()+(slot==0?"":":profile"+slot)))processes.add(slot);}catch(Exception ignored){}
    for(int i=0;i<rows.length();i++){JSONObject row=rows.optJSONObject(i);if(!row.optBoolean("created"))continue;int slot=row.optInt("slot");SecretStore vault=new SecretStore(Profiles.context(c,slot));JSONObject state=new JSONObject();try{byte[] raw=vault.get("network-ui");if(raw!=null)state=J.parse(new String(raw,StandardCharsets.UTF_8));}catch(Exception ignored){}
      boolean running=processes.contains(slot);if(running)try{Bundle current=c.getContentResolver().call(NetworkBridge.uri(c,slot),"state",null,null);if(current!=null)state=J.parse(current.getString("json","{}"));}catch(Exception ignored){}
      out.put(J.obj("row",row,"config",vault.settings(),"runtime",state,"live",running));}return out;
  }
  static final java.util.concurrent.ExecutorService snapshots=java.util.concurrent.Executors.newSingleThreadExecutor();static long savedAt;static String savedSignature="";
  static synchronized void save(Context c,ChatSession s,NativeNetwork n){if(!n.root.getName().equals("network-runtime"))return;try{JSONObject value=live(s,n);String signature=value.optBoolean("connected")+"|"+value.optBoolean("starting")+"|"+value.optBoolean("blocked")+"|"+value.optString("issue")+"|"+value.optString("ip")+"|"+value.optString("entry")+"|"+value.optLong("delayAt");long now=System.currentTimeMillis();if(signature.equals(savedSignature)&&now-savedAt<5000)return;savedAt=now;savedSignature=signature;snapshots.execute(()->{try{new SecretStore(c).put("network-ui",value.toString().getBytes(StandardCharsets.UTF_8));}catch(Exception ignored){}});}catch(Exception ignored){}}
}
