package local.pocketchat;
import android.content.*;import android.net.Uri;import android.os.*;import android.webkit.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.zip.*;

public class ActionsTestActivity extends MainActivity {
 JSONArray checks=new JSONArray();byte[] word,pdf;int saves=0;String userId,replyId;JSONArray files;
 void check(String n,boolean p){checks.put(J.obj("name",n,"pass",p));}
 byte[] docx()throws Exception{ByteArrayOutputStream bytes=new ByteArrayOutputStream();try(ZipOutputStream z=new ZipOutputStream(bytes)){String[] names={"[Content_Types].xml","_rels/.rels","word/document.xml"},values={"<Types xmlns='http://schemas.openxmlformats.org/package/2006/content-types'><Default Extension='rels' ContentType='application/vnd.openxmlformats-package.relationships+xml'/><Default Extension='xml' ContentType='application/xml'/><Override PartName='/word/document.xml' ContentType='application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml'/></Types>","<Relationships xmlns='http://schemas.openxmlformats.org/package/2006/relationships'><Relationship Id='rId1' Type='http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument' Target='word/document.xml'/></Relationships>","<w:document xmlns:w='http://schemas.openxmlformats.org/wordprocessingml/2006/main'><w:body><w:p><w:r><w:t>Download fixture</w:t></w:r></w:p></w:body></w:document>"};for(int i=0;i<names.length;i++){z.putNextEntry(new ZipEntry(names[i]));z.write(values[i].getBytes(StandardCharsets.UTF_8));z.closeEntry();}}return bytes.toByteArray();}
 byte[] pdf()throws Exception{ByteArrayOutputStream bytes=new ByteArrayOutputStream();android.graphics.pdf.PdfDocument d=new android.graphics.pdf.PdfDocument();android.graphics.pdf.PdfDocument.Page p=d.startPage(new android.graphics.pdf.PdfDocument.PageInfo.Builder(360,480,1).create());android.graphics.Paint paint=new android.graphics.Paint();paint.setTextSize(24);p.getCanvas().drawText("PDF download fixture",20,60,paint);d.finishPage(p);d.writeTo(bytes);d.close();return bytes.toByteArray();}
 @Override public void onCreate(Bundle b){try{word=docx();pdf=pdf();}catch(Exception e){throw new RuntimeException(e);}getSharedPreferences("chat",0).edit().clear().commit();super.onCreate(b);setRequestedOrientation(1);handler.postDelayed(()->begin(),4000);}
 @Override void startNetwork(){prefs.edit().putBoolean("networkConfigured",true).putString("networkMode","external").putBoolean("requireExternalVpn",false).commit();session.networkReady=true;session.prefs.edit().putBoolean("requireExternalVpn",false).commit();session.guard.setBlocked(false);remote.loadUrl(ORIGIN);}
 @Override WebViewClient remoteClient(){return new WebViewClient(){@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){try{String html=asset("fixture-actions.html").replace("__DOCX__",android.util.Base64.encodeToString(word,android.util.Base64.NO_WRAP)).replace("__PDF__",android.util.Base64.encodeToString(pdf,android.util.Base64.NO_WRAP));return new WebResourceResponse("text/html","UTF-8",new ByteArrayInputStream(html.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){return blocked();}}};}
 @Override public void startActivityForResult(Intent i,int request){if(request==FileDownloads.SAVE&&!getIntent().getBooleanExtra("manualSave",false)){saves++;String ext=i.getStringExtra(Intent.EXTRA_TITLE).endsWith("pdf")?"pdf":"docx";handler.postDelayed(()->onActivityResult(request,RESULT_OK,new Intent().setData(Uri.parse("content://local.pocketchat.download-fixture/sample"+saves+"."+ext)).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION)),100);}else super.startActivityForResult(i,request);}
 void begin(){runDriver("transcript",new JSONObject(),r->{JSONArray items=r.optJSONArray("entries");if(items==null||items.length()!=2){check("Fixture transcript available",false);write();return;}userId=items.optJSONObject(0).optString("id");replyId=items.optJSONObject(1).optString("id");files=items.optJSONObject(1).optJSONArray("downloads");check("Word and PDF buttons become native download cards",files!=null&&files.length()==2);if(getIntent().getBooleanExtra("manualSave",false)){downloads.open(replyId,files.optJSONObject(0).optString("key"));return;}reader.evaluateJavascript("document.querySelectorAll('.download-card').length",n->check("Reader renders both download cards","2".equals(n)));reader.evaluateJavascript("(()=>{window.pocketActions=[];document.querySelector('.message').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true}));return JSON.stringify(window.pocketActions.splice(0));})()",raw->{try{JSONArray actions=new JSONArray((String)new JSONTokener(raw).nextValue());check("Long press routes to message actions",actions.length()==1&&actions.getJSONObject(0).optString("action").equals("message-menu"));}catch(Exception e){check("Long press routes to message actions",false);}});messageActions.edit(items.optJSONObject(0));check("Edit copies question into composer without sending",input.getText().toString().equals("Initial fixture prompt"));input.setText("Keep this new draft");states();messageActions.regenerate(replyId);handler.postDelayed(()->check("Old completed response cannot finish regeneration",session.pending!=null&&!session.pending.optBoolean("regenerationObserved")),3500);handler.postDelayed(()->regenerated(),11500);});}
 void states(){JSONObject job=J.obj("startedAt",System.currentTimeMillis());check("Thinking status uses observed phase",ReplyState.describe(J.obj("submitted",true,"thinking",true,"busy",true),job,0,0).startsWith("正在思考"));check("Search status uses observed phase",ReplyState.describe(J.obj("submitted",true,"searching",true,"busy",true),job,0,0).startsWith("正在搜索"));check("Generation status distinguished",ReplyState.describe(J.obj("submitted",true,"busy",true,"markdown","Text"),job,0,0).startsWith("正在生成"));check("Long wait offers recovery rather than fake completion",ReplyState.describe(J.obj("submitted",true,"busy",true),job,0,130000).contains("点按检查"));NativeNetwork n=NativeNetwork.get(this);prefs.edit().putString("networkMode","internal").commit();n.exitIp="203.0.113.10";n.observedExitIp="203.0.113.10";n.lastVerified=System.currentTimeMillis();n.ready=true;check("Header shows verified exit IP",ExitIpUi.value(session,n).contains("203.0.113.10"));session.offline=true;check("Offline IP explicitly marked as last known",ExitIpUi.value(session,n).contains("上次")&&ExitIpUi.value(session,n).contains("离线"));session.offline=false;n.recoveryBlocked=true;n.observedExitIp="203.0.113.11";check("Changed exit displays new IP and stop warning",ExitIpUi.value(session,n).contains("203.0.113.11")&&ExitIpUi.value(session,n).contains("已停止"));n.recoveryBlocked=false;n.ready=false;prefs.edit().putString("networkMode","external").putBoolean("requireExternalVpn",false).commit();}
 void regenerated(){check("Regeneration completes and unlocks send",session.pending==null&&send.isEnabled());check("Regeneration preserves new draft",input.getText().toString().equals("Keep this new draft"));remote.evaluateJavascript("JSON.stringify({regenerate:regenerateCount,send:sendCount})",raw->{try{JSONObject o=new JSONObject((String)new JSONTokener(raw).nextValue());check("Regeneration clicks once and never resends prompt",o.optInt("regenerate")==1&&o.optInt("send")==0);}catch(Exception e){check("Regeneration count readable",false);}if(files==null||files.length()<2){write();return;}downloads.open(replyId,files.optJSONObject(0).optString("key"));handler.postDelayed(()->downloadedWord(),5000);});}
 void downloadedWord(){boolean equal=false;try{equal=Arrays.equals(word,java.nio.file.Files.readAllBytes(new File(getCacheDir(),"sample1.docx").toPath()));}catch(Exception ignored){}check("Word download matches original bytes",equal);check("Saved files recorded for reopening",prefs.getString("downloadHistory","").contains("sample.docx"));if(downloads.noticeDialog!=null)downloads.noticeDialog.dismiss();downloads.open(replyId,files.optJSONObject(1).optString("key"));downloads.fail(downloads.ticket,"模拟下载中断");handler.postDelayed(()->{check("Failed download offers retry",downloads.noticeDialog!=null&&!downloads.active);if(downloads.noticeDialog!=null)downloads.noticeDialog.getButton(-1).performClick();handler.postDelayed(()->downloadedPdf(),5500);},500);}
 void downloadedPdf(){boolean equal=false;try{equal=Arrays.equals(pdf,java.nio.file.Files.readAllBytes(new File(getCacheDir(),"sample2.pdf").toPath()));}catch(Exception ignored){}check("Retry downloads PDF without corrupting bytes",equal);check("No unfinished download remains",!downloads.active);check("HTTPS validation rejects script URLs",!FileDownloads.https("javascript:alert(1)")&&!FileDownloads.https("https://user:pass@example.com/x"));if(downloads.noticeDialog!=null)downloads.noticeDialog.dismiss();write();}
 void write(){try{J.write(new File(getFilesDir(),"actions-results.json"),J.obj("checks",checks).toString(2));}catch(Exception ignored){}}
}
