package local.pocketchat;
import android.os.*;import android.webkit.*;import org.json.*;import java.io.*;

public class AttachmentGateTestActivity extends MainActivity {
 JSONArray checks=new JSONArray();JSONArray names=new JSONArray().put("sample.pdf");
 void check(String n,boolean b){checks.put(J.obj("name",n,"pass",b));}
 @Override void startNetwork(){prefs.edit().putString("networkMode","external").putBoolean("requireExternalVpn",false).putBoolean("networkConfigured",true).commit();session.networkReady=true;session.prefs.edit().putBoolean("requireExternalVpn",false).commit();session.guard.setBlocked(false);remote.loadUrl(ORIGIN);}
 @Override WebViewClient remoteClient(){return new WebViewClient(){@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){try{return new WebResourceResponse("text/html","UTF-8",getAssets().open("fixture-media.html"));}catch(Exception e){return blocked();}}};}
 @Override public void onCreate(Bundle b){getSharedPreferences("chat",0).edit().clear().commit();super.onCreate(b);handler.postDelayed(()->begin(),2500);}
 void begin(){remote.evaluateJavascript("uploads.innerHTML='<div data-file-name=\"sample.pdf\"><span>sample.pdf</span><span role=\"progressbar\" aria-valuenow=\"25\" aria-valuemin=\"0\" aria-valuemax=\"100\">Uploading</span><button aria-label=\"Remove file sample.pdf\">Remove</button></div>'",r->session.asyncDriver("attachment-state",J.obj("names",names,"url",ORIGIN),2500,s->{JSONObject f=s.optJSONArray("files").optJSONObject(0);check("Upload percentage comes from webpage progress",f.optInt("progress")==25&&f.optString("state").equals("uploading"));check("Readable size shown without inventing unknown sizes",Attachments.sizeLabel(2048).equals("2.0 KB")&&Attachments.sizeLabel(-1).equals("大小未知"));remote.evaluateJavascript("document.querySelector('[role=progressbar]').remove()",unused->session.asyncDriver("attachment-state",J.obj("names",names,"url",ORIGIN),2500,ready->{check("Stable webpage card is reported ready",ready.optJSONArray("files").optJSONObject(0).optString("state").equals("ready"));missing();}));}));}
 JSONObject args(){return J.obj("text","attachment gate","attachmentNames",names,"expectedUrl",ORIGIN,"expectedModel","Thinking","expectedEffort","Extra High");}
 void missing(){session.asyncDriver("fill",args(),4000,filled->{check("Ready attachment allows drafting",filled.optBoolean("ok"));remote.evaluateJavascript("window.originalCard=uploads.firstElementChild;uploads.replaceChildren()",r->runDriver("submit",args(),result->{check("Removed attachment blocks final send click",!result.optBoolean("ok")&&result.optBoolean("notClicked"));remote.evaluateJavascript("uploads.append(originalCard,originalCard.cloneNode(true))",unused->runDriver("submit",args(),duplicate->{check("Duplicate filename blocks final send click",!duplicate.optBoolean("ok")&&duplicate.optBoolean("notClicked"));remote.evaluateJavascript("uploads.lastElementChild.remove();originalCard.dataset.uploadState='uploading'",x->runDriver("submit",args(),uploading->{check("Upload restarting before click blocks submission",!uploading.optBoolean("ok")&&uploading.optBoolean("notClicked"));remote.evaluateJavascript("window.sendCount",count->{check("No unsafe attachment message was sent","0".equals(count));remote.evaluateJavascript("originalCard.dataset.uploadState='ready'",v->runDriver("submit",args(),good->{check("Ready unique attachment permits submission",good.optBoolean("ok"));remote.evaluateJavascript("window.sendCount",n->{check("Ready attachment is submitted exactly once","1".equals(n));write();});}));});}));}));}));});}
 void write(){try{J.write(new File(getFilesDir(),"attachment-gate-results.json"),J.obj("checks",checks).toString(2));}catch(Exception ignored){}}
}
