package local.pocketchat;
import android.os.*;
import android.webkit.*;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
public class CompletionTestActivity extends MainActivity {
 JSONArray checks=new JSONArray();int attempts=0;
 void check(String n,boolean ok){checks.put(J.obj("name",n,"pass",ok));}
 @Override void startNetwork(){networkReady=true;session.networkReady=true;session.prefs.edit().putBoolean("requireExternalVpn",false).commit();session.guard.setBlocked(false);remote.loadUrl(ORIGIN);}
 @Override WebViewClient remoteClient(){return new WebViewClient(){@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){try{String html=asset("fixture.html");html=html.replace("const reply=document.createElement('article');reply.dataset.messageAuthorRole='assistant';","const turn=document.createElement('section');turn.dataset.turn='assistant';turn.dataset.testid='conversation-turn-2';turn.innerHTML='<div><div data-conversation-screenshot-content><div class=body-wrap></div><div class=turn-actions></div></div></div>';turns.append(turn);const reply=document.createElement('div');reply.dataset.messageAuthorRole='assistant';").replace("turns.append(reply);","turn.querySelector('.body-wrap').append(reply);");html=html.replace(";stop.remove();},", ";const actions=turn.querySelector('.turn-actions');actions.append(reply.querySelector('button'));stop.remove();},");return new WebResourceResponse("text/html","UTF-8",new ByteArrayInputStream(html.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){return blocked();}}};}
 @Override public void onCreate(Bundle b){getSharedPreferences("chat",0).edit().clear().commit();super.onCreate(b);setRequestedOrientation(1);handler.postDelayed(()->begin(),2000);}
 void begin(){runDriver("inspect",new JSONObject(),s->{if(!s.optBoolean("composer")&&attempts++<15){handler.postDelayed(()->begin(),400);return;}input.setText("Completion fixture prompt");sendPrompt();handler.postDelayed(()->input.setText("keep my next draft"),2200);handler.postDelayed(()->complete(),7500);});}
 void complete(){check("Modern sibling action clears pending automatically",session.pending==null);check("Spinner stops after completed response",!session.status.equals("正在接收回复…")&&loading.band.getVisibility()!=android.view.View.VISIBLE);check("Next draft preserved",input.getText().toString().equals("keep my next draft"));check("Send reenabled",send.isEnabled());remote.evaluateJavascript("window.sendCount",r->{check("Completion does not resubmit","1".equals(r));runDriver("latest",J.obj("export",true),p->{check("Modern section actions recognized",p.optBoolean("terminal")&&!p.optBoolean("busy"));withoutCurrentAction();});});}
 void withoutCurrentAction(){remote.evaluateJavascript("document.querySelector('.turn-actions').replaceChildren();const old=document.createElement('section');old.dataset.turn='assistant';old.innerHTML='<button data-testid=copy-turn-action-button aria-label=\"Copy response\">Copy</button>';turns.prepend(old)",r->runDriver("latest",J.obj("export",true),p->{check("Previous response button cannot complete current reply",!p.optBoolean("terminal"));codeButton();}));}
 void codeButton(){remote.evaluateJavascript("document.querySelector('.body-wrap').insertAdjacentHTML('beforeend','<pre><button data-testid=copy-turn-action-button aria-label=\"Copy response\">Copy</button></pre>')",r->runDriver("latest",J.obj("export",true),p->{check("Code copy button cannot complete current reply",!p.optBoolean("terminal"));streaming();}));}
 void streaming(){remote.evaluateJavascript("document.querySelector('.turn-actions').innerHTML='<button data-testid=copy-turn-action-button aria-label=\"Copy response\">Copy</button>';document.body.insertAdjacentHTML('beforeend','<button data-testid=stop-button aria-label=Stop>Stop</button>')",r->runDriver("latest",J.obj("export",true),p->{check("Streaming remains busy even if actions are present",p.optBoolean("busy"));write();}));}
 void write(){try{J.write(new File(getFilesDir(),"completion-results.json"),J.obj("checks",checks).toString(2));}catch(Exception ignored){}}
}
