package local.pocketchat;
import android.os.*;import android.webkit.*;import android.view.*;import org.json.*;import java.io.*;

public class CompactModeTestActivity extends MainActivity {
 JSONArray checks=new JSONArray();void check(String n,boolean b){checks.put(J.obj("name",n,"pass",b));}
 @Override void startNetwork(){prefs.edit().putBoolean("networkConfigured",true).putString("networkMode","external").putBoolean("requireExternalVpn",false).commit();session.networkReady=true;session.prefs.edit().putBoolean("requireExternalVpn",false).commit();session.guard.setBlocked(false);remote.loadUrl(ORIGIN);}
 @Override WebViewClient remoteClient(){return new WebViewClient(){@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){try{return new WebResourceResponse("text/html","UTF-8",getAssets().open("fixture.html"));}catch(Exception e){return blocked();}}};}
 @Override public void onCreate(Bundle b){if(!getIntent().getBooleanExtra("restoreMode",false))getSharedPreferences("chat",0).edit().clear().commit();super.onCreate(b);handler.postDelayed(()->begin(),3000);}
 void begin(){if(getIntent().getBooleanExtra("restoreMode",false)){check("Web mode survives process restart",pageMode&&webTab.isSelected());check("Restored web mode hides native composer",composer.getVisibility()==View.GONE);check("Restored mode keeps a bounded app chrome without duplicate strips",toolbar.getHeight()>0&&toolbar.getHeight()<=dp(164)&&webNotice.getParent()==null&&exitIpLine.getParent()==null);write("compact-mode-restore-results.json");return;}check("Native mode is directly selectable",!pageMode&&nativeTab.isSelected());check("Header fits designed controls without excessive reserved space",toolbar.getHeight()>0&&toolbar.getHeight()<=dp(164));check("Network status lives in that same toolbar",networkLine.getParent()==toolbar&&networkLine.getHeight()<=toolbar.getHeight());check("IP and duplicate webpage strips consume no vertical space",exitIpLine.getParent()==null&&webNotice.getParent()==null);check("Operation status moved below content",status.getParent()==composer&&loading.band.getParent()==composer);input.setText("Native draft preserved");remote.evaluateJavascript("document.querySelector('textarea').value='Web draft preserved'",r->{String url=remote.getUrl();long epoch=session.navigationEpoch;input.requestFocus();webTab.performClick();check("Hidden native composer loses keyboard focus",!input.hasFocus());check("Web tab reveals original page and hides native controls",pageMode&&reader.getVisibility()==View.GONE&&composer.getVisibility()==View.GONE);check("Mode switching does not navigate or reload",url.equals(remote.getUrl())&&epoch==session.navigationEpoch);check("Web mode preference is saved",prefs.getBoolean("pageMode",false));networkLine.performClick();check("Network area opens detailed parameters",networkDialog!=null&&networkDialog.isShowing());if(networkDialog!=null)networkDialog.dismiss();nativeTab.performClick();check("Hidden webpage loses keyboard focus",!remote.hasFocus());check("Native tab restores reader and input",!pageMode&&reader.getVisibility()==View.VISIBLE&&composer.getVisibility()==View.VISIBLE);check("Switching modes preserves native draft",input.getText().toString().equals("Native draft preserved"));remote.evaluateJavascript("JSON.stringify({draft:document.querySelector('textarea').value,sends:window.sendCount})",raw->{try{JSONObject value=new JSONObject((String)new JSONTokener(raw).nextValue());check("Switching modes preserves original webpage draft",value.optString("draft").equals("Web draft preserved"));check("Mode switches never submit messages",value.optInt("sends")==0);}catch(Exception e){check("Web draft result readable",false);}webTab.performClick();write("compact-mode-results.json");});});}
 void write(String name){try{J.write(new File(getFilesDir(),name),J.obj("checks",checks).toString(2));}catch(Exception ignored){}}
}
