package local.pocketchat;

import android.os.*;
import android.app.PendingIntent;
import android.app.Notification;
import org.json.*;
import java.io.*;
import java.util.function.BooleanSupplier;

public class ContinuityTestActivity extends ContinuityFixtureActivity {
  final JSONArray checks=new JSONArray();String instance="";int beforeDocuments;long recoveryStart,recoveryDuration;String originalDraft="保留网页草稿\n  第二行空格  ";
  void check(String name,boolean pass){checks.put(J.obj("name",name,"pass",pass));}
  void js(String code,java.util.function.Consumer<JSONObject> cb){remote.evaluateJavascript(code,raw->cb.accept(J.parse(raw)));}
  void later(Runnable run){handler.postDelayed(run,160);}
  void waitFor(String name,BooleanSupplier condition,int remaining,Runnable done){if(condition.getAsBoolean()){check(name,true);done.run();}else if(remaining<=0){check(name,false);write("Timeout: "+name);}else handler.postDelayed(()->waitFor(name,condition,remaining-1,done),100);}
  @Override public void onCreate(Bundle b){if(!getPackageName().endsWith(".test"))throw new IllegalStateException("Isolated test required");documents.set(0);heads.set(0);failHead=false;nextDraft="";getSharedPreferences("chat",0).edit().clear().putBoolean("pageMode",true).putBoolean("webNotificationAsked",true).putBoolean("networkConfigured",true).putString("networkMode","external").putBoolean("requireExternalVpn",false).putString("conversation",ORIGIN+"c/one").commit();super.onCreate(b);handler.postDelayed(()->waitFor("Initial fixture is usable",()->!session.navigating&&session.entries.length()==2&&session.networkReady,60,()->preserve()),100);}
  void preserve(){js("(()=>{document.querySelector('textarea').value="+JSONObject.quote(originalDraft)+";window.scrollTo(0,500);return {instance:pageInstance};})()",p->{instance=p.optString("instance");beforeDocuments=documents.get();recoveryStart=SystemClock.elapsedRealtime();session.reconnect();waitFor("Idle reconnect completes",()->!session.connecting&&session.networkReady&&session.trace.mode.equals("保留现有网页"),60,()->{
    recoveryDuration=SystemClock.elapsedRealtime()-recoveryStart;js("({instance:pageInstance,draft:document.querySelector('textarea').value,scroll:document.scrollingElement.scrollTop,sends:sendCount})",r->{check("Idle reconnect reuses existing document",instance.equals(r.optString("instance"))&&documents.get()==beforeDocuments);check("Idle reconnect preserves exact multiline draft",originalDraft.equals(r.optString("draft")));check("Idle reconnect preserves scroll position",Math.abs(r.optDouble("scroll")-500)<3);check("Reconnect checks website reachability without submitting",heads.get()>0&&r.optInt("sends")==0);check("Trace records retained-page path",session.trace.mode.equals("保留现有网页"));failedHead();});
  });});}
  void failedHead(){failHead=true;beforeDocuments=documents.get();session.reconnect();waitFor("Unavailable page falls back to a document reload",()->!session.navigating&&session.networkReady&&documents.get()>beforeDocuments,70,()->handler.postDelayed(()->js("({instance:pageInstance,draft:document.querySelector('textarea').value,scroll:document.scrollingElement.scrollTop,sends:sendCount})",r->{check("Fallback replaces the failed document",!instance.equals(r.optString("instance")));check("Fallback restores draft without trimming whitespace",originalDraft.equals(r.optString("draft")));check("Fallback restores scroll position",Math.abs(r.optDouble("scroll")-500)<3);check("Fallback never clicks send",r.optInt("sends")==0);conflict();}),400));}
  void conflict(){nextDraft="新网页已有的草稿";beforeDocuments=documents.get();session.reconnect();waitFor("Conflict reload completes",()->!session.navigating&&session.networkReady&&documents.get()>beforeDocuments,70,()->handler.postDelayed(()->js("({draft:document.querySelector('textarea').value})",r->{check("Existing new-page draft is never overwritten",r.optString("draft").equals("新网页已有的草稿"));waitFor("Conflicting old draft is archived locally",()->{JSONArray a=DraftArchive.get(this).list(ORIGIN+"c/one");for(int i=0;i<a.length();i++)if(originalDraft.equals(a.optJSONObject(i).optString("body")))return true;return false;},30,()->spa());}),400));}
  void spa(){failHead=false;js("({instance:pageInstance})",r->{instance=r.optString("instance");beforeDocuments=documents.get();switchConversation(ORIGIN+"c/two");waitFor("Website navigation reaches target conversation",()->!session.navigating&&session.conversation.endsWith("/c/two")&&session.entries.length()==2&&session.entries.optJSONObject(0).optString("text").contains("two"),50,()->{
    js("({instance:pageInstance,sends:sendCount})",p->{check("SPA navigation preserves document and loaded runtime",instance.equals(p.optString("instance"))&&documents.get()==beforeDocuments);check("SPA route is diagnosed separately from full load",session.trace.mode.equals("网页内切换"));check("Conversation navigation never submits",p.optInt("sends")==0);returnPage();});
  });});}
  void returnPage(){switchConversation(ORIGIN+"c/one");waitFor("Previously visited conversation returns",()->!session.navigating&&session.conversation.endsWith("/c/one"),50,()->handler.postDelayed(()->js("({draft:document.querySelector('textarea').value,scroll:document.scrollingElement.scrollTop})",r->{check("Returning conversation restores its own draft",r.optString("draft").equals("新网页已有的草稿"));check("Returning conversation restores its own scroll",Math.abs(r.optDouble("scroll")-500)<3);delayed();}),350));}
  void delayed(){switchConversation(ORIGIN+"c/delayed");handler.postDelayed(()->{check("SPA never publishes old content under a new URL",session.navigating&&session.entries.length()==0);waitFor("Delayed SPA content eventually becomes ready",()->!session.navigating&&session.entries.length()==2&&session.entries.optJSONObject(0).optString("text").contains("delayed"),50,()->noop());},200);}
  void noop(){beforeDocuments=documents.get();switchConversation(ORIGIN+"c/noop");waitFor("Stalled website navigation falls back to loading target",()->!session.navigating&&session.conversation.endsWith("/c/noop")&&session.entries.length()==2&&session.entries.optJSONObject(0).optString("text").contains("noop"),70,()->{check("Stalled SPA causes one fallback document load",documents.get()==beforeDocuments+1);rapid();});}
  void rapid(){switchConversation(ORIGIN+"c/delayed");handler.postDelayed(()->switchConversation(ORIGIN+"c/two"),40);waitFor("Latest rapid navigation wins",()->!session.navigating&&session.conversation.endsWith("/c/two")&&session.entries.length()==2&&session.entries.optJSONObject(0).optString("text").contains("two"),70,()->scope());}
  void scope(){session.pageMemory.capture(()->js("document.querySelector('textarea').value='';({ok:true})",r->{String old=session.appliedIdentity;session.appliedIdentity="changed-network-profile";session.pageMemory.restorePending=true;session.pageMemory.restore(remote.getUrl(),session.navigationEpoch);handler.postDelayed(()->js("({draft:document.querySelector('textarea').value})",p->{check("Page memory does not restore across network profiles",p.optString("draft").isEmpty());session.appliedIdentity=old;mobileNavigation();}),250);}));}
  void mobileNavigation(){js("(()=>{const nav=document.querySelector('nav');nav.style.display='none';for(const kind of ['Open','Close']){const b=document.createElement('button');b.textContent=kind+' sidebar';b.setAttribute('aria-label',kind+' sidebar');b.onclick=()=>nav.style.display=kind==='Open'?'':'none';document.body.prepend(b);}return {instance:pageInstance};})()",r->{instance=r.optString("instance");beforeDocuments=documents.get();switchConversation(ORIGIN+"c/one");waitFor("Mobile sidebar navigation reaches target",()->!session.navigating&&session.conversation.endsWith("/c/one")&&session.entries.length()==2&&session.entries.optJSONObject(0).optString("text").contains("one"),70,()->js("({instance:pageInstance,closed:document.querySelector('nav').style.display==='none',sends:sendCount})",p->{check("Mobile sidebar navigation avoids document reload",p.optString("instance").equals(instance)&&documents.get()==beforeDocuments);check("Sidebar opened for navigation is closed afterward",p.optBoolean("closed"));check("Mobile navigation never clicks send",p.optInt("sends")==0);lifecycle();}));});}
  void lifecycle(){session.handler.removeCallbacks(session.tick);session.foreground(false);check("Idle background pauses browser",session.browserPaused);check("Idle background removes page polling",!session.handler.hasCallbacks(session.tick));session.transferActive=true;session.updateBrowserActivity();check("An active download resumes background browser",!session.browserPaused);session.transferActive=false;session.updateBrowserActivity();check("Completed transfer returns browser to idle",session.browserPaused);
    session.attachments.put(J.obj("name","fixture.pdf","state","uploading"));session.updateBrowserActivity();check("An active upload keeps background browser running",!session.browserPaused&&session.uploading());session.attachments=new JSONArray();session.updateBrowserActivity();check("No remaining upload permits browser pause",session.browserPaused);
    session.foreground(true);check("Returning to foreground resumes page monitoring",!session.browserPaused&&session.handler.hasCallbacks(session.tick));String diagnostic=session.trace.copyText();check("Diagnostic includes phase timing and runtime version",diagnostic.contains("内容可操作")&&diagnostic.contains("WebView"));check("Diagnostic excludes website URL and draft text",!diagnostic.contains("chatgpt.com")&&!diagnostic.contains(originalDraft)&&!diagnostic.contains("新网页已有"));timerIdle();
  }
  void timerIdle(){js("window.timerSamples=0;window.timerHandle=setInterval(()=>window.timerSamples++,40);({ok:true})",r->handler.postDelayed(()->js("({samples:timerSamples})",before->{int count=before.optInt("samples");session.foreground(false);handler.postDelayed(()->js("({samples:timerSamples})",paused->{check("Idle background suspends actual JavaScript timers",paused.optInt("samples")<=count+1);int stopped=paused.optInt("samples");session.foreground(true);handler.postDelayed(()->js("(()=>{clearInterval(timerHandle);return {samples:timerSamples};})()",resumed->{check("Foreground resumes actual JavaScript timers",resumed.optInt("samples")>=stopped+3);pendingGuard();}),240);}),240);}),200));}
  void pendingGuard(){session.handler.removeCallbacks(session.tick);session.pending=J.obj("id","guarded-request","expectedUrl",ORIGIN+"c/two","confirmedUrl",ORIGIN+"c/two","confirmed",true,"userKey","id:two-user");beforeDocuments=documents.get();session.reconnect();waitFor("An unfinished request uses verified reload path",()->!session.connecting&&documents.get()>beforeDocuments,70,()->handler.postDelayed(()->{
    check("Recovery retains request identity without resending",session.pending!=null&&session.pending.optString("id").equals("guarded-request"));session.pending=null;session.handler.removeCallbacks(session.tick);session.inFlight=false;session.foreground(true);notifications();
  },500));}
  void notifications(){ChatService.channels(this);Notification old=ChatService.notification(this,ChatService.DONE,"Fixture","one",ORIGIN+"c/one",false,"done:old-task");Notification newer=ChatService.notification(this,ChatService.DONE,"Fixture","two",ORIGIN+"c/two",false,"done:new-task");Notification wait=ChatService.notification(this,ChatService.WAIT,"Fixture","waiting",null,true);
    check("Different completed tasks have distinct notification intents",!old.contentIntent.equals(newer.contentIntent));check("Waiting updates cannot overwrite completion intent",!old.contentIntent.equals(wait.contentIntent));
    try{old.contentIntent.send();}catch(Exception e){check("Old completion intent can open",false);write(e.toString());return;}
    waitFor("Old completion intent opens its original conversation",()->!session.navigating&&session.conversation.endsWith("/c/one")&&session.entries.length()==2&&session.entries.optJSONObject(0).optString("text").contains("one"),70,()->{
      try{newer.contentIntent.send();}catch(Exception e){write(e.toString());return;}
      waitFor("New completion intent opens its own conversation",()->!session.navigating&&session.conversation.endsWith("/c/two")&&session.entries.length()==2&&session.entries.optJSONObject(0).optString("text").contains("two"),70,()->js("({sends:sendCount})",r->{check("All restoration and notification paths never send",r.optInt("sends")==0);write("");}));
    });
  }
  void write(String error){try{J.write(new File(getFilesDir(),"continuity-results.json"),J.obj("checks",checks,"error",error,"retainedRecoveryMs",recoveryDuration,"documentLoads",documents.get(),"headRequests",heads.get(),"status",session.status,"navigating",session.navigating,"connecting",session.connecting,"mode",session.trace.mode,"keepCandidate",session.keepPageCandidate,"appliedIdentity",session.appliedIdentity,"conversation",session.conversation,"snapshots",new JSONArray(session.pageMemory.pages.values()),"lastRestore",session.pageMemory.lastRestore,"memoryScope",session.pageMemory.scope(),"memoryKeys",new JSONArray(session.pageMemory.pages.keySet())).toString(2));}catch(Exception ignored){}}
}
