package local.pocketchat;

import android.app.*;import android.content.*;import android.database.Cursor;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import org.json.*;import java.io.*;import java.util.*;

/** Production save completion against real MediaStore, without external requests. */
public class DefaultDownloadTestActivity extends ContinuityFixtureActivity {
  final JSONArray checks=new JSONArray();final byte[] payload=new byte[131072];int pickerRequests,attempts;Uri first;String firstId;DefaultDownloads.Target incomplete,local;JSONObject old;
  void check(String name,boolean pass){checks.put(J.obj("name",name,"pass",pass));}
  @Override public void onCreate(Bundle b){getSharedPreferences("chat",0).edit().clear().putBoolean("networkConfigured",true).putString("networkMode","external").putBoolean("requireExternalVpn",false).putBoolean("webNotificationAsked",true).putString("conversation",ORIGIN+"c/download-fixture").commit();getSharedPreferences("download-tasks",0).edit().clear().commit();super.onCreate(b);for(int i=0;i<payload.length;i++)payload[i]=(byte)(i*31);handler.postDelayed(()->begin(),500);}
  @Override public void startActivityForResult(Intent i,int request){if(request==FileDownloads.SAVE||request==SavedFileActions.EXPORT){pickerRequests++;return;}super.startActivityForResult(i,request);}
  void begin(){if(session.navigating&&attempts++<60){handler.postDelayed(()->begin(),100);return;}check("Records tab is absent while history drawer remains",hub.tabs.length==4&&hub.tabs[1].getText().equals("下载")&&hub.tabs[2].getText().equals("窗口"));try{downloads.newTask("fixture","fixture-key",ORIGIN+"c/download-fixture");downloads.name="default-fixture.bin";downloads.mime="application/octet-stream";downloads.temp=File.createTempFile("download-",".part",getCacheDir());try(OutputStream out=new FileOutputStream(downloads.temp)){out.write(payload);}downloads.receivedBytes=payload.length;downloads.totalBytes=payload.length;downloads.active=true;downloads.cancelled=false;session.transferActive=true;downloads.choose(++downloads.ticket);handler.postDelayed(()->saved(),100);}catch(Exception e){check("Default save fixture starts",false);write();}}
  void saved(){if(!"saved".equals(downloads.task.optString("state"))&&attempts++<120){handler.postDelayed(()->saved(),100);return;}first=Uri.parse(downloads.task.optString("uri"));firstId=downloads.task.optString("id");check("Finished download saves without opening the document picker",pickerRequests==0&&downloads.task.optString("state").equals("saved"));check("Default file bytes are complete and readable",same(first));check("Default location is public and profile-specific",downloads.task.optString("location").startsWith("Download/元婴期院士/窗口_1/"));try(Cursor row=getContentResolver().query(first,new String[]{MediaStore.MediaColumns.IS_PENDING},null,null,null)){check("Only completed files are published in MediaStore",row!=null&&row.moveToFirst()&&row.getInt(0)==0);}catch(Exception e){check("Only completed files are published in MediaStore",false);}check("Saved state and URI survive task recreation",new DownloadTasks(this).rows.optJSONObject(0).optString("uri").equals(first.toString()));boolean indexed=false;JSONArray files=DownloadLibrary.get(this).list();for(int i=0;i<files.length();i++)if(files.optJSONObject(i).optString("uri").equals(first.toString()))indexed=true;check("Saved file appears in shared native download index",indexed);check("Completed save releases transfer guard and temporary file",!downloads.active&&!session.transferActive&&downloads.temp==null);Intent share=SavedFileActions.shareIntent(downloads.task);check("Sharing grants only read access to one URI",(share.getFlags()&Intent.FLAG_GRANT_READ_URI_PERMISSION)!=0&&(share.getFlags()&Intent.FLAG_GRANT_WRITE_URI_PERMISSION)==0&&share.getClipData()!=null&&share.getClipData().getItemCount()==1);downloads.savedActions.export(downloads.task);check("Saved file keeps optional manual Save As",pickerRequests==1);downloads.savedActions.result(Activity.RESULT_CANCELED,null);if(downloads.noticeDialog!=null)downloads.noticeDialog.dismiss();helperTests();}
  boolean same(Uri uri){try(InputStream in=getContentResolver().openInputStream(uri)){return Arrays.equals(payload,J.read(in,1024*1024));}catch(Exception e){return false;}}
  void helperTests(){try{
    DefaultDownloads.Target duplicate=DefaultDownloads.create(this,"default-fixture.bin","application/octet-stream");try(OutputStream out=duplicate.output()){out.write(new byte[]{4,5,6});}duplicate.publish();check("Duplicate names get a distinct destination",!duplicate.uri.equals(first));check("Duplicate downloads receive distinct visible filenames",!duplicate.name.equals(downloads.name));check("Saving a duplicate never overwrites the prior file",same(first));duplicate.abort();
    incomplete=DefaultDownloads.create(this,"interrupted-fixture.bin","application/octet-stream");try(OutputStream out=incomplete.output()){out.write(new byte[]{1,2});}JSONObject interrupted=J.obj("state","saving","pendingDestination",incomplete.uri.toString(),"pendingLocation",incomplete.location);DefaultDownloads.recover(this,interrupted);boolean missing=false;try(InputStream in=getContentResolver().openInputStream(incomplete.uri)){missing=in==null;}catch(Exception e){missing=true;}check("Interrupted pending destinations are cleaned on recovery",missing&&!interrupted.has("pendingDestination")&&!interrupted.optString("state").equals("saved"));
    DefaultDownloads.Target published=DefaultDownloads.create(this,"committed-fixture.bin","application/octet-stream");try(OutputStream out=published.output()){out.write(payload);}published.publish();JSONObject committed=J.obj("state","saving","pendingDestination",published.uri.toString(),"pendingLocation",published.location);DefaultDownloads.recover(this,committed);check("Recovery recognizes a fully published file",committed.optString("state").equals("saved")&&committed.optString("uri").equals(published.uri.toString()));published.abort();
    local=DefaultDownloads.local(this,"legacy-fixture.bin");try(OutputStream out=local.output()){out.write(payload);}local.publish();check("Older Android fallback file is readable through a content URI",same(local.uri));boolean denied=false;try{getContentResolver().openOutputStream(local.uri,"w");}catch(Exception e){denied=true;}check("Fallback sharing provider rejects all writes",denied);denied=false;try{SavedDownloadProvider.resolve(this,new Uri.Builder().scheme("content").authority(getPackageName()+".saved-downloads").appendPath("0").appendPath(UUID.randomUUID().toString()).appendPath("../../chat.xml").build());}catch(Exception e){denied=true;}check("Fallback provider rejects path traversal",denied);check("Each window uses its own default download folder",!DefaultDownloads.directory(this).equals(DefaultDownloads.directory(Profiles.context(this,7))));
    old=J.obj("name","历史文件.pdf","mime","application/pdf","uri","content://local.pocketchat.download-fixture/sample2.pdf","state","saved","conversation","private-chat","source","signed-source-secret");DownloadLibrary.get(this).add(this,old);boolean legacy=false,sensitive=false;JSONArray library=DownloadLibrary.get(this).list();for(int i=0;i<library.length();i++){JSONObject r=library.optJSONObject(i);if(r.optString("name").equals("历史文件.pdf")){legacy=true;sensitive=r.has("conversation")||r.has("source");}}check("Legacy saved files remain discoverable",legacy);check("Shared file index excludes chat and signed source URLs",!sensitive);
    hub.show(1);check("Download module has default path and visible task",hub.panel.getVisibility()==android.view.View.VISIBLE&&hub.page==1);if(local!=null)local.abort();
  }catch(Exception e){check("Default destination protocol fixtures finish",false);}exportTest();}
  void exportTest(){downloads.savedActions.export(downloads.task);Uri destination=Uri.parse("content://local.pocketchat.download-fixture/sample99.docx");downloads.savedActions.result(Activity.RESULT_OK,new Intent().setData(destination));handler.postDelayed(()->{check("Save As copies the existing file without another download",same(destination));check("Save As preserves the default saved file",same(first));try{FileDownloads closing=new FileDownloads(this);closing.newTask("closing","",ORIGIN);closing.name="closing-fixture.bin";closing.temp=File.createTempFile("download-",".part",getCacheDir());try(OutputStream out=new FileOutputStream(closing.temp)){out.write(payload);}closing.active=true;closing.choose(++closing.ticket);closing.destroy();handler.postDelayed(()->{boolean remains=false;try(Cursor row=getContentResolver().query(MediaStore.Downloads.EXTERNAL_CONTENT_URI,new String[]{MediaStore.MediaColumns.DISPLAY_NAME},MediaStore.MediaColumns.DISPLAY_NAME+"=?",new String[]{"closing-fixture.bin"},null)){remains=row!=null&&row.moveToFirst();}catch(Exception e){remains=true;}check("Closing during automatic save cleans the unfinished destination",!remains);check("Closing a new save keeps already saved files",same(first));write();},1000);}catch(Exception e){check("Closing save fixture completes",false);write();}},600);}
  void write(){try{J.write(new File(getFilesDir(),"default-download-results.json"),J.obj("checks",checks,"scope","Production completion; real MediaStore and read-only provider; no external download").toString(2));}catch(Exception ignored){}}
}
