package local.pocketchat;
import android.os.*;import android.webkit.*;import org.json.*;import java.io.*;import java.util.*;
public class DeliveryTestActivity extends MainActivity {
 JSONArray checks=new JSONArray();Set<String> seen=new HashSet<>();String request="";final ChatSession.Observer watcher=()->observe();
 void check(String n,boolean b){checks.put(J.obj("name",n,"pass",b));}
 void observe(){if(session==null)return;if(!session.activeDeliveryId.isEmpty())request=session.activeDeliveryId;JSONObject r=session.deliveries.get(request);if(r!=null)seen.add(r.optString("state"));}
 @Override public void onCreate(Bundle b){deleteDatabase("deliveries.db");getSharedPreferences("chat",0).edit().clear().commit();super.onCreate(b);setRequestedOrientation(1);session.add(watcher);handler.postDelayed(()->{remote.evaluateJavascript("window.replyDelay=3600",r->{input.setText("delivery-state-fixture");sendPrompt();handler.postDelayed(()->complete(),8500);});},2500);}
 @Override void startNetwork(){prefs.edit().putBoolean("networkConfigured",true).putString("networkMode","external").putBoolean("requireExternalVpn",false).commit();session.networkReady=true;session.prefs.edit().putBoolean("requireExternalVpn",false).commit();session.guard.setBlocked(false);remote.loadUrl(ORIGIN);}
 @Override WebViewClient remoteClient(){return new WebViewClient(){@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){try{return new WebResourceResponse("text/html","UTF-8",getAssets().open("fixture.html"));}catch(Exception e){return blocked();}}};}
 void complete(){observe();for(String stage:new String[]{"queued","sending","confirmed","awaiting","completed"})check("Observed message stage: "+stage,seen.contains(stage));JSONObject record=session.deliveries.get(request);check("Completed message binds to its webpage identity",record!=null&&!record.optString("user_key").isEmpty()&&record.optInt("attempted")==1);JSONArray decorated=session.deliveries.decorate(conversation,entries,session.activeDeliveryId);int locals=0;boolean complete=false;for(int i=0;i<decorated.length();i++){JSONObject e=decorated.optJSONObject(i);if(e.optBoolean("local"))locals++;if(e.optJSONObject("delivery")!=null&&e.optJSONObject("delivery").optString("state").equals("completed"))complete=true;}check("Confirmed bubble is not duplicated by a local placeholder",locals==0&&complete);remote.evaluateJavascript("document.querySelector('textarea').value='independent-web-draft'",r->{input.setText("blocked-local-input");sendPrompt();handler.postDelayed(()->failed(),1300);});}
 void failed(){JSONObject record=session.deliveries.get(session.activeDeliveryId);check("Pre-send conflict is recorded as failed but unattempted",record!=null&&record.optString("state").equals("failed")&&record.optInt("attempted")==0);if(draftUi.dialog!=null)draftUi.dialog.getButton(-2).performClick();String unknown=session.deliveries.begin(ORIGIN+"c/recovery","uncertain fixture",null,"send",null);session.deliveries.update(unknown,"sending","waiting",true,"","");session.deliveries.recover(null);check("An interrupted attempted send recovers as uncertain",session.deliveries.get(unknown).optString("state").equals("uncertain")&&session.deliveries.get(unknown).optInt("attempted")==1);remote.evaluateJavascript("window.sendCount",r->{check("Status recovery never submits again","1".equals(r));write();});}
 void write(){session.remove(watcher);try{J.write(new File(getFilesDir(),"delivery-results.json"),J.obj("checks",checks).toString(2));}catch(Exception ignored){}}
}
