package local.pocketchat;
import android.os.*;import android.view.*;import org.json.*;import java.io.*;
public class DesignUiTestActivity extends ContinuityFixtureActivity {
  final JSONArray checks=new JSONArray();int attempts,launches;String pageInstance;void check(String name,boolean pass){checks.put(J.obj("name",name,"pass",pass));}
  @Override public void startActivity(android.content.Intent intent){launches++;super.startActivity(intent);}
  @Override public void onCreate(Bundle state){getSharedPreferences("chat",0).edit().clear().putBoolean("networkConfigured",true).putString("networkMode","external").putBoolean("requireExternalVpn",false).putBoolean("pageMode",true).putBoolean("webNotificationAsked",true).putString("conversation",ORIGIN+"c/design-fixture").commit();super.onCreate(state);handler.postDelayed(()->test(),100);}
  void test(){if((session.navigating||session.entries.length()!=2)&&attempts++<70){handler.postDelayed(()->test(),100);return;}remote.evaluateJavascript("({instance:pageInstance})",raw->{pageInstance=J.parse(raw).optString("instance");check("Designed app chrome keeps real website visible",remote.getVisibility()==View.VISIBLE&&pageMode);check("Five destinations keep environment scope",hub.tabs.length==5&&hub.tabs[0].getText().equals("会话")&&hub.tabs[1].getText().equals("环境")&&hub.tabs[2].getText().equals("下载")&&hub.tabs[3].getText().equals("网络")&&hub.tabs[4].getText().equals("设置"));check("URL strip is from current site host",designChrome.host.getText().toString().equals("chatgpt.com"));int[] browserPosition=new int[2],barPosition=new int[2];remote.getLocationOnScreen(browserPosition);toolbar.getLocationOnScreen(barPosition);check("Toolbar ends directly at browser viewport",Math.abs(browserPosition[1]-barPosition[1]-toolbar.getHeight())<=dp(1));modules();});}
  void modules(){editorChecks();hub.show(4);for(int i=0;i<5;i++){hub.networkTab=i;hub.network();check("Network section renders actual view: "+i,hub.panel.getChildCount()==1&&hub.page==4);}check("Network page selects network nav item",hub.tabs[3].isSelected());hub.show(3);check("Settings is app-wide",text(hub.panel).contains("默认环境与启动入口")&&!text(hub.panel).contains("当前窗口设置"));hub.settingsTab=1;hub.settings();check("Global settings render independently",hub.page==3&&hub.tabs[4].isSelected());check("Global settings excludes profile switches",!text(hub.panel).contains("当前窗口仅在 Wi-Fi")&&!text(hub.panel).contains("偏好设置"));hub.show(4);hub.networkTab=1;hub.network();check("External network does not expose subscription actions",text(hub.panel).contains("修改配置")&&hub.networkTab==0&&!text(hub.panel).contains("更新已保存的订阅"));hub.networkTab=0;hub.show(1);check("Download center selects downloads nav item",hub.tabs[2].isSelected());String index=DownloadLibrary.get(this).tasks().toString();check("Shared progress index excludes signed source URLs",!index.contains("https://fixture.invalid")&&!index.contains("Cookie="));String before=AppPrefs.values(this).toString();int level=session.privacy.level();android.app.AlertDialog development=FutureFeatures.open(this,FutureFeatures.Feature.CUSTOM_FINGERPRINT,Profiles.slot(this));check("Opening development slot cannot change current privacy policy",level==session.privacy.level()&&before.equals(AppPrefs.values(this).toString()));if(development!=null)development.dismiss();int oldDefault=AppSettings.defaultSlot(this);ProfileCatalog.get(this).created(1);AppSettings.defaultSlot(this,1);int beforeLaunch=launches;hub.tabs[0].performClick();check("Conversation navigation retains current environment",hub.page==0&&launches==beforeLaunch);AppSettings.defaultSlot(this,oldDefault);handler.postDelayed(()->remote.evaluateJavascript("({instance:pageInstance,sends:sendCount})",raw->{JSONObject data=J.parse(raw);check("Designed panels retain same website document",pageInstance.equals(data.optString("instance")));check("Designed controls never submit a chat message",data.optInt("sends")==0&&session.pending==null);write();}),250);}
  void editorChecks(){
    JSONObject original=EnvironmentEditorUi.current(this);ProfileCatalog catalog=ProfileCatalog.get(this);android.widget.EditText name=new android.widget.EditText(this);
    JSONObject invalid=J.parse(original.toString());try{invalid.put("name","");}catch(Exception ignored){}
    check("Invalid editor values leave live configuration unchanged",!EnvironmentEditorUi.apply(this,invalid,name)&&Profiles.display(this,Profiles.slot(this)).equals(original.optString("name")));
    JSONObject changed=J.parse(original.toString());try{changed.put("name","环境编辑回归");changed.put("group","研究");changed.put("notes","独立资料环境");}catch(Exception ignored){}
    catalog.draft(Profiles.slot(this),changed);check("Editor drafts do not apply group changes",!catalog.item(Profiles.slot(this)).optString("group").equals("研究"));
    int documentsBefore=documents.get();boolean saved=EnvironmentEditorUi.apply(this,changed,name);
    check("Editor save persists name, group and notes",saved&&catalog.item(Profiles.slot(this)).optString("group").equals("研究")&&Profiles.display(this,Profiles.slot(this)).equals("环境编辑回归"));
    check("Editor save clears applied draft",catalog.item(Profiles.slot(this)).optString("draft").isEmpty());
    check("Metadata-only save keeps browser document and privacy",documents.get()==documentsBefore&&session.privacy.level()==original.optInt("privacyLevel"));
    check("Editor restores original environment",EnvironmentEditorUi.apply(this,original,name));
  }
  static String text(View view){StringBuilder out=new StringBuilder();if(view instanceof android.widget.TextView)out.append(((android.widget.TextView)view).getText());if(view instanceof android.view.ViewGroup){android.view.ViewGroup group=(android.view.ViewGroup)view;for(int i=0;i<group.getChildCount();i++)out.append(text(group.getChildAt(i)));}return out.toString();}
  void write(){try{J.write(new File(getFilesDir(),"design-ui-results.json"),J.obj("checks",checks).toString(2));}catch(Exception ignored){}handler.postDelayed(()->preview(),200);}
  void preview(){String screen=getIntent().getStringExtra("qaScreen");if(screen==null)return;if(screen.equals("chat")){hub.show(0);showPage(true);}if(screen.equals("settings")){hub.settingsTab=getIntent().getIntExtra("section",0);hub.show(3);}if(screen.equals("network")){hub.networkTab=getIntent().getIntExtra("section",0);hub.show(4);}if(screen.equals("editor")){ProfileCatalog.get(this).draft(Profiles.slot(this),null);EnvironmentEditorUi.editTab(this,getIntent().getIntExtra("section",0));}if(screen.equals("privacy"))DesignPrivacyUi.show(this);if(screen.equals("downloads"))hub.show(1);}
}
