package local.pocketchat;
import android.os.*;import android.view.*;import org.json.*;import java.io.*;
public class DesignUiTestActivity extends ContinuityFixtureActivity {
  final JSONArray checks=new JSONArray();int attempts;String pageInstance;void check(String name,boolean pass){checks.put(J.obj("name",name,"pass",pass));}
  @Override public void onCreate(Bundle state){getSharedPreferences("chat",0).edit().clear().putBoolean("networkConfigured",true).putString("networkMode","external").putBoolean("requireExternalVpn",false).putBoolean("pageMode",true).putBoolean("webNotificationAsked",true).putString("conversation",ORIGIN+"c/design-fixture").commit();super.onCreate(state);handler.postDelayed(()->test(),100);}
  void test(){if((session.navigating||session.entries.length()!=2)&&attempts++<70){handler.postDelayed(()->test(),100);return;}remote.evaluateJavascript("({instance:pageInstance})",raw->{pageInstance=J.parse(raw).optString("instance");check("Designed app chrome keeps real website visible",remote.getVisibility()==View.VISIBLE&&pageMode);check("Five destinations match supplied design",hub.tabs.length==5&&hub.tabs[0].getText().equals("默认")&&hub.tabs[1].getText().equals("窗口")&&hub.tabs[2].getText().equals("下载")&&hub.tabs[3].getText().equals("网络")&&hub.tabs[4].getText().equals("设置"));check("URL strip is from current site host",designChrome.host.getText().toString().equals("chatgpt.com"));int[] browserPosition=new int[2],barPosition=new int[2];remote.getLocationOnScreen(browserPosition);toolbar.getLocationOnScreen(barPosition);check("Toolbar ends directly at browser viewport",Math.abs(browserPosition[1]-barPosition[1]-toolbar.getHeight())<=dp(1));modules();});}
  void modules(){hub.show(4);for(int i=0;i<5;i++){hub.networkTab=i;hub.network();check("Network section renders actual view: "+i,hub.panel.getChildCount()==1&&hub.page==4);}check("Network page selects network nav item",hub.tabs[3].isSelected());hub.show(3);check("Settings keeps current-window scope",hub.settingsTab==0);hub.settingsTab=1;hub.settings();check("Global settings render independently",hub.page==3&&hub.tabs[4].isSelected());hub.show(1);check("Download center selects downloads nav item",hub.tabs[2].isSelected());String index=DownloadLibrary.get(this).tasks().toString();check("Shared progress index excludes signed source URLs",!index.contains("https://fixture.invalid")&&!index.contains("Cookie="));String before=AppPrefs.values(this).toString();int level=session.privacy.level();android.app.AlertDialog development=FutureFeatures.open(this,FutureFeatures.Feature.CUSTOM_FINGERPRINT,Profiles.slot(this));check("Opening development slot cannot change current privacy policy",level==session.privacy.level()&&before.equals(AppPrefs.values(this).toString()));if(development!=null)development.dismiss();hub.show(0);handler.postDelayed(()->remote.evaluateJavascript("({instance:pageInstance,sends:sendCount})",raw->{JSONObject data=J.parse(raw);check("Designed panels retain same website document",pageInstance.equals(data.optString("instance")));check("Designed controls never submit a chat message",data.optInt("sends")==0&&session.pending==null);write();}),250);}
  void write(){try{J.write(new File(getFilesDir(),"design-ui-results.json"),J.obj("checks",checks).toString(2));}catch(Exception ignored){}handler.postDelayed(()->preview(),200);}
  void preview(){String screen=getIntent().getStringExtra("qaScreen");if(screen==null)return;if(screen.equals("chat")){hub.show(0);showPage(true);}if(screen.equals("settings")){hub.settingsTab=getIntent().getIntExtra("section",0);hub.show(3);}if(screen.equals("network")){hub.networkTab=getIntent().getIntExtra("section",0);hub.show(4);}if(screen.equals("editor")){ProfileCatalog.get(this).draft(Profiles.slot(this),null);EnvironmentEditorUi.editTab(this,getIntent().getIntExtra("section",0));}if(screen.equals("privacy"))DesignPrivacyUi.show(this);if(screen.equals("downloads"))hub.show(1);}
}
