package local.pocketchat;
import android.os.*;import android.webkit.*;import org.json.*;import java.io.*;import java.net.*;import java.util.*;

/** Deterministic HTTP protocol tests: production streaming code, no external requests. */
public class DownloadFlowTestActivity extends MainActivity {
 JSONArray checks=new JSONArray();byte[] payload=new byte[131072];MockDownloads mock;int completed=0;
 void check(String n,boolean b){checks.put(J.obj("name",n,"pass",b));}
 @Override void startNetwork(){prefs.edit().putString("networkMode","external").putBoolean("requireExternalVpn",false).putBoolean("networkConfigured",true).commit();session.networkReady=true;session.prefs.edit().putBoolean("requireExternalVpn",false).commit();session.guard.setBlocked(false);remote.loadUrl(ORIGIN);}
 @Override WebViewClient remoteClient(){return new WebViewClient(){@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){try{return new WebResourceResponse("text/html","UTF-8",getAssets().open("fixture.html"));}catch(Exception e){return blocked();}}};}
 @Override public void onCreate(Bundle b){getSharedPreferences("chat",0).edit().clear().commit();getSharedPreferences("download-tasks",0).edit().clear().commit();super.onCreate(b);for(int i=0;i<payload.length;i++)payload[i]=(byte)(i*37);handler.postDelayed(()->begin(),2200);}
 void begin(){downloads.destroy();mock=new MockDownloads(this);downloads=mock;mock.accept("https://fixture.invalid/file.bin","fixture","","application/octet-stream",payload.length);handler.postDelayed(()->firstFailure(),900);}
 void firstFailure(){check("Interrupted HTTP transfer retains partial bytes",mock.temp!=null&&mock.temp.length()==32768);check("Failure reason and byte progress persist",mock.task.optString("state").equals("failed")&&mock.task.optLong("received")==32768&&!mock.task.optString("reason").isEmpty());check("Unknown signed URLs are not persisted",!mock.tasks.prefs.getString("rows","").contains("fixture.invalid"));if(mock.noticeDialog!=null)mock.noticeDialog.dismiss();mock.retry();handler.postDelayed(()->afterResume(),900);}
 void afterResume(){check("Resume sends exact Range and If-Range headers",mock.last!=null&&"bytes=32768-".equals(mock.last.getRequestProperty("Range"))&&"\"fixture-v1\"".equals(mock.last.getRequestProperty("If-Range")));check("Resumed file matches original bytes",completed==1&&same());check("Finished transfer reports full size",mock.receivedBytes==payload.length&&mock.totalBytes==payload.length);mock.cancel();mock.ignoreUntil=0;mock.mode=1;mock.calls=0;mock.accept("https://fixture.invalid/ignore-range.bin","fixture","","application/octet-stream",payload.length);handler.postDelayed(()->{if(mock.noticeDialog!=null)mock.noticeDialog.dismiss();mock.retry();handler.postDelayed(()->afterIgnoredRange(),900);},900);}
 boolean same(){try{return Arrays.equals(payload,java.nio.file.Files.readAllBytes(mock.temp.toPath()));}catch(Exception e){return false;}}
 void afterIgnoredRange(){check("Server ignoring Range restarts without duplicate prefix",completed==2&&same());try{Fake c=new Fake(new URL("https://fixture.invalid/"),206,32768,false);c.range="bytes 1-98304/131072";boolean rejected=false;try{DownloadRange.total(c,32768,"\"fixture-v1\"");}catch(IOException e){rejected=true;}check("Mismatched Content-Range is rejected",rejected);c.range="bytes 32768-131071/131072";c.etag="\"changed\"";rejected=false;try{DownloadRange.total(c,32768,"\"fixture-v1\"");}catch(IOException e){rejected=true;}check("Changed resource validator is rejected",rejected);check("Weak ETags alone cannot enable resume",DownloadRange.validator("W/\"weak\"",null).isEmpty());}catch(Exception e){check("Range protocol fixture",false);}mock.mark("downloading","");DownloadTasks recovered=new DownloadTasks(this);check("Interrupted task becomes paused on recreation",recovered.rows.optJSONObject(0).optString("state").equals("paused"));mock.history();check("Unified download manager opens",mock.manager!=null&&mock.manager.isShowing());if(mock.manager!=null)mock.manager.dismiss();mock.active=true;session.transferActive=true;mock.pause();check("Pause releases switching guard and retains bytes",!mock.active&&!session.transferActive&&mock.temp!=null&&mock.temp.length()==payload.length);File partial=mock.temp;mock.cancel();handler.postDelayed(()->{check("Cancel clears partial cache and records cancellation",!partial.exists()&&mock.task.optString("state").equals("cancelled"));write();},500);}
 class MockDownloads extends FileDownloads {int calls=0,mode=0;Fake last;MockDownloads(MainActivity a){super(a);} @Override HttpURLConnection connect(String u,Proxy p)throws Exception{calls++;last=new Fake(new URL(u),calls==1||mode==1?200:206,calls==1||mode==1?0:32768,calls==1);return last;}@Override void choose(long attempt){if(!valid(attempt))return;completed++;completeFile=true;mark("paused","fixture complete");active=false;a.session.transferActive=false;dismiss();}}
 class Fake extends HttpURLConnection {int code,offset;boolean truncate;String etag="\"fixture-v1\"",range;Fake(URL url,int code,int offset,boolean truncate){super(url);this.code=code;this.offset=offset;this.truncate=truncate;range="bytes "+offset+"-131071/131072";}public void connect(){}public void disconnect(){}public boolean usingProxy(){return false;}public int getResponseCode(){return code;}public long getContentLengthLong(){return payload.length-offset;}public String getContentType(){return "application/octet-stream";}public String getHeaderField(String key){return key.equals("ETag")?etag:key.equals("Content-Range")?range:null;}public InputStream getInputStream(){return new InputStream(){int at=offset;public int read()throws IOException{if(truncate&&at>=32768)throw new IOException("fixture network interruption");return at<payload.length?payload[at++]&255:-1;}public int read(byte[] b,int off,int len)throws IOException{if(truncate&&at>=32768)throw new IOException("fixture network interruption");if(at==payload.length)return -1;int n=Math.min(len,(truncate?32768:payload.length)-at);System.arraycopy(payload,at,b,off,n);at+=n;return n;}};}}
 void write(){try{J.write(new File(getFilesDir(),"download-flow-results.json"),J.obj("checks",checks).toString(2));}catch(Exception ignored){}}
}
