package local.pocketchat;
import android.os.*;import android.webkit.*;import org.json.*;import java.io.*;

public class DraftTestActivity extends MainActivity {
 JSONArray checks=new JSONArray();
 void check(String n,boolean value){checks.put(J.obj("name",n,"pass",value));}
 @Override public void onCreate(Bundle b){getSharedPreferences("chat",0).edit().clear().commit();super.onCreate(b);setRequestedOrientation(1);handler.postDelayed(()->begin(),3000);}
 @Override void startNetwork(){prefs.edit().putBoolean("networkConfigured",true).putString("networkMode","external").putBoolean("requireExternalVpn",false).commit();session.networkReady=true;session.prefs.edit().putBoolean("requireExternalVpn",false).commit();session.guard.setBlocked(false);remote.loadUrl(ORIGIN);}
 @Override WebViewClient remoteClient(){return new WebViewClient(){@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){try{return new WebResourceResponse("text/html","UTF-8",getAssets().open("fixture.html"));}catch(Exception e){return blocked();}}};}
 void begin(){remote.evaluateJavascript("document.querySelector('textarea').value='web-only-draft'",r->{input.setText("native-one");sendPrompt();handler.postDelayed(()->conflict(),1400);});}
 void conflict(){check("Different web draft produces a resolution dialog",session.draftConflict!=null&&draftUi.dialog!=null&&draftUi.dialog.isShowing());remote.evaluateJavascript("JSON.stringify({draft:document.querySelector('textarea').value,count:sendCount})",r->{JSONObject x=decode(r);check("Unapproved web draft remains untouched",x.optString("draft").equals("web-only-draft")&&x.optInt("count")==0);if(draftUi.dialog==null){write();return;}draftUi.dialog.getButton(-1).performClick();handler.postDelayed(()->confirmed(),6500);});}
 void confirmed(){remote.evaluateJavascript("JSON.stringify({count:sendCount,last:[...document.querySelectorAll('[data-message-author-role=user]')].at(-1)?.textContent})",r->{JSONObject x=decode(r);check("Approved current input sends exactly once",x.optInt("count")==1&&x.optString("last").equals("native-one"));check("Other draft archived before replacement",new DraftArchive(this).list(ORIGIN).toString().contains("web-only-draft"));check("Owned fill is remembered",prefs.getString("ownedWebDraft:"+ORIGIN,"").equals("native-one"));remote.evaluateJavascript("document.querySelector('textarea').value='native-one'",unused->{input.setText("native-two");sendPrompt();handler.postDelayed(()->owned(),6500);});});}
 void owned(){remote.evaluateJavascript("JSON.stringify({count:sendCount,last:[...document.querySelectorAll('[data-message-author-role=user]')].at(-1)?.textContent})",r->{JSONObject x=decode(r);check("App-owned leftover updates without another conflict",session.draftConflict==null&&x.optInt("count")==2&&x.optString("last").equals("native-two"));check("Earlier input remains recoverable",new DraftArchive(this).list(ORIGIN).toString().contains("native-one"));remote.evaluateJavascript("document.querySelector('textarea').value='changed-after-approval'",unused->{runDriver("fill",J.obj("text","should-not-replace","replaceDraft",true,"expectedDraft","older-approved-value","expectedUrl",ORIGIN,"expectedModel","Thinking","expectedEffort","Extra High"),result->{check("Concurrent webpage changes invalidate replacement approval",result.optBoolean("conflict")&&!result.optBoolean("ok"));remote.evaluateJavascript("document.querySelector('textarea').value",value->{check("Newer webpage text is preserved",value.contains("changed-after-approval"));paragraphs();});});});});}
 void paragraphs(){remote.evaluateJavascript("(()=>{const old=document.querySelector('textarea'),e=document.createElement('div');e.id='prompt-textarea';e.className='ProseMirror';e.contentEditable='true';e.innerHTML='<p>第一行</p><p><br class=ProseMirror-trailingBreak></p><p>  第二行</p>';old.replaceWith(e);})()",r->runDriver("inspect",new JSONObject(),state->{check("ProseMirror draft parsed without legacy data attribute",state.optString("draft").equals("第一行\n\n  第二行"));write();}));}
 JSONObject decode(String raw){try{return new JSONObject((String)new JSONTokener(raw).nextValue());}catch(Exception e){return new JSONObject();}}
 void write(){try{J.write(new File(getFilesDir(),"draft-results.json"),J.obj("checks",checks).toString(2));}catch(Exception ignored){}}
}
