package local.pocketchat;

import android.os.*;
import android.webkit.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.CountDownLatch;

/** Real local frames and Worker; public endpoints are intercepted, never contacted. */
public class EnvironmentAuditTestActivity extends ContinuityFixtureActivity {
  final JSONArray checks=new JSONArray();int attempts;FixtureAudit audit;String mainUrl,mainInstance,mainDraft="自检时保留的草稿";
  void check(String name,boolean pass){checks.put(J.obj("name",name,"pass",pass));}
  @Override public void onCreate(Bundle b){if(!getPackageName().endsWith(".test"))throw new IllegalStateException();new SecretStore(this).file("environment-audit").delete();getSharedPreferences("chat",0).edit().clear().putBoolean("networkConfigured",true).putString("networkMode","external").putBoolean("requireExternalVpn",false).putBoolean("pageMode",true).putBoolean("webNotificationAsked",true).putString("conversation",ORIGIN+"c/audit-room").commit();super.onCreate(b);handler.postDelayed(()->ready(),100);}
  static JSONObject row(JSONObject report,String key){JSONArray rows=report.optJSONArray("rows");if(rows!=null)for(int i=0;i<rows.length();i++){JSONObject r=rows.optJSONObject(i);if(key.equals(r.optString("key")))return r;}return new JSONObject();}
  static boolean state(JSONObject report,String key,String state){return state.equals(row(report,key).optString("state"));}
  void ready(){if((session.navigating||session.entries.length()!=2)&&attempts++<70){handler.postDelayed(()->ready(),100);return;}check("Main fixture is usable before diagnostics",session.networkReady&&!session.navigating);audit=new FixtureAudit(session);session.audit=audit;mainUrl=remote.getUrl();remote.evaluateJavascript("document.querySelector('textarea').value="+JSONObject.quote(mainDraft)+";({instance:pageInstance})",raw->{mainInstance=J.parse(raw).optString("instance");models();local();});}
  void models(){String ua=BrowserPrivacy.reducedAgent("Mozilla Chrome/110.0.5481.154"),ip="203.0.113.8";JSONObject p=J.obj("ua",ua,"cpu",4,"memory",4,"language","zh-CN","offset",-480,"early",true,"rtc","restricted","hints",J.obj("brands",J.arr(J.obj("brand","Chromium","version","110"))));JSONObject sample=J.obj("parent",p,"frame",J.parse(p.toString()),"worker",J.parse(p.toString()),"network",J.obj("ipv4",J.obj("ip",ip),"ipv6",J.obj("error","timeout"),"headers",J.obj("headers",J.obj("User-Agent",ua))));try{sample.getJSONObject("worker").put("ip",J.obj("ip",ip));}catch(Exception ignored){}
    JSONObject expected=J.obj("ua",ua,"major",110,"level",1,"offset",-480,"exitIp",ip),nativeIp=J.obj("ip",ip),r=AuditReport.build(sample,nativeIp,expected,true,true);
    check("Matching observed IPv4 paths are verified",state(r,"ipv4",AuditReport.VERIFIED));check("IPv6 timeout is never treated as leak-free",state(r,"ipv6",AuditReport.UNCOVERED));check("DNS remains unverified without a real DNS probe",state(r,"dns",AuditReport.UNCOVERED));check("HTTPS checks do not certify UDP or TLS",state(r,"udp",AuditReport.UNCOVERED));check("Returned request header is compared with page UA",state(r,"header",AuditReport.VERIFIED));
    JSONObject changed=J.parse(sample.toString());try{changed.getJSONObject("worker").put("cpu",8);}catch(Exception ignored){}check("Cross-context hardware difference is reported",state(AuditReport.build(changed,nativeIp,expected,true,true),"worker",AuditReport.ISSUE));
    check("Native and browser exit disagreement is reported",state(AuditReport.build(sample,J.obj("ip","203.0.113.9"),expected,true,true),"ipv4",AuditReport.ISSUE));
    changed=J.parse(sample.toString());try{changed.getJSONObject("parent").getJSONObject("hints").getJSONArray("brands").getJSONObject(0).put("version","109");}catch(Exception ignored){}check("Client Hints version conflict is reported",state(AuditReport.build(changed,nativeIp,expected,true,true),"hints",AuditReport.ISSUE));
    changed=J.parse(sample.toString());changed.optJSONObject("parent").remove("hints");check("Missing Client Hints are unverified",state(AuditReport.build(changed,nativeIp,expected,true,true),"hints",AuditReport.UNCOVERED));
    check("Connection-change results are invalidated",state(AuditReport.build(sample,nativeIp,expected,true,false),"ipv4",AuditReport.UNCOVERED));check("Invalid IP response cannot pass",state(AuditReport.build(sample,J.obj("ip","not-an-ip"),expected,true,true),"ipv4",AuditReport.UNCOVERED));
    changed=J.parse(sample.toString());try{changed.getJSONObject("parent").put("renderer","restricted");changed.getJSONObject("worker").put("renderer","Visible fixture GPU");}catch(Exception ignored){}check("Worker-only GPU exposure is reported",state(AuditReport.build(changed,nativeIp,expected,true,true),"worker",AuditReport.ISSUE));
    check("Redacted IPv6 does not expose an address",EnvironmentAudit.address("2001:db8::8",true).equals("[地址已隐藏]"));check("Detailed local view can show the observed address",EnvironmentAudit.address("203.0.113.8",false).equals("203.0.113.8"));
    JSONObject before=J.obj("level",1,"webview","110","routeHash","a"),after=J.obj("level",2,"webview","111","routeHash","b");check("Baseline differences name only changed fields",EnvironmentAudit.differences(before,after).length()==3);check("Newly observed baseline fields do not count as changes",EnvironmentAudit.differences(before,J.obj("level",1,"webview","110","routeHash","a","exitHash","first")).length()==0);
  }
  void local(){audit.start(false,()->{check("Offline diagnostics make no public requests",audit.publicRequests==0&&audit.nativeRequests==0);check("Real parent frame is sampled",audit.report.optJSONObject("signals").optJSONObject("parent").has("ua"));check("Real child frame is sampled",audit.report.optJSONObject("signals").optJSONObject("frame").has("ua"));check("Real blob Worker is sampled without network",audit.report.optJSONObject("signals").optJSONObject("worker").has("ua"));check("Local diagnostics cannot claim network verification",state(audit.report,"network",AuditReport.UNCOVERED));check("Local RTC test is labelled as an API test",row(audit.report,"rtc").optString("detail").contains("STUN"));
    remote.evaluateJavascript("({instance:pageInstance,draft:document.querySelector('textarea').value,sends:sendCount})",raw->{JSONObject data=J.parse(raw);check("Diagnostics preserve the live chat document",mainUrl.equals(remote.getUrl())&&mainInstance.equals(data.optString("instance")));check("Diagnostics preserve the exact draft",mainDraft.equals(data.optString("draft")));check("Diagnostics never send an account message",data.optInt("sends")==0&&session.pending==null);network();});
  });}
  void network(){android.webkit.CookieManager.getInstance().setCookie("https://api.ipify.org","audit_cookie_must_not_leave=fixture; Secure");audit.start(true,()->{check("Real browser and native paths reach intercepted endpoints",audit.publicRequests>=4&&audit.nativeRequests==1);check("Explicit network check verifies observed IPv4",state(audit.report,"ipv4",AuditReport.VERIFIED));check("Network fetches do not include cookies",!audit.cookieSeen);check("Native query has no cookie or authorization",!audit.nativeCredentialSeen);check("IPv6 failure still remains uncovered",state(audit.report,"ipv6",AuditReport.UNCOVERED));check("Report does not claim all fingerprint fields pass",state(audit.report,"dns",AuditReport.UNCOVERED)&&state(audit.report,"udp",AuditReport.UNCOVERED));try{byte[] encrypted=new SecretStore(this).get("environment-audit");check("Local encrypted report persists",encrypted!=null&&J.parse(new String(encrypted,StandardCharsets.UTF_8)).has("report"));byte[] bytes=new byte[(int)new SecretStore(this).file("environment-audit").length()];try(InputStream in=new FileInputStream(new SecretStore(this).file("environment-audit"))){in.read(bytes);}check("Saved baseline is not plaintext IP or JSON",!new String(bytes,StandardCharsets.ISO_8859_1).contains("203.0.113.8")&&!new String(bytes,StandardCharsets.ISO_8859_1).contains("baseline"));}catch(Exception e){check("Report storage readable through Keystore",false);}baseline();});}
  void baseline(){audit.acceptBaseline();check("Accepting reviewed environment clears change notice",!audit.hasChanges());session.prefs.edit().putInt("privacyLevel",2).commit();session.privacy.apply();audit.refresh(true);check("Protection change is detected without clearing login",audit.hasChanges()&&mainUrl.equals(remote.getUrl()));audit.acceptBaseline();check("Updated baseline persists per environment",!new EnvironmentAudit(session).hasChanges());session.prefs.edit().putInt("privacyLevel",1).commit();session.privacy.apply();audit.acceptBaseline();
    int requests=audit.publicRequests;session.guard.setBlocked(true);session.networkReady=false;check("Network audit refuses an unprotected connection",!audit.start(true,()->{}));check("Refused audit has no test requests",audit.publicRequests==requests);session.networkReady=true;session.guard.setBlocked(false);stale();}
  void stale(){audit.delay=350;audit.start(true,()->{check("Mid-check connection change invalidates IPv4 proof",state(audit.report,"ipv4",AuditReport.UNCOVERED)&&!audit.report.optBoolean("fresh"));cancelled();});handler.postDelayed(()->session.connectionEpoch++,100);}
  void cancelled(){long previous=audit.report.optLong("at");audit.hold=true;audit.disconnected=false;audit.nativeStarted=false;audit.start(true,()->{});attempts=0;waitNative(previous);}
  void waitNative(long previous){if(!audit.nativeStarted&&attempts++<40){handler.postDelayed(()->waitNative(previous),50);return;}check("Cancellation fixture reaches a real native request",audit.nativeStarted);audit.cancel();check("Cancel destroys only the diagnostic WebView",!audit.running&&audit.diagnostic==null&&mainUrl.equals(remote.getUrl()));handler.postDelayed(()->{check("Cancel closes the native socket without queued waits",audit.disconnected);check("Cancelled job does not overwrite prior report",audit.report.optLong("at")==previous);check("Brief copy contains no raw IP or credentials",!audit.safeCopy().contains("203.0.113.8")&&!audit.safeCopy().contains("audit_cookie_must_not_leave"));write();},400);}
  void write(){try{J.write(new File(getFilesDir(),"environment-audit-results.json"),J.obj("checks",checks,"sample",audit.report,"scope","Real local frames/Worker, intercepted fake public responses, no actual account or public IP request").toString(2));}catch(Exception ignored){}if(getIntent().getBooleanExtra("showAudit",false))EnvironmentAuditUi.show(this);}
  final class FixtureAudit extends EnvironmentAudit {
    int publicRequests,nativeRequests,delay;volatile boolean hold,nativeStarted,disconnected,nativeCredentialSeen,cookieSeen;
    FixtureAudit(ChatSession s){super(s);}
    @Override WebResourceResponse resource(WebResourceRequest request){String url=request.getUrl().toString();if(!networkRun||!fresh()||!(url.equals(IPV4)||url.equals(IPV6)||url.equals(HEADERS)))return BrowserNetworkGuard.denied();publicRequests++;for(String key:request.getRequestHeaders().keySet())if(key.equalsIgnoreCase("Cookie")||key.equalsIgnoreCase("Authorization"))cookieSeen=true;String body=url.equals(IPV4)?"{\"ip\":\"203.0.113.8\"}":url.equals(IPV6)?"{\"error\":\"No IPv6 fixture\"}":J.obj("headers",J.obj("User-Agent",request.getRequestHeaders().getOrDefault("User-Agent",initial.optString("ua")))).toString();return new WebResourceResponse("application/json","UTF-8",url.equals(IPV6)?503:200,url.equals(IPV6)?"Fixture unavailable":"OK",Collections.singletonMap("Access-Control-Allow-Origin","*"),new ByteArrayInputStream(body.getBytes(StandardCharsets.UTF_8)));}
    @Override HttpURLConnection open(URL url,Proxy route){nativeRequests++;return new HttpURLConnection(url){final CountDownLatch closed=new CountDownLatch(1);public void connect(){}public boolean usingProxy(){return route!=Proxy.NO_PROXY;}public void disconnect(){disconnected=true;closed.countDown();}public int getResponseCode(){nativeStarted=true;nativeCredentialSeen=getRequestProperty("Cookie")!=null||getRequestProperty("Authorization")!=null;try{if(hold)closed.await();else if(delay>0)Thread.sleep(delay);}catch(Exception ignored){}return 200;}public InputStream getInputStream(){return new ByteArrayInputStream("{\"ip\":\"203.0.113.8\"}".getBytes(StandardCharsets.UTF_8));}};}
  }
}
