package local.pocketchat;

import android.os.*;
import android.app.*;
import android.content.*;
import org.json.*;
import java.io.*;
import java.util.*;

public class FunctionalHubTestActivity extends ContinuityFixtureActivity {
  final JSONArray checks=new JSONArray();int attempts;String instance,url;int historyReads;
  void check(String name,boolean pass){checks.put(J.obj("name",name,"pass",pass));}
  @Override public void onCreate(Bundle b){getSharedPreferences("chat",0).edit().clear().putBoolean("networkConfigured",true).putString("networkMode","external").putBoolean("requireExternalVpn",false).putBoolean("pageMode",true).putBoolean("webNotificationAsked",true).putString("conversation",ORIGIN+"c/hub-fixture").commit();super.onCreate(b);handler.postDelayed(()->ready(),100);}
  @Override void runDriver(String action,JSONObject args,Result callback){if(action.equals("chats"))historyReads++;super.runDriver(action,args,callback);}
  void ready(){if((session.navigating||session.entries.length()!=2)&&attempts++<70){handler.postDelayed(()->ready(),100);return;}url=remote.getUrl();remote.evaluateJavascript("document.querySelector('textarea').value='模块切换草稿';({instance:pageInstance})",raw->{instance=J.parse(raw).optString("instance");features();});}
  void features(){check("Five designed tabs are installed; records page remains removed",hub!=null&&hub.tabs.length==5);check("Default startup remains chat",hub.page==0);check("Eight environment slots are available",Profiles.MAX==8&&ProfileCatalog.get(this).list().length()==8);check("Existing current environment remains created",ProfileCatalog.get(this).item(0).optBoolean("created"));String old=Profiles.display(this,0);Profiles.rename(this,0,"测试环境名称");check("Environment rename is backed by shared catalog",Profiles.display(this,0).equals("测试环境名称"));Profiles.rename(this,0,old);
    JSONObject before=AppPrefs.values(this);check("Existing draft and background defaults are retained",AppPrefs.enabled(this,"saveDraft")&&AppPrefs.enabled(this,"backgroundWait"));check("Destructive cleanup and WiFi-only are opt-in",!AppPrefs.enabled(this,"cleanTemporaryCache")&&!AppPrefs.enabled(this,"wifiDownloads"));
    ProfileCatalog.get(this).draft(0,J.obj("name","未应用的名称","backgroundWait",false));check("Saving editor draft does not change active name",Profiles.display(this,0).equals(old));check("Saving editor draft does not apply preferences",AppPrefs.enabled(this,"backgroundWait"));check("Editor draft is persisted separately",J.parse(ProfileCatalog.get(this).item(0).optString("draft")).optString("name").equals("未应用的名称"));ProfileCatalog.get(this).draft(0,null);
    AppPrefs.apply(this,J.obj("saveDraft",false,"autoHistory",false));String saved=prefs.getString("draft","");input.setText("不写入的临时输入");check("Disabled draft persistence does not write new text",prefs.getString("draft","").equals(saved));check("Disabling draft persistence keeps visible input",input.getText().toString().equals("不写入的临时输入"));int count=historyReads;showDrawer();handler.postDelayed(()->{check("Visible history auto-sync switch controls actual query",historyReads==count);if(drawer!=null)drawer.dismiss();AppPrefs.apply(this,before);input.setText("仍可保存的草稿");check("Enabled draft persistence resumes",prefs.getString("draft","").equals("仍可保存的草稿"));cache();tabs();},250);
  }
  void cache(){try{File expired=new File(getCacheDir(),"download-old-orphan.part"),referenced=new File(getCacheDir(),"download-old-needed.part"),fresh=new File(getCacheDir(),"download-new-safe.part"),other=new File(getCacheDir(),"keep-user-note.txt");for(File f:new File[]{expired,referenced,fresh,other})J.write(f,"fixture");long old=System.currentTimeMillis()-31L*24*60*60*1000;expired.setLastModified(old);referenced.setLastModified(old);other.setLastModified(old);getSharedPreferences("download-tasks",0).edit().putString("rows",J.arr(J.obj("partial",referenced.getName())).toString()).commit();JSONObject scan=AppPrefs.temporaryCache(this,System.currentTimeMillis(),false);check("Cache scan identifies old unreferenced intermediates",scan.optInt("count")>=1);AppPrefs.temporaryCache(this,System.currentTimeMillis(),true);check("Cleanup removes only the eligible orphan",!expired.exists());check("Cleanup retains referenced resumable data",referenced.exists());check("Cleanup retains recent intermediate files",fresh.exists());check("Cleanup retains arbitrary user cache files",other.exists());referenced.delete();fresh.delete();other.delete();}catch(Exception e){check("Managed cache fixture completes",false);}}
  void tabs(){for(int p:new int[]{1,2,3,4}){hub.show(p);check("Native module opens: "+p,hub.panel.getVisibility()==android.view.View.VISIBLE&&hub.page==p);check("Module switching keeps same WebView and URL: "+p,url.equals(remote.getUrl()));}hub.show(0);handler.postDelayed(()->remote.evaluateJavascript("({instance:pageInstance,draft:document.querySelector('textarea').value,sends:sendCount})",raw->{JSONObject data=J.parse(raw);check("Return to chat reuses the existing document",instance.equals(data.optString("instance")));check("Return to chat preserves web draft",data.optString("draft").equals("模块切换草稿"));check("Native module clicks never submit",data.optInt("sends")==0&&session.pending==null);notice();}),300);}
  void notice(){AppPrefs.apply(this,J.obj("replyNotice",false));getSystemService(NotificationManager.class).cancel(Profiles.notification(this,4102));ChatService.completed(this,"quiet-fixture",url);boolean found=false;for(android.service.notification.StatusBarNotification n:getSystemService(NotificationManager.class).getActiveNotifications())if(n.getId()==Profiles.notification(this,4102))found=true;check("Reply notification toggle controls notification posting",!found);AppPrefs.apply(this,J.obj("replyNotice",true));check("Download notification intents keep unique task targets",!ChatService.downloadIntent(this,"file-one").equals(ChatService.downloadIntent(this,"file-two")));session.connectionStage="等待手机 VPN";NetworkJournal.record(session);String log=NetworkJournal.text(this);check("Network event log uses fixed local categories",log.contains("等待手机 VPN")&&!log.contains("exitPassword")&&!log.contains("Cookie="));check("Restored defaults keep waiting feature",AppPrefs.enabled(this,"backgroundWait"));try{J.write(new File(getFilesDir(),"functional-hub-results.json"),J.obj("checks",checks,"scope","Local intercepted chat fixtures, persistent settings and actual module views").toString(2));}catch(Exception ignored){}if(getIntent().getBooleanExtra("showHub",false))hub.show(3);}
}
