package local.pocketchat;
import android.content.*;import android.net.Uri;import android.os.*;import android.webkit.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;
public class ImagesTestActivity extends MainActivity {
 byte[] png;JSONArray checks=new JSONArray();boolean pickerImage=false;
 void check(String n,boolean b){checks.put(J.obj("name",n,"pass",b));}
 @Override public void onCreate(Bundle b){try{android.graphics.Bitmap bmp=android.graphics.Bitmap.createBitmap(240,180,android.graphics.Bitmap.Config.ARGB_8888);bmp.eraseColor(0xff67adce);ByteArrayOutputStream out=new ByteArrayOutputStream();bmp.compress(android.graphics.Bitmap.CompressFormat.PNG,100,out);bmp.recycle();png=out.toByteArray();}catch(Exception e){throw new RuntimeException(e);}getSharedPreferences("chat",0).edit().clear().commit();super.onCreate(b);setRequestedOrientation(1);handler.postDelayed(()->begin(),4000);}
 @Override void startNetwork(){prefs.edit().putBoolean("networkConfigured",true).putString("networkMode","external").putBoolean("requireExternalVpn",false).commit();session.networkReady=true;session.prefs.edit().putBoolean("requireExternalVpn",false).commit();session.guard.setBlocked(false);remote.loadUrl(ORIGIN);}
 @Override WebViewClient remoteClient(){return new WebViewClient(){@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){String data=android.util.Base64.encodeToString(png,android.util.Base64.NO_WRAP),html="<!doctype html><meta name='viewport' content='width=device-width,initial-scale=1'><button data-testid='model-switcher-dropdown-button'>Thinking</button><button aria-label='Thinking effort'>High</button><section data-turn='assistant'><div data-message-author-role='assistant' data-message-id='generated-image'><img id='picture' alt='Generated image' style='width:240px;height:180px'></div><button data-testid='copy-turn-action-button' aria-label='Copy response'>Copy</button></section><textarea id='prompt-textarea'></textarea><button data-testid='send-button' aria-label='Send'>Send</button><script>picture.src=URL.createObjectURL(new Blob([Uint8Array.from(atob('"+data+"'),c=>c.charCodeAt(0))],{type:'image/png'}));</script>";return new WebResourceResponse("text/html","UTF-8",new ByteArrayInputStream(html.getBytes(StandardCharsets.UTF_8)));}};}
 @Override public void startActivityForResult(Intent i,int req){if(req==FileDownloads.SAVE){pickerImage="image/png".equals(i.getType())&&i.getStringExtra(Intent.EXTRA_TITLE).endsWith(".png");handler.postDelayed(()->onActivityResult(req,RESULT_OK,new Intent().setData(Uri.parse("content://local.pocketchat.download-fixture/sample3.png"))),100);}else super.startActivityForResult(i,req);}
 void begin(){runDriver("transcript",new JSONObject(),r->{JSONArray list=r.optJSONArray("entries");JSONObject e=list==null?null:list.optJSONObject(0);JSONArray files=e==null?null:e.optJSONArray("downloads");check("Image-only replies retain a saveable image entry",files!=null&&files.length()==1&&files.optJSONObject(0).optString("kind").equals("image"));if(files==null||files.length()==0){write();return;}downloads.open(e.optString("id"),files.optJSONObject(0).optString("key"));handler.postDelayed(()->{boolean same=false;try{same=Arrays.equals(png,java.nio.file.Files.readAllBytes(new File(getCacheDir(),"sample3.png").toPath()));}catch(Exception ignored){}check("Image uses an image MIME type and extension",pickerImage);check("Saved PNG bytes match the displayed image",same);check("Image transfer releases the route-switch guard",!session.transferActive&&!downloads.active);if(downloads.noticeDialog!=null)downloads.noticeDialog.dismiss();original();},4500);});}
 void original(){remote.evaluateJavascript("(()=>{const p=picture.parentElement;const original=document.createElement('button');original.id='original-download';original.setAttribute('aria-label','Download original image');original.textContent='Download original image';p.append(original);const preview=document.createElement('button');preview.setAttribute('aria-label','Download image');preview.textContent='Download image';p.append(preview);})()",r->runDriver("transcript",new JSONObject(),list->{JSONObject entry=list.optJSONArray("entries").optJSONObject(0),f=entry.optJSONArray("downloads").optJSONObject(0);runDriver("file-prepare",J.obj("id",entry.optString("id"),"key",f.optString("key"),"expectedUrl",ORIGIN),prepared->remote.evaluateJavascript("(()=>{const r=document.getElementById('original-download').getBoundingClientRect();return JSON.stringify({x:r.left+r.width/2,y:r.top+r.height/2});})()",raw->{try{JSONObject rect=new JSONObject((String)new JSONTokener(raw).nextValue()),touch=prepared.optJSONObject("touch");check("Explicit original-image control is preferred over preview download",prepared.optBoolean("ok")&&prepared.optString("direct").isEmpty()&&touch!=null&&Math.abs(touch.optDouble("x")-rect.optDouble("x"))<1&&Math.abs(touch.optDouble("y")-rect.optDouble("y"))<1);}catch(Exception e){check("Original image target resolved",false);}write();}));}));}
 void write(){try{J.write(new File(getFilesDir(),"image-download-results.json"),J.obj("checks",checks).toString(2));}catch(Exception ignored){}}
}
