package local.pocketchat;
import android.app.*;import android.os.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;

public class NetworkMetricsTestActivity extends Activity {
 final Handler handler=new Handler(Looper.getMainLooper());JSONArray checks=new JSONArray();FakeNetwork n;ChatSession session;ServerSocket server;volatile boolean authenticated=false;volatile int lines=0;
 void check(String name,boolean pass){checks.put(J.obj("name",name,"pass",pass));}
 @Override public void onCreate(Bundle b){super.onCreate(b);getSharedPreferences("chat",0).edit().clear().putString("networkMode","external").putBoolean("requireExternalVpn",false).commit();session=ChatSession.get(this);n=new FakeNetwork();n.ready=true;n.currentEntry="Entry|Fixture";n.quality.configure("metrics-fixture-"+System.currentTimeMillis());n.settings=J.obj("exitHost","127.0.0.1","exitPort",1080,"exitUser","fixture","exitPassword","fixture");check("App core explicitly uses the same unified delay method as Clash",n.config(false,false).optBoolean("unified-delay"));check("New method has its own statistics profile",NativeNetwork.MEASUREMENT_PROFILE.equals("unified-delay-v1"));long now=System.currentTimeMillis();n.quality.record(n.currentEntry,100,now-2000);n.quality.record(n.currentEntry,200,now-1000);n.quality.record(n.currentEntry,-1,now);JSONObject q=n.quality.stats(n.currentEntry,now);check("Latest probe timestamp is exposed",q.optLong("lastAt")==now);check("Success ratio and jitter reflect actual samples",q.optInt("samples")==3&&q.optInt("successes")==2&&q.optLong("mean")==150&&q.optLong("jitter")==50);check("Failed probe is not displayed as zero latency",NetworkMetricsUi.latency(q,now).contains("未通过"));check("Old latency is explicitly stale",NetworkMetricsUi.latency(q,now+91000).equals("数据待更新"));check("Missing latency is not fabricated",NetworkMetricsUi.latency(new JSONObject(),now).equals("等待测量"));try{TrafficMonitor.Sample s=TrafficMonitor.parse("{\"up\":1024,\"down\":2097152,\"upTotal\":8192,\"downTotal\":9000000}",500);check("Core traffic values are interpreted as bytes per second",s.up==1024&&s.down==2097152&&NetworkMetricsUi.speed(s.up).equals("1.0 KB/s")&&NetworkMetricsUi.speed(s.down).equals("2.0 MB/s"));check("Zero traffic is valid, not a network failure",NetworkMetricsUi.speedLine(new TrafficMonitor.Sample(0,0,0,0,500),600).contains("0 B/s"));check("Stale traffic is hidden rather than shown as current",NetworkMetricsUi.speedLine(s,6000).contains("—"));check("Unknown traffic differs from idle traffic",NetworkMetricsUi.speedLine(null,600).contains("—"));boolean missing=false,negative=false;try{TrafficMonitor.parse("{}",1);}catch(Exception e){missing=true;}try{TrafficMonitor.parse("{\"up\":-1,\"down\":0,\"upTotal\":0,\"downTotal\":0}",1);}catch(Exception e){negative=true;}check("Missing and negative counters are rejected",missing&&negative);boolean bounded=false;try{TrafficMonitor.line(new ByteArrayInputStream(new byte[4097]));}catch(IOException e){bounded=true;}check("Traffic frames have a strict size bound",bounded);}catch(Exception e){check("Traffic parser fixture",false);}
  session.prefs.edit().putString("networkMode","internal").commit();session.offline=true;check("Offline header suppresses stale measurements",NetworkMetricsUi.line(session,n,now,0).contains("已断开"));session.offline=false;n.recoveryBlocked=true;check("Exit verification block is prominent",NetworkMetricsUi.line(session,n,now,0).contains("连接已停止"));n.recoveryBlocked=false;n.quality.record(n.currentEntry,120,now);check("Connected header includes measured latency",NetworkMetricsUi.line(session,n,now,0).contains("120 ms"));session.prefs.edit().putString("networkMode","external").putBoolean("requireExternalVpn",false).commit();check("External network does not claim app proxy statistics",NetworkMetricsUi.line(session,n,now,0).contains("统计未启用"));check("Too few samples remain under observation",NetworkMetricsUi.stability(J.obj("lastAt",now,"latest",100,"samples",1,"rate",1),now).contains("观察中"));check("Repeated consistent successes support recent stability",NetworkMetricsUi.stability(J.obj("lastAt",now,"latest",120,"samples",10,"rate",1,"mean",140,"jitter",20),now).equals("近期稳定"));check("Poor success ratio is visible",NetworkMetricsUi.stability(J.obj("lastAt",now,"latest",100,"samples",10,"rate",.7,"mean",100,"jitter",10),now).contains("成功率偏低"));check("Large latency variation is visible",NetworkMetricsUi.stability(J.obj("lastAt",now,"latest",100,"samples",10,"rate",1,"mean",200,"jitter",150),now).contains("波动较大"));check("Recent failure asks for recheck rather than stable label",NetworkMetricsUi.stability(q,now).equals("待复核"));manual();}
 void manual(){String before=n.currentEntry;n.measureLatency((ok,message)->{check("Manual latency probe reports its actual result",ok&&message.contains("123 ms"));check("Manual probe does not change or stop the route",n.ready&&n.currentEntry.equals(before));n.measureLatency((second,reason)->{check("Repeated manual probes are throttled",!second&&reason.contains("稍后"));stream();});});}
 void stream(){try{server=new ServerSocket(0,1,InetAddress.getByName("127.0.0.1"));n.controllerPort=server.getLocalPort();n.token="fixture-token";new Thread(()->{try(Socket socket=server.accept()){BufferedReader reader=new BufferedReader(new InputStreamReader(socket.getInputStream(),StandardCharsets.UTF_8));String header;while((header=reader.readLine())!=null&&!header.isEmpty())if(header.equals("Authorization: Bearer fixture-token"))authenticated=true;OutputStream out=socket.getOutputStream();out.write("HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nConnection: close\r\n\r\n".getBytes(StandardCharsets.UTF_8));for(int i=0;i<30;i++){out.write("{\"up\":120,\"down\":2048,\"upTotal\":900,\"downTotal\":9000}\n".getBytes(StandardCharsets.UTF_8));out.flush();lines++;Thread.sleep(100);}}catch(Exception ignored){}},"traffic-fixture").start();n.traffic.watch(true);handler.postDelayed(()->streamed(),700);}catch(Exception e){check("Loopback traffic fixture started",false);write();}}
 void streamed(){TrafficMonitor.Sample sample=n.traffic.sample;check("Traffic endpoint uses bearer authentication",authenticated);check("Streaming monitor receives real HTTP frames",sample!=null&&sample.down==2048&&sample.upTotal==900&&lines>1);long generation=n.traffic.generation;n.traffic.watch(false);check("Leaving foreground clears traffic and stops collection",!n.traffic.visible&&n.traffic.sample==null);n.traffic.publish(generation,"fixture-token",sample);check("Late frames from old monitor generation are rejected",n.traffic.sample==null);n.traffic.visible=true;n.token="changed-core-token";n.traffic.publish(n.traffic.generation,"fixture-token",sample);check("Previous core identity cannot publish new statistics",n.traffic.sample==null);n.traffic.watch(false);write();}
 class FakeNetwork extends NativeNetwork {FakeNetwork(){super(NetworkMetricsTestActivity.this);}@Override boolean coreAlive(){return true;}@Override int probe(String route){return 123;}}
 void write(){try{if(server!=null)server.close();n.traffic.watch(false);n.worker.shutdownNow();n.probes.shutdownNow();n.traffic.reader.shutdown();J.write(new File(getFilesDir(),"network-metrics-results.json"),J.obj("checks",checks).toString(2));}catch(Exception ignored){}TextView view=new TextView(this);view.setText("网络统计隔离测试完成\n"+checks.length()+" 项检查");setContentView(view);}
}
