package local.pocketchat;

import android.app.*;import android.content.*;import android.os.*;import android.view.*;import android.widget.*;
import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;

/** Isolated test app: real Mihomo parsing, real encrypted saves/IPC, fixture connection callbacks. */
public class NetworkReferenceTestActivity extends Activity {
  final Handler handler=new Handler(Looper.getMainLooper());final JSONArray checks=new JSONArray();NetworkWorkspaceUi ui;NetworkCatalog catalog;JSONObject first,second,config6,config7;byte[] providerA,providerB;long began;boolean written;
  void check(String name,boolean pass){checks.put(J.obj("name",name,"pass",pass));}
  @Override public void onCreate(Bundle state){super.onCreate(state);if(!getPackageName().endsWith(".test"))throw new IllegalStateException();if(Build.VERSION.SDK_INT>=30)getWindow().setDecorFitsSystemWindows(false);LinearLayout root=DesignUi.column(this);ReferenceUi.insets(this,root);FrameLayout host=new FrameLayout(this);root.addView(host,new LinearLayout.LayoutParams(-1,0,1));Button[] nav=new Button[5];root.addView(ReferenceUi.nav(this,3,n->{},nav));setContentView(root);ui=new NetworkWorkspaceUi(this,host);began=SystemClock.elapsedRealtime();new Thread(this::seed,"network-fixture-seed").start();}
  byte[] provider(String... nodes){JSONArray all=new JSONArray();for(String name:nodes)all.put(J.obj("name",name,"type","socks5","server","127.0.0.1","port",19000));return J.obj("proxies",all).toString().getBytes(StandardCharsets.UTF_8);}
  JSONObject config(String url,String mode,String node){return J.obj("subscriptionUrl",url,"subscriptionName",url.endsWith("a")?"测试订阅 A":"测试订阅 B","exitHost","127.0.0.1","exitPort",19001,"exitUser","fixture","exitPassword","fixture","exitName","测试固定出口","exitRegion","测试地区","entryMode",mode,"entry",node,"entryPool",J.arr(node));}
  void seed(){try{
    providerA=provider("大阪 03","大阪 01");providerB=provider("东京 02","首尔");config6=config("https://subscription.example.invalid/a","manual","Entry|大阪 03");config7=J.parse(config6.toString());
    for(int slot:new int[]{6,7}){Context c=Profiles.context(this,slot);SecretStore vault=new SecretStore(c);vault.save(slot==6?config6:config7);vault.put("subscription",providerA);vault.put("subscription-meta",J.obj("urlHash",NativeNetwork.hash(config6.optString("subscriptionUrl"))).toString().getBytes(StandardCharsets.UTF_8));vault.put("subscription-ui",J.obj("urlHash",NativeNetwork.hash(config6.optString("subscriptionUrl")),"nodes",J.arr("Entry|大阪 03","Entry|大阪 01")).toString().getBytes(StandardCharsets.UTF_8));c.getSharedPreferences("chat",0).edit().putString("networkMode","internal").putBoolean("networkConfigured",true).putString("draft","profile-"+slot+"-draft").commit();ProfileCatalog.get(this).created(slot);ProfileCatalog.get(this).rename(slot,"测试窗口 "+slot);}
    catalog=new NetworkCatalog(this);first=catalog.subscription(NativeNetwork.hash(config6.optString("subscriptionUrl")));second=catalog.addSubscription("测试订阅 B","https://subscription.example.invalid/b");if(getIntent().getBooleanExtra("ipcOnly",false)){catalog.parsed(first.optString("id"),J.arr("Entry|大阪 03","Entry|大阪 01"),providerA,0);catalog.parsed(second.optString("id"),J.arr("Entry|东京 02","Entry|首尔"),providerB,0);handler.post(()->{ui.catalog=catalog;ui.windows=WindowNetworkState.windows(this);ui.show(0);startActivity(new Intent(this,NetworkBridgeProbeActivity.class));awaitProbe(0);});return;}
    byte[] before=new SecretStore(Profiles.context(this,7)).get("network");
    NativeNetwork.previewSubscription(Profiles.context(this,0),first.optString("url"),providerA,(ok,message,nodes,bytes)->{try{check("Existing Mihomo parser reads cached subscription A",ok&&EntrySelection.strings(nodes).equals(Arrays.asList("Entry|大阪 03","Entry|大阪 01")));check("Parsing A leaves window config bytes unchanged",Arrays.equals(before,new SecretStore(Profiles.context(this,7)).get("network")));if(!ok)throw new IOException(message);catalog.parsed(first.optString("id"),nodes,bytes,0);parseB(before);}catch(Exception e){failure(e);}});
  }catch(Exception e){failure(e);}}
  void parseB(byte[] before){NativeNetwork.previewSubscription(Profiles.context(this,0),second.optString("url"),providerB,(ok,message,nodes,bytes)->{try{check("Existing Mihomo parser reads cached subscription B",ok&&EntrySelection.strings(nodes).equals(Arrays.asList("Entry|东京 02","Entry|首尔")));check("Parsing candidate subscription preserves live config",Arrays.equals(before,new SecretStore(Profiles.context(this,7)).get("network")));if(!ok)throw new IOException(message);catalog.parsed(second.optString("id"),nodes,bytes,0);coreChecks();}catch(Exception e){failure(e);}});}
  void coreChecks(){new Thread(()->{NativeNetwork engine=null;try{
    Context c=Profiles.context(this,0);engine=new NativeNetwork(c,new File(c.getNoBackupFilesDir(),"selection-fixture"),false);engine.settings=config(second.optString("url"),"random","Entry|东京 02");engine.names=EntrySelection.allowed(engine.settings,Arrays.asList("Entry|东京 02","Entry|首尔"));engine.token=UUID.randomUUID().toString();engine.controllerPort=NativeNetwork.freePort();engine.proxyPort=NativeNetwork.freePort();
    try(FileOutputStream out=new FileOutputStream(new File(engine.root,"subscription.yaml"))){out.write(providerB);}J.write(new File(engine.root,"config.json"),engine.config(true,false).toString().replace("\\/","/"));engine.launchCore();engine.readProvider();J.write(new File(engine.root,"config.json"),engine.config(false,false).toString().replace("\\/","/"));engine.api("PUT","/configs?force=true",J.obj("path",new File(engine.root,"config.json").getAbsolutePath()),5000);JSONObject group=engine.api("GET","/proxies/EntryChoice",null,3000);JSONArray all=group.optJSONArray("all");boolean selected=false,unchecked=false;for(int i=0;i<all.length();i++){selected|=all.optString(i).equals("Entry|东京 02");unchecked|=all.optString(i).equals("Entry|首尔");}check("Actual Mihomo selector excludes unchecked subscription nodes",selected&&!unchecked);boolean rejected=false;try{engine.api("PUT","/proxies/EntryChoice",J.obj("name","Entry|首尔"),3000);}catch(Exception expected){rejected=true;}check("Actual controller rejects an unchecked entry switch",rejected);engine.selectNow("Entry|东京 02");check("Actual controller accepts the checked entry",engine.api("GET","/proxies/EntryChoice",null,3000).optString("now").equals("Entry|东京 02"));
    check("Selection core checks leave live window settings intact",new SecretStore(Profiles.context(this,7)).settings().toString().equals(config7.toString()));handler.post(()->{try{modelChecks();}catch(Exception e){failure(e);}});
  }catch(Exception e){handler.post(()->failure(e));}finally{if(engine!=null){engine.stopNow();engine.worker.shutdownNow();engine.probes.shutdownNow();engine.closers.shutdownNow();engine.traffic.reader.shutdownNow();NativeNetwork.deletePreview(engine.root);}}},"selection-core-fixture").start();}
  void modelChecks()throws Exception{
    catalog=new NetworkCatalog(this);NetworkDraft draft=new NetworkDraft(7,config7,catalog);draft.mode="random";draft.subscription(second.optString("id"),catalog);check("Changing subscription clears old entry and pool",draft.entry.isEmpty()&&draft.pool.isEmpty());draft.pool.add("Entry|东京 02");draft.randomize(new Random(5));check("Candidate randomization only uses checked nodes",draft.entry.equals("Entry|东京 02"));boolean outside=false;for(int i=0;i<500;i++){draft.randomize(new Random(i));outside|=!draft.pool.contains(draft.entry);}check("Repeated randomization cannot escape checked pool",!outside);JSONObject candidate=draft.candidate(catalog);check("Changing subscription preserves the selected fixed exit",candidate.optString("exitHost").equals(config7.optString("exitHost"))&&NetworkCatalog.exitId(candidate).equals(NetworkCatalog.exitId(config7)));
    check("Model changes do not save any window settings",new SecretStore(Profiles.context(this,7)).settings().toString().equals(config7.toString()));
    JSONObject invalid=J.parse(candidate.toString());invalid.put("entry","Entry|大阪 03");boolean denied=false;try{EntrySelection.validate(invalid,EntrySelection.strings(catalog.subscription(second.optString("id")).optJSONArray("nodes")));}catch(IOException e){denied=true;}check("Old subscription entry is rejected for the new pool",denied);
    invalid=J.parse(candidate.toString());invalid.put("entryPool",new JSONArray());denied=false;try{EntrySelection.validate(invalid,EntrySelection.strings(catalog.subscription(second.optString("id")).optJSONArray("nodes")));}catch(IOException e){denied=true;}check("Empty random pool cannot be applied",denied);
    List<String> all=Arrays.asList("Entry|东京 02","Entry|首尔","Entry|大阪 03");check("Runtime candidate list excludes unchecked and foreign nodes",EntrySelection.allowed(candidate,all).equals(Collections.singletonList("Entry|东京 02")));
    candidate.put("entryMode","manual");check("Manual mode exposes exactly the selected entry to recovery",EntrySelection.allowed(candidate,all).equals(Collections.singletonList("Entry|东京 02")));
    String regex=EntrySelection.filter(Arrays.asList("Entry|a.b+(x)","Entry|other"));check("Controller group filter treats node names literally","Entry|a.b+(x)".matches(regex)&&!"Entry|axbxxxx".matches(regex));
    WindowNetworkState phone=new WindowNetworkState(this,ProfileCatalog.get(this).item(7),config7,J.obj("mode","external","configured",true,"at",System.currentTimeMillis(),"connected",true,"ip","192.0.2.7","exitId",NetworkCatalog.exitId(config7)),true,System.currentTimeMillis());check("Phone network never borrows region or IP from a previous fixed exit",!phone.internal&&phone.region.isEmpty()&&phone.ip.isEmpty());
    Context c=Profiles.context(this,0);String beforeMode=c.getSharedPreferences("chat",0).getString("networkMode","external");NetworkBridgeProbeActivity.Fixture prior=new NetworkBridgeProbeActivity.Fixture(c);prior.ready=true;prior.recoveryBlocked=true;try{c.getSharedPreferences("chat",0).edit().putString("networkMode","external").commit();JSONObject idle=WindowNetworkState.live(null,prior);check("Phone mode without a browser session never reports the old proxy as connected or blocked",!idle.optBoolean("connected")&&!idle.optBoolean("blocked")&&idle.optString("issue").isEmpty());}finally{c.getSharedPreferences("chat",0).edit().putString("networkMode",beforeMode).commit();prior.worker.shutdownNow();prior.probes.shutdownNow();prior.closers.shutdownNow();prior.traffic.reader.shutdownNow();}
    check("Library has no global default exit setting",!catalog.data.has("defaultExit"));check("No ChatSession or account WebView is created for metadata",ChatSession.peek()==null);
    ui.catalog=catalog;ui.windows=WindowNetworkState.windows(this);ui.show(0);handler.postDelayed(()->uiChecks(),300);
  }
  static String text(View v){StringBuilder out=new StringBuilder();if(v instanceof TextView)out.append(((TextView)v).getText()).append('\n');if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)out.append(text(g.getChildAt(i)));}return out.toString();}
  static TextView find(View v,String label){if(v instanceof TextView&&((TextView)v).getText().toString().equals(label))return (TextView)v;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){TextView result=find(g.getChildAt(i),label);if(result!=null)return result;}}return null;}
  JSONObject item(int slot){for(int i=0;i<ui.windows.length();i++){JSONObject item=ui.windows.optJSONObject(i);if(item.optJSONObject("row").optInt("slot")==slot)return item;}throw new IllegalArgumentException();}
  void uiChecks(){try{
    String page=text(ui.root);check("Three first-level network tabs are present",ui.tabHost.getChildCount()==1&&((LinearLayout)ui.tabHost.getChildAt(0)).getChildCount()==3&&page.contains("窗口网络")&&page.contains("订阅")&&page.contains("出口"));check("All created windows appear without an environment switch",page.contains("测试窗口 6")&&page.contains("测试窗口 7"));check("No large statistics panels are added",!page.contains("线路统计")&&!page.contains("成功率")&&!page.contains("网络所属环境"));check("Missing latency stays explicit",page.contains("延迟未测")&&!page.contains("42 ms"));
    NetworkWorkspaceUi.EditorSession editor=ui.edit(item(7));String content=text(editor.dialog.body);check("Editor contains only the three required route fields",content.contains("入口订阅")&&content.contains("入口选择")&&content.contains("固定出口")&&!content.contains("SOCKS5 服务器")&&!content.contains("订阅地址"));check("Editor uses a centered window",editor.dialog.getWindow().getAttributes().gravity==Gravity.CENTER);check("Modal width fits the current Android phone",editor.dialog.getWindow().getAttributes().width<=getResources().getDisplayMetrics().widthPixels-ReferenceUi.dp(this,36));check("Cancel leaves sealed network settings unchanged",new SecretStore(Profiles.context(this,7)).settings().toString().equals(config7.toString()));editor.dialog.cancel.run();
    NetworkDraft draft=new NetworkDraft(7,config7,catalog);draft.mode="random";draft.subscription(second.optString("id"),catalog);draft.pool.add("Entry|东京 02");draft.randomize(new Random(4));String chosen=draft.entry;
    ReferenceUi.Modal picker=ui.selectEntry(draft,()->{});handler.postDelayed(()->pickerChecks(picker,draft,chosen,0),250);
  }catch(Exception e){failure(e);}}
  void pickerChecks(ReferenceUi.Modal picker,NetworkDraft draft,String chosen,int tries){try{TextView toggle=find(picker.body,"首尔");if(toggle==null&&tries<20){handler.postDelayed(()->pickerChecks(picker,draft,chosen,tries+1),100);return;}check("Entry picker uses only the selected subscription nodes",toggle instanceof CheckBox&&find(picker.body,"大阪 03")==null);toggle.performClick();find(picker.body,"重新随机").performClick();check("Picker actions still do not change the parent candidate until confirmation",draft.pool.size()==1&&draft.entry.equals(chosen));picker.cancel.run();check("Canceling entry picker preserves detached parent candidate",draft.pool.size()==1&&draft.entry.equals(chosen));
    ui.select(1);check("Subscription tab contains library entries only",text(ui.box).contains("测试订阅 A")&&text(ui.box).contains("测试订阅 B")&&!text(ui.box).contains("测试窗口 7"));ui.select(2);check("Exit tab never offers a global default",!text(ui.box).contains("默认出口")&&text(ui.box).contains("测试固定出口"));
    startActivity(new Intent(this,NetworkBridgeProbeActivity.class));awaitProbe(0);
  }catch(Exception e){failure(e);}}
  void awaitProbe(int tries){NetworkBridge.worker.execute(()->{boolean ready=false;try{Bundle state=getContentResolver().call(NetworkBridge.uri(this,7),"state",null,null);JSONObject value=J.parse(state==null?"{}":state.getString("json","{}"));ready=value.optString("ip").equals("192.0.2.7");if(tries%10==0)J.write(new File(getFilesDir(),"network-fixture-readiness.json"),value.toString());}catch(Exception ignored){}final boolean connected=ready;handler.post(()->{if(connected)bridgeChecks();else if(tries<100)handler.postDelayed(()->awaitProbe(tries+1),300);else failure(new IOException("Profile fixture did not initialize"));});});}
  void bridgeChecks(){NetworkBridge.run(this,7,"apply",config7,"invalid-baseline",(ok,message,snapshot)->{try{check("Stale UI candidate is rejected before writing",!ok&&new SecretStore(Profiles.context(this,7)).settings().toString().equals(config7.toString()));check("Private dispatch returns state from requested profile",snapshot.optString("ip").equals("192.0.2.7"));applyChecks();}catch(Exception e){failure(e);}});}
  void applyChecks()throws Exception{
    ui.windows=WindowNetworkState.windows(this);NetworkWorkspaceUi.EditorSession editor=ui.edit(item(7));editor.draft.mode="random";editor.draft.subscription(second.optString("id"),catalog);editor.draft.pool.add("Entry|东京 02");editor.draft.randomize(new Random(1));editor.refresh.run();editor.dialog.primary().performClick();pollApplied(editor,0);
  }
  void pollApplied(NetworkWorkspaceUi.EditorSession editor,int tries){handler.postDelayed(()->{try{JSONObject actual=new SecretStore(Profiles.context(this,7)).settings();if((!actual.optString("subscriptionUrl").equals(second.optString("url"))||editor.dialog.isShowing())&&tries<100){pollApplied(editor,tries+1);return;}J.write(new File(getFilesDir(),"network-apply-observed.json"),J.obj("url",actual.optString("subscriptionUrl"),"entry",actual.optString("entry"),"modal",editor.dialog.isShowing(),"feedback",text(editor.dialog.body)).toString());check("Save-and-apply writes the candidate to the intended window",actual.optString("subscriptionUrl").equals(second.optString("url"))&&actual.optString("entry").equals("Entry|东京 02"));check("Saving profile 7 leaves profile 6 untouched",new SecretStore(Profiles.context(this,6)).settings().toString().equals(config6.toString()));check("Applying a network candidate preserves per-profile chat drafts",Profiles.context(this,7).getSharedPreferences("chat",0).getString("draft","").equals("profile-7-draft")&&Profiles.context(this,6).getSharedPreferences("chat",0).getString("draft","").equals("profile-6-draft"));check("Applied subscription cache matches selected subscription",new JSONObject(new String(new SecretStore(Profiles.context(this,7)).get("subscription-meta"),StandardCharsets.UTF_8)).optString("urlHash").equals(second.optString("id")));if(editor.dialog.isShowing())editor.dialog.dismiss();NetworkBridge.run(this,7,"measure",null,null,(ok,message,state)->{check("Window speed action calls existing complete-chain measurement",ok&&message.contains("137 ms")&&state.optInt("delay")==137);android.util.Log.i("NetworkReferenceTest","MEASURE_OBSERVED entry="+state.optString("entry"));check("Measuring does not alter configured entry",state.optString("entry").equals("Entry|东京 02"));write();});}catch(Exception e){failure(e);}},300);}
  void failure(Exception e){if(Looper.myLooper()!=Looper.getMainLooper()){handler.post(()->failure(e));return;}android.util.Log.e("NetworkReferenceTest","Scenario failed",e);check("Scenario completed without error: "+e.getClass().getSimpleName()+" · "+e.getMessage(),false);write();}
  void write(){if(written)return;written=true;try{int passed=0;for(int i=0;i<checks.length();i++)if(checks.getJSONObject(i).optBoolean("pass"))passed++;J.write(new File(getFilesDir(),"network-reference-results.json"),J.obj("passed",passed,"total",checks.length(),"checks",checks,"elapsedMs",SystemClock.elapsedRealtime()-began,"scope","Real encrypted saves and private profile IPC; real cached-subscription Mihomo parsing; network connection callbacks/latency use isolated test fixtures. No real account or public proxy reachability is claimed.").toString(2));}catch(Exception ignored){}ui.catalog=new NetworkCatalog(this);ui.windows=WindowNetworkState.windows(this);ui.focus(7);ui.show(0);}
  @Override public void onDestroy(){if(ui!=null)ui.close();super.onDestroy();}
}
