package local.pocketchat;
import android.os.*;
import android.webkit.*;
import android.view.View;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
public class OptimizationTestActivity extends MainActivity {
 JSONArray checks=new JSONArray();String target=ORIGIN+"c/optimization-fixture-"+System.currentTimeMillis();
 void check(String n,boolean ok){checks.put(J.obj("name",n,"pass",ok));}
 @Override void startNetwork(){prefs.edit().putBoolean("networkConfigured",true).commit();networkReady=true;session.networkReady=true;session.prefs.edit().putBoolean("requireExternalVpn",false).commit();session.guard.setBlocked(false);session.navigate(ORIGIN,"加载测试");}
 @Override WebViewClient remoteClient(){WebViewClient real=session.client();return new WebViewClient(){@Override public void onPageStarted(WebView v,String u,android.graphics.Bitmap i){real.onPageStarted(v,u,i);}@Override public void onPageFinished(WebView v,String u){real.onPageFinished(v,u);}@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){try{String html=asset("fixture.html");if(r.getUrl().getPath().contains("/c/")){Thread.sleep(1600);StringBuilder turns=new StringBuilder("<div id=\"turns\">");for(int i=0;i<125;i++)turns.append("<article data-message-author-role=\"user\" data-message-id=\"long-").append(i).append("\">Message ").append(i).append(" unique-search-").append(i).append("</article>");turns.append("</div>");html=html.replace("<div id=\"turns\"></div>",turns.toString());}return new WebResourceResponse("text/html","UTF-8",new ByteArrayInputStream(html.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){return blocked();}}};}
 @Override public void onCreate(Bundle b){getSharedPreferences("chat",0).edit().clear().commit();super.onCreate(b);setRequestedOrientation(1);handler.postDelayed(()->begin(),4500);}
 void begin(){JSONArray cache=new JSONArray();for(int i=0;i<125;i++)cache.put(J.obj("id","long-"+i,"role","user","text","Cached message "+i));conversations.saveMessages(target,cache);input.setText("keep draft");switchConversation(target);check("Cached conversation appears synchronously",session.showingCache&&entries.length()==125&&conversation.equals(target));check("Cached navigation keeps reader visible",loading.cover.getVisibility()!=View.VISIBLE);check("Draft editable during refresh",input.isEnabled()&&!send.isEnabled());handler.postDelayed(()->longReady(),6500);}
 void longReady(){check("More than 80 remote messages retained",entries.length()==125&&entries.optJSONObject(0).optString("text").contains("Message 0"));reader.evaluateJavascript("window.chat.debug().count",r->{check("Long conversations initially render 40 messages","40".equals(r));reader.evaluateJavascript("window.chat.expandAll();setTimeout(()=>window.scrollTo(0,700),100)",null);handler.postDelayed(()->position(),600);});}
 void position(){reader.evaluateJavascript("window.chat.debug().count",r->check("Search expands all cached history","125".equals(r)));reader.findAllAsync("unique-search-0");reader.setFindListener((active,total,done)->{if(done)check("Search finds earliest message",total>0);});input.setText("offline draft persists");session.connectivity(false);check("Offline preserves draft and transcript",input.getText().toString().equals("offline draft persists")&&entries.length()==125&&!send.isEnabled());check("Offline retains editable composer",input.isEnabled());session.attachments.put(J.obj("name","offline.pdf","uri","content://local.pocketchat.fixturefiles/document.pdf","state","unknown","mime","application/pdf"));attachments.persist();check("Attachment record persisted",prefs.getString("files:"+target,"").contains("offline.pdf"));session.connectivity(true);handler.postDelayed(()->recovered(),7500);}
 void recovered(){check("Reconnect restores conversation without submit",!session.navigating&&!session.navigationFailed&&session.pending==null);check("Reconnect keeps draft and attachment",input.getText().toString().equals("offline draft persists")&&session.attachments.length()==1);remote.evaluateJavascript("window.sendCount",r->{check("Reconnect never sends automatically","0".equals(r));try{J.write(new File(getFilesDir(),"optimization-results.json"),J.obj("checks",checks).toString(2));}catch(Exception ignored){}});}
}
