package local.pocketchat;
import android.os.*;
import android.webkit.*;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;

public class QuickSetupTestActivity extends MainActivity {
 JSONArray checks=new JSONArray();
 void check(String name,boolean ok){checks.put(J.obj("name",name,"pass",ok));}
 @Override void startNetwork(){prefs.edit().putBoolean("networkConfigured",true).putString("networkMode","external").putBoolean("requireExternalVpn",false).commit();session.networkReady=true;session.prefs.edit().putBoolean("requireExternalVpn",false).commit();session.guard.setBlocked(false);remote.loadUrl(ORIGIN);}
 @Override WebViewClient remoteClient(){return new WebViewClient(){@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){try{return new WebResourceResponse("text/html","UTF-8",getAssets().open("fixture.html"));}catch(Exception e){return blocked();}}};}
 @Override public void onCreate(Bundle b){getSharedPreferences("chat",0).edit().clear().commit();super.onCreate(b);setRequestedOrientation(1);handler.postDelayed(()->verify(),2500);}
 InputStream preset(String host){return new ByteArrayInputStream(J.obj("subscriptionUrl","https://fixture.invalid/subscription","exitHost",host,"exitPort",1080,"exitUser","fixture-user","exitPassword","fixture-password","provider","proxies: []\n").toString().getBytes(StandardCharsets.UTF_8));}
 void verify(){try{SecretStore vault=new SecretStore(this);vault.save(new JSONObject());check("Default profile imports on fresh install",vault.importDefaults(preset("fixture.invalid"),false));JSONObject saved=vault.settings();check("All five network fields prefilled",saved.optString("subscriptionUrl").startsWith("https://")&&saved.optString("exitHost").equals("fixture.invalid")&&saved.optInt("exitPort")==1080&&saved.optString("exitUser").equals("fixture-user")&&saved.optString("exitPassword").equals("fixture-password"));check("Automatic network mode enabled",prefs.getBoolean("networkConfigured",false)&&prefs.getString("networkMode","").equals("internal"));check("Provider cache installed separately",vault.get("subscription")!=null&&!saved.has("provider"));check("Defaults stored using Android Keystore",vault.file("network").isFile()&&!new String(java.nio.file.Files.readAllBytes(vault.file("network").toPath()),StandardCharsets.UTF_8).contains("fixture-password"));saved.put("exitHost","custom.invalid");vault.save(saved);check("Upgrade preserves customized network",!vault.importDefaults(preset("fixture.invalid"),false)&&vault.settings().optString("exitHost").equals("custom.invalid"));check("Explicit reset restores bundled values",vault.importDefaults(preset("fixture.invalid"),true)&&vault.settings().optString("exitHost").equals("fixture.invalid"));prefs.edit().putString("networkMode","external").putBoolean("requireExternalVpn",false).commit();FeatureDialogs.network(this);J.write(new File(getFilesDir(),"quick-setup-results.json"),J.obj("checks",checks).toString(2));}catch(Exception e){check("Setup flow completes",false);try{J.write(new File(getFilesDir(),"quick-setup-results.json"),J.obj("checks",checks,"errorType",e.getClass().getSimpleName()).toString(2));}catch(Exception ignored){}}}
}
