package local.pocketchat;
import android.os.*;import android.webkit.*;import org.json.*;import java.io.*;

public class ReaderWindowTestActivity extends MainActivity {
 JSONArray checks=new JSONArray();void check(String n,boolean b){checks.put(J.obj("name",n,"pass",b));}
 @Override void startNetwork(){session.networkReady=true;session.prefs.edit().putBoolean("requireExternalVpn",false).commit();session.guard.setBlocked(false);remote.loadUrl(ORIGIN);}
 @Override WebViewClient remoteClient(){return new WebViewClient(){@Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){try{return new WebResourceResponse("text/html","UTF-8",getAssets().open("fixture.html"));}catch(Exception e){return blocked();}}};}
 @Override public void onCreate(Bundle b){getSharedPreferences("chat",0).edit().clear().commit();super.onCreate(b);handler.postDelayed(()->begin(),2600);}
 void eval(String code,java.util.function.Consumer<JSONObject> cb){reader.evaluateJavascript("JSON.stringify((()=>{"+code+"})())",raw->{try{cb.accept(new JSONObject((String)new JSONTokener(raw).nextValue()));}catch(Exception e){check("Reader test result decoded",false);write();}});}
 void begin(){session.remove(sessionObserver);handler.removeCallbacks(ticker);reader.evaluateJavascript("window.fixtureConversation='fixture-reader-'+Date.now();window.longFixture=Array.from({length:1000},(_,i)=>({id:'row-'+i,role:i%2?'assistant':'user',text:'Message '+i+'\\n\\n'+(i%2?'$$E=mc^2$$\\n\\n```python\\nprint(123)\\n```':'Readable history paragraph')}));window.chat.receive({type:'messages',conversation:fixtureConversation,entries:longFixture,forceBottom:true})",r->handler.postDelayed(()->initial(),500));}
 void initial(){eval("return window.chat.debug()",d->{check("1000-message conversation initially renders only 40",d.optInt("count")==40&&d.optString("firstId").equals("row-960"));reader.evaluateJavascript("document.querySelector('.older-messages').click()",r->handler.postDelayed(()->earlier(),400));});}
 void earlier(){eval("return window.chat.debug()",d->{check("Earlier page adds 40 messages",d.optInt("count")==80&&d.optString("firstId").equals("row-920"));reader.evaluateJavascript("document.querySelector('.older-messages').click();document.querySelector('.older-messages').click();window.scrollTo(0,700)",r->handler.postDelayed(()->anchor(),500));});}
 void anchor(){eval("window.anchorNode=[...document.querySelectorAll('.message')].find(e=>e.getBoundingClientRect().bottom>0);window.anchorY=anchorNode.getBoundingClientRect().top;window.anchorId=anchorNode.dataset.id;window.savedFirst=chat.debug().firstId;return chat.debug()",d->{check("Normal reading window stays bounded at 120",d.optInt("count")==120);check("Reading old history disables automatic following",!d.optBoolean("follow"));reader.evaluateJavascript("longFixture.push({id:'new-reply',role:'assistant',text:'New streamed reply'});chat.receive({type:'messages',conversation:fixtureConversation,entries:longFixture})",r->handler.postDelayed(()->verifyAnchor(),400));});}
 void verifyAnchor(){eval("const node=[...document.querySelectorAll('.message')].find(e=>e.dataset.id===anchorId);return {retained:!!node,delta:node?Math.abs(node.getBoundingClientRect().top-anchorY):999,stable:chat.debug().firstId===savedFirst,follow:chat.debug().follow}",r->{check("Incoming replies retain the old reading window",r.optBoolean("retained")&&r.optBoolean("stable"));check("Incoming replies preserve the exact reading position",r.optDouble("delta",999)<3&&!r.optBoolean("follow"));reader.evaluateJavascript("document.getElementById('jump').click()",v->handler.postDelayed(()->latest(),400));});}
 void latest(){eval("return chat.debug()",r->{check("Jump to latest returns to bounded newest window",r.optInt("count")==40&&r.optString("lastId").equals("new-reply")&&r.optBoolean("follow"));eval("return chat.search('Message 0',0)",result->{check("Search finds earliest message without rendering all history",result.optInt("total")==1);handler.postDelayed(()->search(),400);});});}
 void search(){eval("return chat.debug()",r->{check("Search uses only the 40-message result window",r.optInt("count")==40&&r.optString("firstId").equals("row-0"));eval("return chat.search('Message 99',0)",result->{check("Search includes matches outside the current window",result.optInt("total")==11&&result.optInt("index")==1);eval("return chat.search('Message 99',1)",next->{check("Next search result advances by matching message",next.optInt("index")==2);reader.evaluateJavascript("chat.endSearch()",v->handler.postDelayed(()->finishTest(),400));});});});}
 void finishTest(){eval("return chat.debug()",r->{check("Closing search keeps the display bounded",r.optInt("count")<=40);write();});}
 void write(){try{J.write(new File(getFilesDir(),"reader-window-results.json"),J.obj("checks",checks).toString(2));}catch(Exception ignored){}}
}
