package local.pocketchat;

import android.os.*;import android.view.*;import android.webkit.*;import org.json.*;import java.io.*;import java.util.*;

public class WebPerformanceBenchmarkActivity extends MainActivity {
  final JSONArray phases=new JSONArray();final ArrayList<Double> frames=new ArrayList<>();boolean sampling;long lastFrame,startCpu;int attempts;
  final Choreographer.FrameCallback monitor=new Choreographer.FrameCallback(){public void doFrame(long nanos){if(!sampling)return;if(lastFrame!=0)frames.add((nanos-lastFrame)/1000000.0);lastFrame=nanos;Choreographer.getInstance().postFrameCallback(this);}};
  @Override void startNetwork(){prefs.edit().putBoolean("networkConfigured",true).putString("networkMode","external").putBoolean("requireExternalVpn",false).commit();session.networkReady=true;session.offline=false;session.prefs.edit().putBoolean("requireExternalVpn",false).commit();session.guard.setBlocked(false);remote.loadUrl(ORIGIN+"c/performance-fixture");}
  @Override WebViewClient remoteClient(){WebViewClient real=super.remoteClient();return new WebViewClient(){
    @Override public void onPageStarted(WebView v,String u,android.graphics.Bitmap i){real.onPageStarted(v,u,i);}
    @Override public void onPageFinished(WebView v,String u){real.onPageFinished(v,u);}
    @Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){try{return new WebResourceResponse("text/html","UTF-8",getAssets().open("fixture-web-performance.html"));}catch(Exception e){return blocked();}}
  };}
  @Override public void onCreate(Bundle b){if(!getPackageName().endsWith(".test"))throw new IllegalStateException("Isolated test package required");getSharedPreferences("chat",0).edit().clear().putBoolean("pageMode",true).putBoolean("webNotificationAsked",true).putBoolean("networkConfigured",true).putString("networkMode","external").putBoolean("requireExternalVpn",false).commit();super.onCreate(b);handler.postDelayed(()->ready(),1800);}
  void ready(){if(session.entries.length()!=1000&&attempts++<80){handler.postDelayed(()->ready(),400);return;}handler.postDelayed(()->phase(false),3000);}
  void phase(boolean stream){frames.clear();lastFrame=0;WebPerfStats.reset();sampling=true;startCpu=android.os.Process.getElapsedCpuTime();Choreographer.getInstance().postFrameCallback(monitor);remote.evaluateJavascript("beginPerf("+stream+")",r->handler.postDelayed(()->finishPhase(stream),12000));}
  JSONObject intervals(Collection<Double> values){ArrayList<Double> sorted=new ArrayList<>(values);Collections.sort(sorted);int n=sorted.size(),over50=0;double total=0;for(double v:sorted){total+=v;if(v>50)over50++;}double p95=n==0?0:sorted.get(Math.min(n-1,(int)(n*.95)));return J.obj("count",n,"meanMs",n==0?0:total/n,"p95Ms",p95,"maxMs",n==0?0:sorted.get(n-1),"over50ms",over50);}
  void finishPhase(boolean stream){sampling=false;Choreographer.getInstance().removeFrameCallback(monitor);long cpu=android.os.Process.getElapsedCpuTime()-startCpu;JSONObject counters=WebPerfStats.snapshot(),hostFrames=intervals(frames);remote.evaluateJavascript("JSON.stringify(endPerf())",raw->{try{JSONObject remoteResult=new JSONObject((String)new JSONTokener(raw).nextValue());JSONArray a=remoteResult.optJSONArray("intervals");ArrayList<Double> browser=new ArrayList<>();for(int i=0;a!=null&&i<a.length();i++)browser.add(a.optDouble(i));phases.put(J.obj("scenario",stream?"streaming-scroll-input":"static-scroll-input","durationMs",12000,"messageCount",session.entries.length(),"appCpuMs",cpu,"hostFrameIntervals",hostFrames,"webFrameIntervals",intervals(browser),"work",counters));}catch(Exception e){phases.put(J.obj("error",e.toString()));}if(!stream)handler.postDelayed(()->phase(true),2000);else{WebPerfStats.enabled=false;try{J.write(new File(getFilesDir(),"web-performance-benchmark.json"),J.obj("variant",getIntent().getStringExtra("variant"),"android",Build.VERSION.RELEASE,"phases",phases).toString(2));}catch(Exception ignored){}}});}
}
