package local.pocketchat;

import android.content.*;import android.database.sqlite.*;import android.os.*;import android.widget.*;import org.json.*;import java.io.*;

/** Actual native launcher, including migration of the previous shared catalog. */
public class WindowHomeTestActivity extends WindowHomeActivity {
  final JSONArray checks=new JSONArray();Intent openedIntent;int launches;
  void check(String name,boolean pass){checks.put(J.obj("name",name,"pass",pass));}
  @Override public void onCreate(Bundle b){Context root=Profiles.global(this);if(ProfileCatalog.instance!=null){ProfileCatalog.instance.close();ProfileCatalog.instance=null;}root.deleteDatabase("environment-catalog.db");SQLiteDatabase db=root.openOrCreateDatabase("environment-catalog.db",0,null);db.execSQL("CREATE TABLE environments (slot INTEGER PRIMARY KEY,name TEXT NOT NULL,created INTEGER NOT NULL DEFAULT 0,draft TEXT NOT NULL DEFAULT '',pid INTEGER NOT NULL DEFAULT 0,seen INTEGER NOT NULL DEFAULT 0,connected INTEGER NOT NULL DEFAULT 0,waiting INTEGER NOT NULL DEFAULT 0,mode TEXT NOT NULL DEFAULT '',privacy INTEGER NOT NULL DEFAULT 1)");for(int i=0;i<8;i++)db.execSQL("INSERT INTO environments(slot,name,created,draft) VALUES(?,?,?,?)",new Object[]{i,i==0?"个人主号":i==1?"工作号":i==2?"备用号":"窗口 "+(i+1),i<3?1:0,i==0?"{\"name\":\"原有编辑草稿\"}":""});db.setVersion(1);db.close();super.onCreate(b);handler.postDelayed(()->test(),300);}
  @Override public void startActivity(Intent intent){openedIntent=intent;launches++;}
  void test(){ProfileCatalog catalog=ProfileCatalog.get(this);Intent launcher=getPackageManager().getLaunchIntentForPackage(getPackageName());check("App icon resolves to the window launcher",launcher!=null&&launcher.getComponent().getClassName().endsWith("BrandLaunchActivity"));check("Native launcher does not create a chat session",ChatSession.peek()==null);check("Existing three windows survive catalog upgrade",catalog.item(0).optBoolean("created")&&catalog.item(1).optBoolean("created")&&catalog.item(2).optBoolean("created"));check("Existing names and editor drafts survive upgrade",catalog.name(0).equals("个人主号")&&catalog.item(0).optString("draft").contains("原有编辑草稿"));check("Launcher displays real window cards",cards.getChildCount()==3&&count.getText().toString().contains("3 / 8"));search.setText("工作");check("Name search filters actual cards",cards.getChildCount()==1);search.setText("");catalog.favorite(1,true);filter=1;refresh();check("Favorites persist and filter windows",catalog.item(1).optBoolean("favorite")&&cards.getChildCount()==1);filter=0;refresh();cards.getChildAt(1).performClick();check("Tapping a window routes to its owning profile",openedIntent!=null&&openedIntent.getComponent().getClassName().endsWith("ProfileActivity1")&&"chat".equals(openedIntent.getStringExtra("openWindowAction")));check("Opening records a separate last-opened timestamp",catalog.item(1).optLong("opened")>0&&lastWindow()==1);check("Window cards never submit chat content",ChatSession.peek()==null);openWindow(2,"network");check("Window network menu targets the selected profile",openedIntent.getComponent().getClassName().endsWith("ProfileActivity2")&&"network".equals(openedIntent.getStringExtra("openWindowAction")));try{android.content.pm.ActivityInfo info=getPackageManager().getActivityInfo(new ComponentName(this,DownloadCenterActivity.class),0);check("Download center is private and available without chat",!info.exported);}catch(Exception e){check("Download center is private and available without chat",false);}try{J.write(new File(getFilesDir(),"window-home-results.json"),J.obj("checks",checks,"scope","Actual native launcher; v1 catalog migration; no account or external traffic").toString(2));}catch(Exception ignored){}search.setText("");filter=0;refresh();}
}
